### ISSUE TITLE
Puppeteer: Calling I.amOnPage('/') in BeforeSuite gives error.

### ISSUE THREAD

**Issue by besrabasant** [Codeception/CodeceptJS#1002]
I am trying to all `I.amOnPage('/)` in `BeforeSuite` but on running the test I get this error.

```
Home page --
TypeError: Cannot read property 'mainFrame' of undefined
 ✖ "before all" hook: BeforeSuite in 7ms

-- FAILURES:

  1) Home page
       "before all" hook: BeforeSuite:
     Cannot read property 'goto' of undefined

```

Here the the detailed `--verbose` output.

```bash
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook Puppeteer._beforeSuite()
   [1] Queued | hook BrowserHelper._beforeSuite()
   Emitted | hook.start ([object Object])
   Emitted | step.before (I am on page "/")
   [1] Queued | hook Puppeteer._beforeStep()
   [1] Queued | hook BrowserHelper._beforeStep()
   [1] Queued | amOnPage: "/"
   Emitted | step.after (I am on page "/")
   [1] Queued | hook Puppeteer._afterStep()
   [1] Queued | hook BrowserHelper._afterStep()
   [1] Queued | step passed
   [1] Queued | return result
   [1] Queued | fire hook.passed
   [1] Queued | finish beforeSuite hook
   Emitted | step.start (I am on page "/")
 • I am on page "/"
   [1] Error | TypeError: Cannot read property 'goto' of undefined
   Emitted | step.failed (I am on page "/")
   Step finished in 0.001 sec
   [1] Error | TypeError: Cannot read property 'goto' of undefined
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook Puppeteer._failed()
   [1] <teardown> Queued | hook BrowserHelper._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
   [1] <teardown> Error | TypeError: Cannot read property 'mainFrame' of undefined
TypeError: Cannot read property 'mainFrame' of undefined
 ✖ FAILED in 11ms

   [2] Starting recording promises
   Emitted | suite.after ([object Object])
   [2] Queued | hook Puppeteer._afterSuite()
   [2] Queued | hook BrowserHelper._afterSuite()

-- FAILURES:

  1) Home page
       "before all" hook: BeforeSuite:
     Cannot read property 'goto' of undefined

  Scenario Steps:

  - I.amOnPage("/") at Context.BeforeSuite (__e2e__/home-page.test.js:4:7)

  TypeError: Cannot read property 'goto' of undefined
      at Puppeteer.amOnPage (/home/programmersedge/.nvm/versions/node/v8.9.4/lib/node_modules/codeceptjs-puppeteer/node_modules/codeceptjs/lib/helper/Puppeteer.js:369:21)
      at Step.run (/home/programmersedge/.nvm/versions/node/v8.9.4/lib/node_modules/codeceptjs-puppeteer/node_modules/codeceptjs/lib/step.js:26:47)
      at recorder.add (/home/programmersedge/.nvm/versions/node/v8.9.4/lib/node_modules/codeceptjs-puppeteer/node_modules/codeceptjs/lib/actor.js:68:23)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)


  FAIL  | 0 passed, 1 failed   // 40ms
   Emitted | global.result ([object Object])
   [2] Queued | hook Puppeteer._finishTest()
   [2] Queued | hook BrowserHelper._finishTest()
   Emitted | global.after ([object Object])

```

### Details

* CodeceptJS version:1.1.7
* NodeJS Version:8.9.4
* Operating System:Ubuntu14.04
* Configuration file:

```js
{
    "output": "./codeceptjs/output",
    "helpers": {
        "Puppeteer": {
            "url": "http://localhost",
            "show": false,
            "windowSize": "1366x768",
          },
        "BrowserHelper": {
            "require": "./codeceptjs/browser_helper.js"
        }
    },
    "include": {
        "I": "./codeceptjs/steps_file.js"
    },
    "mocha": {},
    "bootstrap": false,
    "teardown": null,
    "hooks": [],
    "tests": "__e2e__/*.test.js",
    "timeout": 10000,
    "name": "locahost"
}
```

**Comment by supports2004** [comment]
Hi , the same issue, is it resolved somehow ?

**Comment by besrabasant** [comment]
Yeah, I was trying to open the page before the browser was in an open state...

**Comment by ChpokmanKG** [comment]
> Yeah, I was trying to open the page before the browser was in an open state...

I realy didn't get it. Can you explain it cleaner to me? Please

**Comment by mighty98** [comment]
@besrabasant Can you please let know how exactly you resolved it.. I mean how you waited for browser to be In open state

**Comment by Xotabu4** [comment]
Having the same issue for Playwright setup:

```
[32me2e_1       |[0m   9) Standard Sign-In
[32me2e_1       |[0m        Password is wrong validation @40744 @touch @smoke @regression:
[32me2e_1       |[0m      Cannot read property 'goto' of undefined
[32me2e_1       |[0m       at Playwright.amOnPage (/codecept/lib/helper/Playwright.js:701:21)
[32me2e_1       |[0m       at Step.run (/codecept/lib/step.js:66:47)
[32me2e_1       |[0m       at /codecept/lib/actor.js:117:23
```


```
Scenario(`Password is wrong validation`, ({ I }) => {
  I.amOnPage('sign-in');
})
```


```
  helpers: {
    Playwright: {
      url: environment.frontendUrl.toString(),
      browser: 'chromium',
      // Restart browsers between tests
      restart: true,
      keepBrowserState: false,
      keepCookies: false,
      show: isCI,
      ignoreHTTPSErrors: true,
      chromium: {
        headless: isCI,
        defaultViewport: null,
        args: [
          '--use-fake-device-for-media-stream',
          '--use-fake-ui-for-media-stream',
          `--unsafely-treat-insecure-origin-as-secure=${environment.frontendUrl.toString()}`,
          `--unsafely-treat-insecure-origin-as-secure=${environment.apiUrl.toString()}`,
          '--disable-web-security',
          '--ignore-certificate-errors'
        ]
      }
    }
  },
```

**Comment by Bobi2000** [comment]
Facing the same issue, have you found any fixes?

**Comment by PeterNgTr** [comment]
Based on the documentation, it's designed like that 

https://codecept.io/basics/#beforesuite

If you need to run complex a setup before all tests and have to teardown this afterwards, you can use the BeforeSuite and AfterSuite functions. BeforeSuite and AfterSuite have access to the I object, but BeforeSuite/AfterSuite don't have any access to the browser, because it's not running at this moment. You can use them to execute handlers that will setup your environment. BeforeSuite/AfterSuite will work only for the file it was declared in (so you can declare different setups for files)

**Comment by aramsoltan** [comment]
@besrabasant , can you please share with us how you fix the issue?
