### ISSUE TITLE
 Puppeteer.js TypeError: msg.type is not a function

### ISSUE THREAD

**Issue by andreymaznyak** [Codeception/CodeceptJS#1009]
#### What are you trying to achieve?
I run tests and have report in log
#### What do you get instead?
I run tests and have report with many errors in log

```bash
codeceptjs run --steps --verbose
CodeceptJS v1.1.7
Using test root "C:\Projects\petgio\e2e\codecept"
...
(node:7228) UnhandledPromiseRejectionWarning: TypeError: msg.type is not a function
    at Page.page.on (C:\Projects\petgio\e2e\codecept\node_modules\codeceptjs\lib\helper\Puppeteer.js:279:31)
    at emitOne (events.js:116:13)
    at Page.emit (events.js:211:7)
    at Page._onConsoleAPI (C:\Projects\petgio\e2e\codecept\node_modules\puppeteer\lib\Page.js:400:10)
    at Session.Page.client.on.event (C:\Projects\petgio\e2e\codecept\node_modules\puppeteer\lib\Page.js:93:57)
    at emitOne (events.js:116:13)
    at Session.emit (events.js:211:7)
    at Session._onMessage (C:\Projects\petgio\e2e\codecept\node_modules\puppeteer\lib\Connection.js:210:12)
    at Connection._onMessage (C:\Projects\petgio\e2e\codecept\node_modules\puppeteer\lib\Connection.js:105:19)
    at emitOne (events.js:116:13)
(node:7228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7228) UnhandledPromiseRejectionWarning: TypeError: msg.type is not a function
    at Page.page.on (C:\Projects\petgio\e2e\codecept\node_modules\codeceptjs\lib\helper\Puppeteer.js:279:31)
    at emitOne (events.js:116:13)
    at Page.emit (events.js:211:7)
    at Page._onConsoleAPI (C:\Projects\petgio\e2e\codecept\node_modules\puppeteer\lib\Page.js:400:10)
    at Session.Page.client.on.event (C:\Projects\petgio\e2e\codecept\node_modules\puppeteer\lib\Page.js:93:57)
    at emitOne (events.js:116:13)
    at Session.emit (events.js:211:7)
    at Session._onMessage (C:\Projects\petgio\e2e\codecept\node_modules\puppeteer\lib\Connection.js:210:12)
    at Connection._onMessage (C:\Projects\petgio\e2e\codecept\node_modules\puppeteer\lib\Connection.js:105:19)
    at emitOne (events.js:116:13)
...
```

> Provide test source code if related

```js
page.on('console', (msg) => {
        this.debugSection(msg.type(), msg.args().join(' ')); // <-- error msg undefined
        consoleLogStore.add(msg);
      });
```

### Details

* CodeceptJS version: CodeceptJS v1.1.7
* NodeJS Version: v8.10.0
* Operating System: Windows 10
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Puppeteer": {
      "url": "http://localhost",
      "waitForAction": 500,
      "waitForTimeout": 10000,
      "show": true,
      "windowSize": "800x600"
    }
  },
  "include": {
    "I": "./y.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "codecept",
  "translation": "ru-RU"
}
```

**Comment by andreymaznyak** [comment]
I have bug becouse install `codeceptjs-puppeteer`.
I have install `codeceptjs@1.1.7` and resolve this bug.
Please remove this package in your site. And update tutorial https://codecept.io/puppeteer/

**Comment by pavelloz** [comment]
This is probably because `codeceptjs-puppeteer` has outdated dependencies in package.json.

https://github.com/DavertMik/codeceptjs-puppeteer/blob/master/package.json#L23-L24

**Comment by DavertMik** [comment]
Please install just puppeteer without `codeceptjs-pupeteer`
