### ISSUE TITLE
Unable to make custom hook work properly on test fail

### ISSUE THREAD

**Issue by dlopespg** [Codeception/CodeceptJS#1023]
#### What are you trying to achieve?
I am currently trying to create a new hoot to perform some actions when test fails to interact with mochawesome and send some e-mails.

running with verbose   Emitted | test.failed ([object Object]) is emmited but my hook is not triggered

#### What do you get instead?
It apperats that the hook is not activated 

> Provide console output if related. Use `--verbose` mode for more details.

```bash
PS C:\Projetos> codeceptjs run Test_test.js --steps --verbose
CodeceptJS v1.1.7
Using test root "C:\Projetos\"

Demo feature --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook WebDriverIO._beforeSuite()
   [1] Queued | hook main_Helper._beforeSuite()
 Scenario demo
   Emitted | test.before
   [1] Queued | hook WebDriverIO._before()
   [1] Queued | hook main_Helper._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "/")
   [1] Queued | hook WebDriverIO._beforeStep()
   [1] Queued | hook main_Helper._beforeStep()
   [1] Queued | amOnPage: "/"
   Emitted | step.after (I am on page "/")
   [1] Queued | hook WebDriverIO._afterStep()
   [1] Queued | hook main_Helper._afterStep()
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I click "do not work")
   [1] Queued | hook WebDriverIO._beforeStep()
   [1] Queued | hook main_Helper._beforeStep()
   [1] Queued | click: "do not work"
   Emitted | step.after (I click "do not work")
   [1] Queued | hook WebDriverIO._afterStep()
   [1] Queued | hook main_Helper._afterStep()
   [1] Queued | step passed
   [1] Queued | return result
   [1] Queued | create new promises queue for generator
   Emitted | step.start (I am on page "/")
 * I am on page "/"
   Emitted | step.passed (I am on page "/")
   Step finished in 0.694 sec
   Emitted | step.start (I click "do not work")
 * I click "do not work"
   [1] Error | Error: Clickable element do not work was not found by text|CSS|XPath
   Emitted | step.failed (I click "do not work")
   Step finished in 0.103 sec
   [1] Error | Error: Clickable element do not work was not found by text|CSS|XPath
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook WebDriverIO._failed()
   [1] <teardown> Queued | hook main_Helper._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
   [1] <teardown> Starting <generator> session
 > Screenshot has been saved to C:\Projetos\output\Scenario_demo.failed.png
 × FAILED in 1291ms

   [2] Starting recording promises
   Emitted | test.after
   [2] Queued | hook WebDriverIO._after()
   [2] Queued | hook main_Helper._after()
   Emitted | suite.after ([object Object])
   [2] Queued | hook WebDriverIO._afterSuite()
   [2] Queued | hook main_Helper._afterSuite()

-- FAILURES:

  1) Demo feature
       Scenario demo:
     Clickable element do not work was not found by text|CSS|XPath

  Scenario Steps:

  - I.click("do not work") at Test.<anonymous> (Test_test.js:11:5)
  - I.amOnPage("/") at Test.<anonymous> (Test_test.js:10:5)

  Error: Clickable element do not work was not found by text|CSS|XPath
      at new ElementNotFound (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\lib\helper\errors\ElementNotFound.js:14:11)
      at assertElementExists (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\lib\helper\WebDriverIO.js:2055:11)
      at WebDriverIO.click (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\lib\helper\WebDriverIO.js:511:7)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)


  FAIL  | 0 passed, 1 failed   // 5s
   Emitted | global.result ([object Object])
   [2] Queued | hook WebDriverIO._finishTest()
   [2] Queued | hook main_Helper._finishTest()
   Emitted | global.after ([object Object])
```

> Provide test source code if related

```js
/// <reference path="./steps.d.ts" />
/*jshint esversion: 6 */
const event = require('codeceptjs').event;

Feature('Demo feature');

Scenario('Scenario demo', function*(I) {
  I.amOnPage('/');
  I.click('do not work');
});
```
> Provide Hook file content

```js
const event = require('codeceptjs').event;

module.exports = function() {

  event.dispatcher.on(event.test.failed, function (test, error) {

    console.log('--- I am a fail --');

  });
}
```
### Details

* CodeceptJS version: 1.1.7
* NodeJS Version:v8.10.0
* Operating System:windows 10

* Configuration file:

```js
{
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost/index.html",
      "browser": "chrome",
      "windowSize": "maximize",
      "restart": true,
      "keepBrowserState": true,
      "smartWait": 2000
    },
    "main_Helper": {
      "require": "./main_helper.js"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "mocha": {
    "reporterOptions": {
      "reportDir": "output",
      "reportTitle": "Test Report",
      "uniqueScreenshotNames": "true"
    }
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": [
    "./otherHook.js"
  ],
  "tests": "*_test.js",
  "timeout": 10000,
  "name": "sts"
}
```

Thank you in advance.

**Comment by DavertMik** [comment]
I'm not sure hook was actually loaded. Please try this:

```
  "hooks": [
    "otherHook.js"
 ]
```

**Comment by dlopespg** [comment]
Got the same result, with  "./otherHook.js" and  "otherHook.js", when changing the file name to something that does not exists I got the propper error message.

```bash
Hook C:\Projetos\otherHook.jdfsdfsdfsdfds doesn't exist

Error:
    at module.exports (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\lib\hooks.js:10:13)
    at config.hooks.forEach.hook (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\lib\codecept.js:65:39)
    at Array.forEach (<anonymous>)
    at Codecept.bootstrap (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\lib\codecept.js:65:23)
    at Codecept.init (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\lib\codecept.js:48:10)
    at Command.module.exports (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\lib\command\run.js:36:14)
    at Command.listener (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\Users\d.lopes\AppData\Roaming\npm\node_modules\codeceptjs\node_modules\commander\index.js:651:12)
```

**Comment by dlopespg** [comment]
Problem solved.

in order to run codecept locally i had to use change the start command to use the following:

What I was using
C:\Projetos> **codeceptjs** run Test_test.js --steps --verbose

What I use now:
C:\Projetos> **./node_modules/.bin/codecepjs** run Test_test.js --steps --verbose

**Comment by davicho01** [comment]
Having the same problem. I guess I don't understand why it works one way and not the other.

**Comment by gaainf** [comment]
Looks like _init hook was removed in https://github.com/Codeception/CodeceptJS/commit/632dafb14c636d654da9e9f700a005441ae53df2 revision to fix https://github.com/Codeception/CodeceptJS/issues/1036 issue.
