### ISSUE TITLE
Unable to attach captures fail image to mochawesome report

### ISSUE THREAD

**Issue by dlopespg** [Codeception/CodeceptJS#1027]
#### What are you trying to achieve?
Insert image on report when test fail using mochawesome.

#### What do you get instead?
I can add an image but is registered on the report as a new scenario and test
Attached an image on how the test report is displayed.

![failscenario](https://user-images.githubusercontent.com/34516628/38755184-2c876b2c-3f3b-11e8-8afb-6ca98b0d2516.jpg)

> Provide console output if related. Use `--verbose` mode for more details.

```bash
PS C:\Projetos> ./node_modules/.bin/codeceptjs run Test_test.js --steps --reporter mochawesome --verbose


  Demo-Feature
### Fail ###    1) testScenario

  test suite
    √ add context


  1 passing (5s)
  1 failing

  1) Demo-Feature
       testScenario:
     Clickable element XPTO was not found by text|CSS|XPath

  Scenario Steps:

  - I.click("XPTO") at Test.<anonymous> (Test_test.js:7:5)
  - I.amOnPage("/") at Test.<anonymous> (Test_test.js:6:5)





[mochawesome] Report JSON saved to C:\Projetos\output\mochawesome.json

[mochawesome] Report HTML saved to C:\Projetos\output\mochawesome.html
```

> Provide test source code if related
Hook Code
```js
'use strict';
var event = require('codeceptjs').event;
const addContext = require('mochawesome/addContext');

module.exports = function() {
  event.dispatcher.on(event.test.failed, function (test, error) {
    console.log('### Fail ###');
   describe('test suite', function () {
        it('add context', function () {
          addContext(this, './testScenario.failed.png');
        })
      });
  });
}
```
Test Code
```js
Feature('Demo-Feature');
Scenario('testScenario', function*(I) {
  I.amOnPage('/');
  I.click('XPTO');
});
```

### Details

* CodeceptJS version:1.1.7
* NodeJS Version:8.10
* Operating System:Windows 10
* Configuration file:

```js
"output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost/index.html",
      "browser": "chrome",
      "windowSize": "maximize",
      "restart": true,
      "keepBrowserState": true,
      "smartWait": 2000
    },
    "main_Helper": {
      "require": "./main_helper.js"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "mocha": {
    "reporterOptions": {
      "reportDir": "output",
      "reportTitle": "Test Report",
      "uniqueScreenshotNames": "true"
    }
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": ["/hook.js"],
  "tests": "*_test.js",
  "timeout": 10000,
  "name": "sts"
}
```

**Comment by dlopespg** [comment]
Solved on hook

```bash
'use strict';
var event = require('codeceptjs').event;
const addContext = require('mochawesome/addContext');

module.exports = function() {
  event.dispatcher.on(event.test.failed, function (test, error) {  
      console.log('### Fail ###');
      addContext( test.ctx, './'+test.tile+'failed.png')
  });
}
```
