### ISSUE TITLE
Run test without browser name (BrowserStack iPhone)

### ISSUE THREAD

**Issue by pablopaul** [Codeception/CodeceptJS#1030]
#### What are you trying to achieve?
Run test on iPhone on BrowserStack with WebdriverIO helper.

#### What do you get instead?
```js
codeceptjs run-multiple local
/usr/local/lib/node_modules/codeceptjs/lib/command/run-multiple.js:113
    return suiteConf.browsers.map((b) => {
                                  ^

RangeError: Maximum call stack size exceeded
    at suiteConf.browsers.map (/usr/local/lib/node_modules/codeceptjs/lib/command/run-multiple.js:113:35)
    at Array.map (<anonymous>)
    at runSuite (/usr/local/lib/node_modules/codeceptjs/lib/command/run-multiple.js:113:31)
    at suiteConf.browsers.map (/usr/local/lib/node_modules/codeceptjs/lib/command/run-multiple.js:117:16)
    at Array.map (<anonymous>)
    at runSuite (/usr/local/lib/node_modules/codeceptjs/lib/command/run-multiple.js:113:31)
    at suiteConf.browsers.map (/usr/local/lib/node_modules/codeceptjs/lib/command/run-multiple.js:117:16)
    at Array.map (<anonymous>)
    at runSuite (/usr/local/lib/node_modules/codeceptjs/lib/command/run-multiple.js:113:31)
    at suiteConf.browsers.map (/usr/local/lib/node_modules/codeceptjs/lib/command/run-multiple.js:117:16)
```
* CodeceptJS version: codeceptjs@1.1.7
* NodeJS Version: v9.11.1
* Operating System: Mac OS X 10.13.4
* WebDriverIO
* Configuration file:

```js
exports.config = {

    tests: './*_test.js',
    timeout: 10000,
    output: './output',

    helpers: {
        WebDriverIO: {
            // load variables from the environment and provide defaults
            url: 'https://…',
            browser: 'Chrome',

            // If present in env vars, use BrowserStack, else fall back to local browser above
            user: process.env.BROWSERSTACK_USER || undefined,
            key: process.env.BROWSERSTACK_KEY || undefined,
            desiredCapabilities: {
                'os': 'Windows',
                'os_version': '10',
                'browser': 'IE',
                'browser_version': '11.0',
                'resolution': '1024x768'
            }
        }
    },

    include: {
        I: './steps_file.js'
    },
    bootstrap: false,
    mocha: {},
    name: 'codeceptjs',
    multiple: {
        remote: {
            browsers: [
                {
                    'device': 'iPhone 7',
                    'os_version': '10.3',
                }
            ],
        },
    }

};
```

Capabilities config is from here https://www.browserstack.com/automate/webdriverio

![image](https://user-images.githubusercontent.com/635526/38931057-3e72d026-4312-11e8-9281-3257d951a9b8.png)

**Comment by pablopaul** [comment]
This was a misunderstand from my side, 
as mobile `browser` I can use `iPhone` and `android`, this makes it work.

**Comment by paulcredmond** [comment]
@pablopaul I've been trying to figure this out all day, thank you! The part I was missing was `remote` in the `multiple` object.
