### ISSUE TITLE
Parallel Execution failure v1.2.0

### ISSUE THREAD

**Issue by pathakparth** [Codeception/CodeceptJS#1068]
@sveneisenschmidt 

**Below is my config file for codecept. I am trying to add parallel execution but it fails to execute.**

let browser = 'chrome';

if (process.profile === 'IE') {
browser = 'internet explorer';
}

exports.config = {
'output': './codeceptjs/output',
'helpers': {
'WebDriverIO': {
'smartWait': 1000,
'browser': browser,
'restart': false,
'url': 'http://localhost:4200',
'cssSelectorsEnabled': true,
'timeouts': {
'script': 60000,
'page load': 60000
},
'capabilities': [
{
'browserName': 'internet explorer',
'ignoreProtectedModeSettings': true,
'ignoreZoomSetting': true,
'initialBrowserUrl': 'http://localhost:4200'
}
]
},
'JSFailure': {
'require': './codeceptjs/helpers/js-failure.js'
},
'Mochawesome': {
}
},
'include': {
'I': './codeceptjs/common-steps/steps.js'
},
'mocha': {
'reporterOptions': {
'codeceptjs-cli-reporter': {
'stdout': '-',
'options': {
'verbose': false,
'steps': true
}
},
'mochawesome': {
'stdout': '-',
'options': {
'reportDir': './codeceptjs/output',
'reportPageTitle': 'Report page',
'reportFilename': 'report',
'quiet': true,
'json': true,
'html': true,
'overwrite': true,
'inline': true
}
}
}
},
'bootstrap': false,
'teardown': null,
'hooks': [],
'tests': './codeceptjs/tests/**/*-test.js',
'timeout': 10000,
'name': 'cls-ucp-web',
'multiple': {
'parallel': {
'chunks': 2,
'browsers': ['chrome']
}
}
};

**error =>**

creating output directory: E:\app\ucp\cls-ucp-web\codeceptjs\output\parallel:chunk2__browser_chrome__2
creating output directory: E:\app\ucp\cls-ucp-web\codeceptjs\output\parallel:chunk1__browser_chrome__1
path.js:33
function normalizeStringWin32(path, allowAboveRoot) {
^

RangeError: Maximum call stack size exceeded
at normalizeStringWin32 (path.js:33:30)
at Object.resolve (path.js:328:20)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:68:14)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:77:24)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
path.js:33
function normalizeStringWin32(path, allowAboveRoot) {
^

RangeError: Maximum call stack size exceeded
at normalizeStringWin32 (path.js:33:30)
at Object.resolve (path.js:328:20)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:68:14)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:77:24)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)
at sync (E:\app\ucp\cls-ucp-web\node_modules\mkdirp\index.js:78:17)

**can you please help in setting up the config ? I could not find solution for this error anywhere.**

### Details

* CodeceptJS version: 1.2.0
* NodeJS Version: v8.11.1
* Operating System: windows 
* Protractor || WebDriverIO || Nightmare version (if related) WebDriverIO

**Comment by hubidu** [comment]
I am having the same problem:

- CodeceptJS version: 1.2.0
- NodeJS Version: v8.9.4
- Operating System: windows
- WebDriverIO

> node_modules\\.bin\\codeceptjs run-multiple parallel --debug
creating output directory: C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\__out\parallel:chunk1__browser_chrome__1
creating output directory: C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\__out\parallel:chunk2__browser_chrome__2
path.js:33
function normalizeStringWin32(path, allowAboveRoot) {
                             ^

RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.resolve (path.js:338:20)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:68:14)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
path.js:33
function normalizeStringWin32(path, allowAboveRoot) {
                             ^

RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.resolve (path.js:338:20)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:68:14)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\node_modules\mkdirp\index.js:78:17)

**Comment by DavertMik** [comment]
Looks like this was not tested on Windows :disappointed:

**Comment by vigneshwar-v** [comment]
Not working on mac also.

**Comment by lukasf98** [comment]
It still doesn't work for me.
I upgraded Codecept to Version 1.2.1 but I still get the same Error.

$ codeceptjs run-multiple parallel -c codecept.conf.js --recursive
creating output directory: C:\Users\user\Documents\unfall.uitestswebsitemobile\output\screenshot\parallel:chunk1__browser_chrome__1
path.js:33
function normalizeStringWin32(path, allowAboveRoot) {
                             ^

RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.resolve (path.js:339:20)
    at sync (C:\Users\user\Documents\unfall.uitestswebsitemobile\node_modules\mkdirp\index.js:68:14)
    at sync (C:\Users\user\Documents\unfall.uitestswebsitemobile\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\user\Documents\unfall.uitestswebsitemobile\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\userr\Documents\unfall.uitestswebsitemobile\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\user\Documents\unfall.uitestswebsitemobile\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\user\Documents\unfall.uitestswebsitemobile\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\user\Documents\unfall.uitestswebsitemobile\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\user\Documents\unfall.uitestswebsitemobile\node_modules\mkdirp\index.js:78:17)

My codecept configuration:

const config = require('config');
const isDocker = require('is-docker');

exports.config = {
  'tests': './e2e/**/*.feature.js',
  'timeout': 10000,
  'output': './output/screenshot',
  'helpers': {
    'WebDriverIO': {
      'host': isDocker() ? 'selenium-chrome' : 'localhost',
      'port': isDocker() ? 24444 : 4444,
      'url': config.url,
      'waitForTimeout': 15000,
      'browser': 'chrome',
      'desiredCapabilities': {
        'chromeOptions': {
          'args': ['–-lang= de']
        }
      }
    },
    'GenericHelper': {
      'require': './e2e/helpers/page_helper.js'
    }
  },
  'include': {
    ...
  },
  'multiple': {
    'parallel': {
      'chunks': 2
    }
  },
  'mocha': {
    'reporterOptions': {
      // 'mocha-junit-reporter': '/reports/result.xml',
      'mochawesome': {
        'disableScreenshots': 'false',
        'stdout': './output/console.log',
        'options': {
          'reportDir': './output',
          'reportFilename': 'report'
        }
      },
      'codeceptjs-cli-reporter': {
        'stdout': '-',
        'options': {
          'verbose': false,
          'steps': false
        }
      }
    }
  },
  'bootstrap': false
};
