### ISSUE TITLE
Error when starting shell: TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by mirao** [Codeception/CodeceptJS#1178]
#### What are you trying to achieve?
Configure a WebDriverIO test. 
```bash
$ codeceptjs init
$ codeceptjs generate:test
$ codeceptjs shell --verbose
```

Interactive shell should be working when starting it manually. WebDriverIO methods can be executed.
#### What do you get instead?

```bash
$ codeceptjs shell --verbose
String interactive shell for current suite...
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   Emitted | test.before
   Error processing test.before event:
   TypeError: Cannot read property 'config' of undefined
    at EventEmitter.event.dispatcher.on (/usr/lib/node_modules/codeceptjs/lib/listener/config.js:33:19)
    at emitNone (events.js:111:20)
    at EventEmitter.emit (events.js:208:7)
    at Object.emit (/usr/lib/node_modules/codeceptjs/lib/event.js:49:28)
    at codecept.init (/usr/lib/node_modules/codeceptjs/lib/command/interactive.js:25:11)
    at module.exports (/usr/lib/node_modules/codeceptjs/lib/hooks.js:26:13)
    at Codecept.bootstrap (/usr/lib/node_modules/codeceptjs/lib/codecept.js:78:5)
    at Codecept.init (/usr/lib/node_modules/codeceptjs/lib/codecept.js:57:10)
    at Command.module.exports (/usr/lib/node_modules/codeceptjs/lib/command/interactive.js:14:12)
    at Command.listener (/usr/lib/node_modules/codeceptjs/node_modules/commander/index.js:315:8)
   [1] Starting <pause> session
 Interactive shell started
 Press ENTER to resume test
 - Use JavaScript syntax to try steps in action
 - Press TAB twice to see all available commands
 - Enter next to run the next step
 I.amOnPage('/');
   Emitted | step.before (I am on page "/")
   Emitted | step.after (I am on page "/")
   Emitted | step.start (I am on page "/")
   [1] <pause> Error | TypeError: Cannot read property 'url' of undefined
   Emitted | step.failed (I am on page "/")
   Emitted | step.finish (I am on page "/")
 FAIL  Cannot read property 'url' of undefined
```

> Provide test source code if related

```js
Feature('My');

Scenario('test something', (I) => {
    I.amOnPage('/');
});
```

### Details

* CodeceptJS version: 1.3.2
* NodeJS Version: v8.11.1
* Operating System: Ubuntu 18.04
* WebDriverIO
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost",
      "browser": "chrome"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "tmp"
}
```

**Comment by mirao** [comment]
Can't reproduce the issue anymore, it seems to be already fixed.
Tested with CodeceptJS 2.3.6, WebDriverIO 5.16.13
