### ISSUE TITLE
Drag And Drop By Offset using WebdriverIO

### ISSUE THREAD

**Issue by fawazfauzan** [Codeception/CodeceptJS#1201]
#### What are you trying to achieve?
I want to drag and drop but by using offset element

#### What do you get instead?
Drag and drop Can't using offset

> Provide console output if related. Use `--verbose` mode for more details.

```bash

-- FAILURES:

  1) Login
       test something:
     locator.substr is not a function

  Scenario Steps:

  - I.dragAndDrop("#draggable", 333, 7) at Object.obj.(anonymous function).obj.(anonymous function) [as dragAndDrop] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.see("Draggable") at Object.obj.(anonymous function).obj.(anonymous function) [as see] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.click("Draggable") at Object.obj.(anonymous function).obj.(anonymous function) [as click] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.click("Demo") at Object.obj.(anonymous function).obj.(anonymous function) [as click] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.see("It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using ‘lorem ipsum’ is that it has a more-or-less normal distribution of letters, as opposed to using ‘This here is content’ or ‘Osama Bin Laden wanted dead or alive’, making it look like readable text and there also has been many examples what has happened if someone has forgotten to change the dummy text for the final copywrite text.
  In Finland there was couple of years ago this one bookshop banner in public internet with ‘Buying a book is as easy as hitting a child’ text in it.") at Object.obj.(anonymous function).obj.(anonymous function) [as see] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.amOnPage("/services/") at Object.obj.(anonymous function).obj.(anonymous function) [as amOnPage] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.seeElement("p") at Object.obj.(anonymous function).obj.(anonymous function) [as seeElement] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.click("About us") at Object.obj.(anonymous function).obj.(anonymous function) [as click] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.moveCursorTo("#menu-item-158") at Object.obj.(anonymous function).obj.(anonymous function) [as moveCursorTo] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.seeCurrentUrlEquals("http://demoqa.com/") at Object.obj.(anonymous function).obj.(anonymous function) [as seeCurrentUrlEquals] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.grabCurrentUrl() at Object.obj.(anonymous function).obj.(anonymous function) [as grabCurrentUrl] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.see("Home") at Object.obj.(anonymous function).obj.(anonymous function) [as see] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)
  - I.amOnPage("/") at Object.obj.(anonymous function).obj.(anonymous function) [as amOnPage] (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:28:26)

  TypeError: locator.substr is not a function
      at isXPath (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\locator.js:251:18)
      at new Locator (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\locator.js:33:9)
      at WebDriverIO.withStrictLocator (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\helper\WebDriverIO.js:2097:13)
      at WebDriverIO.dragAndDrop (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\helper\WebDriverIO.js:1409:25)
      at Step.run (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\step.js:39:47)
      at recorder.add (C:\Users\user\AppData\Roaming\npm\node_modules\codeceptjs\lib\actor.js:68:23)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

> Provide test source code if related

```js
Feature('Login');

Scenario('test something', async (I) => {
    I.say('Saya Menuju ke Demo QA')
    I.amOnPage('/');
    I.say('Saya Melihat Home')
    I.see('Home');
    let url = await I.grabCurrentUrl();
    I.seeCurrentUrlEquals(url);
    I.moveCursorTo('#menu-item-158');
    I.click('About us');
    I.seeElement('p');
    I.amOnPage('/services/')
    I.see('It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using ‘lorem ipsum’ is that it has a more-or-less normal distribution of letters, as opposed to using ‘This here is content’ or ‘Osama Bin Laden wanted dead or alive’, making it look like readable text and there also has been many examples what has happened if someone has forgotten to change the dummy text for the final copywrite text.\nIn Finland there was couple of years ago this one bookshop banner in public internet with ‘Buying a book is as easy as hitting a child’ text in it.')
    I.click('Demo');
    I.click('Draggable');
    I.see('Draggable');
    I.dragAndDrop('#draggable', 333, 7);
    I.wait(5);
});
```

### Details

* CodeceptJS version: v1.3.3
* NodeJS Version: v10.4.0
* Operating System: windows 7 64 bit
* WebDriverIO (if related)
* Configuration file:

```js
{
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://demoqa.com/",
      "host": "localhost",
      "port": "4444",
      "protocol": "http",
      "path": "/wd/hub",
      "smartWait": 5000,
      "uniqueScreenshotNames": true,
      "windowSize": "maximize",
      "browser": "chrome"
    },
    "MyHelper": {
      "require": "./myhelper_helper.js"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "mocha": {
    "reporterOptions": {
      "reportDir": "output"
    }
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "gherkin": {},
  "tests": "./*_test.js",
  "timeout": 10000,
  "name": "ccjswebio"
}
```

**Comment by LukoyanovE** [comment]
@fawazfauzan, [dragAndDrop function](https://codecept.io/helpers/WebDriverIO/#draganddrop), should receive two arguments, both selectors.

Codecept tries to find element "333" and fails, when not found.

Do you really need to drag it to certain pixels coordinates?

**Comment by fawazfauzan** [comment]
Hai @LukoyanovE  thanks for respond, I think for now it's not necessary, i just want to try in demoqa.com about drag and drop, but condition on there drag and drop must using offset, how to use offset in codeceptjs to drag and drop  ?

**Comment by LukoyanovE** [comment]
@fawazfauzan , according to [helper's code](https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/WebDriverIO.js#L1380), which implements [this WebDriverIO code](http://webdriver.io/api/action/dragAndDrop.html) - not
dragAndDrop only drag from one element by locator to another element by locator

**Comment by LukoyanovE** [comment]
If you really need to move by some pixel values, you should write your own function in helper.
You can use [buttonDown](http://webdriver.io/api/protocol/buttonDown.html), [buttonUp](http://webdriver.io/api/protocol/buttonUp.html) and [moveToObject](http://webdriver.io/api/action/moveToObject.html) WebDriverIO's methods
