### ISSUE TITLE
"requireg(...) is not a function" when using Protractor helper

### ISSUE THREAD

**Issue by ZZaphod** [Codeception/CodeceptJS#121]
When I try to run CodeceptJS with the Pratractor helper, I'm getting the following error:

 `requireg(...) is not a function`

`TypeError:`

    at Protractor._init (/usr/lib/node_modules/codeceptjs/lib/helper/Protractor.js:83:92)
    at createHelpers (/usr/lib/node_modules/codeceptjs/lib/container.js:33:44)
    at Object.module.exports.create (/usr/lib/node_modules/codeceptjs/lib/container.js:73:15)
    at Codecept.init (/usr/lib/node_modules/codeceptjs/lib/codecept.js:42:15)
    at Command.module.exports (/usr/lib/node_modules/codeceptjs/lib/command/run.js:12:14)
    at Command.listener (/usr/lib/node_modules/codeceptjs/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/lib/node_modules/codeceptjs/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/lib/node_modules/codeceptjs/node_modules/commander/index.js:458:21) `

I'm using node.js v6.0.0 and npm v3.8.6

**Comment by DavertMik** [comment]
Probably error is in using npm v3.x
`requireg` is a package in dependencies list. Should be available...

**Comment by ZZaphod** [comment]
Thank you for your reply. The `requireg` package seems to work in other cases thought. The problem only occurs when passing arguments directly after the `requireg(...)` statement, as in `codeceptjs/lib/helper/Protractor.js:83:92`.
Maybe the problem is related to something completely unrelated.. I'm just not seeing it yet.

**Comment by DavertMik** [comment]
Maybe this is related to Protractor update....

**Comment by DavertMik** [comment]
Yes, this should be fixed in latest updated. This happened due to changes in Protractor API.
