### ISSUE TITLE
Test running in Docker fails at login, but works when running on host

### ISSUE THREAD

**Issue by ChexWarrior** [Codeception/CodeceptJS#1234]
#### What are you trying to achieve?
Hi, 

I am using CodeceptJS to test a WordPress site I manage.  One of the tests require that I login into the site as a user with a particular role to perform some specific tasks.

#### What do you get instead?
The tests run with no issue outside of a Docker container, however when I run them inside a container my tests are no longer able to login, they get an error claiming I've entered an invalid username.  What's bizarre is that the website (a local dev site) these tests run on is the same regardless of whether the tests occur in or outside of a Docker container and the user the tests login as is the same.

Here is the output of the tests that run within Docker:
```bash
docker run --rm --net=host -e CODECEPT_URL='https://test.local:8000' -v $PWD:/tests codeception/codeceptjs codeceptjs run --verbose

CodeceptJS v1.4.2
Using test root "/tests"
Helpers: Puppeteer
Plugins: screenshotOnFail

Test Site --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  Create Post as Content Manger User
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I am on page "/admin")
    Emitted | step.after (I am on page "/admin")
    Emitted | step.before (I fill field "#user_login", "testUser")
    Emitted | step.after (I fill field "#user_login", "testUser")
    Emitted | step.before (I fill field "#user_pass", "password")
    Emitted | step.after (I fill field "#user_pass", "password")
    Emitted | step.before (I click "#wp-submit")
    Emitted | step.after (I click "#wp-submit")
    Emitted | step.before (I wait for element "#wp-toolbar")
    Emitted | step.after (I wait for element "#wp-toolbar")
    Emitted | step.before (I am on page "/wp-admin/post-new.php")
    Emitted | step.after (I am on page "/wp-admin/post-new.php")
    Emitted | step.before (I fill field "#title", "hi")
    Emitted | step.after (I fill field "#title", "hi")
    Emitted | step.before (I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'))
    Emitted | step.after (I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'))
    Emitted | step.start (I am on page "/admin")
    I: login
      I am on page "/admin"
      › [Url] https://test.local:8000/wp-login.php?redirect_to=https%3A%2F%2Ftest.local%3A8000%2Fwp-admin%2F&reauth=1
      › [Browser:Log] JQMIGRATE: Migrate is installed, version 1.4.1JSHandle:JQMIGRATE: Migrate is installed, version 1.4.1
    Emitted | step.passed (I am on page "/admin")
    Emitted | step.finish (I am on page "/admin")
    Emitted | step.start (I fill field "#user_login", "testUser")
      I fill field "#user_login", "testUser"
    Emitted | step.passed (I fill field "#user_login", "testUser")
    Emitted | step.finish (I fill field "#user_login", "testUser")
    Emitted | step.start (I fill field "#user_pass", "password")
      I fill field "#user_pass", "password"
    Emitted | step.passed (I fill field "#user_pass", "password")
    Emitted | step.finish (I fill field "#user_pass", "password")
    Emitted | step.start (I click "#wp-submit")
      I click "#wp-submit"
    Emitted | step.passed (I click "#wp-submit")
    Emitted | step.finish (I click "#wp-submit")
    Emitted | step.start (I wait for element "#wp-toolbar")
      I wait for element "#wp-toolbar"
      › [Url] https://test.local:8000/wp-login.php
      › [Browser:Log] JQMIGRATE: Migrate is installed, version 1.4.1JSHandle:JQMIGRATE: Migrate is installed, version 1.4.1
    [1] Error | Error: element (#wp-toolbar) still not present on page after 5 sec
waiting for selector "#wp-toolbar" failed: timeout 5000ms exceeded
    Emitted | step.failed (I wait for element "#wp-toolbar")
    Emitted | step.finish (I wait for element "#wp-toolbar")
    [1] Error | Error: element (#wp-toolbar) still not present on page after 5 sec
waiting for selector "#wp-toolbar" failed: timeout 5000ms exceeded
    Emitted | step.failed (I am on page "/wp-admin/post-new.php")
    Emitted | step.finish (I am on page "/wp-admin/post-new.php")
    [1] Error | Error: element (#wp-toolbar) still not present on page after 5 sec
waiting for selector "#wp-toolbar" failed: timeout 5000ms exceeded
    Emitted | step.failed (I fill field "#title", "hi")
    Emitted | step.finish (I fill field "#title", "hi")
    [1] Error | Error: element (#wp-toolbar) still not present on page after 5 sec
waiting for selector "#wp-toolbar" failed: timeout 5000ms exceeded
    Emitted | step.failed (I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'))
    Emitted | step.finish (I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'))
    [1] Error | Error: element (#wp-toolbar) still not present on page after 5 sec
waiting for selector "#wp-toolbar" failed: timeout 5000ms exceeded
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, saving screenshot
 › Screenshot is saving to /tests/output/Create_Post_as_Content_Manger_User.failed.png
  ✖ FAILED in 7214ms

    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) Test Site
       Create Post as Content Manger User:
     element (#wp-toolbar) still not present on page after 5 sec
waiting for selector "#wp-toolbar" failed: timeout 5000ms exceeded

  Scenario Steps:

  - I.waitForElement("#wp-toolbar") at Object.login (custom_steps.js:28:12)
  - I.click("#wp-submit") at Object.login (custom_steps.js:27:12)
  - I.fillField("#user_pass", "password") at Object.login (custom_steps.js:26:12)
  - I.fillField("#user_login", "testUser") at Object.login (custom_steps.js:25:12)
  - I.amOnPage("/admin") at Object.login (custom_steps.js:24:12)

  Error: element (#wp-toolbar) still not present on page after 5 sec
  waiting for selector "#wp-toolbar" failed: timeout 5000ms exceeded
      at waiter.catch (/codecept/lib/helper/Puppeteer.js:1451:13)
      at <anonymous>


  FAIL  | 0 passed, 1 failed   // 7s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

Here is the output of the tests running outside of a container:
```
npx codeceptjs run test.js --verbose

CodeceptJS v1.4.2
Using test root "/Users/someUser/Projects/puppeteer-wordpress-tests"
Helpers: Puppeteer
Plugins: screenshotOnFail

Test Site --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  Create Post as Content Manger User
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I am on page "/admin")
    Emitted | step.after (I am on page "/admin")
    Emitted | step.before (I fill field "#user_login", "testUser")
    Emitted | step.after (I fill field "#user_login", "testUser")
    Emitted | step.before (I fill field "#user_pass", "password")
    Emitted | step.after (I fill field "#user_pass", "password")
    Emitted | step.before (I click "#wp-submit")
    Emitted | step.after (I click "#wp-submit")
    Emitted | step.before (I wait for element "#wp-toolbar")
    Emitted | step.after (I wait for element "#wp-toolbar")
    Emitted | step.before (I am on page "/wp-admin/post-new.php")
    Emitted | step.after (I am on page "/wp-admin/post-new.php")
    Emitted | step.before (I fill field "#title", "vi")
    Emitted | step.after (I fill field "#title", "vi")
    Emitted | step.before (I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'))
    Emitted | step.after (I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'))
    Emitted | step.start (I am on page "/admin")
    I: login
      I am on page "/admin"
      › [Url] https://test.local:8000/wp-login.php?redirect_to=https%3A%2F%2Ftest.local%3A8000%2Fwp-admin%2F&reauth=1
      › [Browser:Log] JQMIGRATE: Migrate is installed, version 1.4.1JSHandle:JQMIGRATE: Migrate is installed, version 1.4.1
    Emitted | step.passed (I am on page "/admin")
    Emitted | step.finish (I am on page "/admin")
    Emitted | step.start (I fill field "#user_login", "testUser")
      I fill field "#user_login", "testUser"
    Emitted | step.passed (I fill field "#user_login", "testUser")
    Emitted | step.finish (I fill field "#user_login", "testUser")
    Emitted | step.start (I fill field "#user_pass", "password")
      I fill field "#user_pass", "password"
    Emitted | step.passed (I fill field "#user_pass", "password")
    Emitted | step.finish (I fill field "#user_pass", "password")
    Emitted | step.start (I click "#wp-submit")
      I click "#wp-submit"
    Emitted | step.passed (I click "#wp-submit")
    Emitted | step.finish (I click "#wp-submit")
    Emitted | step.start (I wait for element "#wp-toolbar")
      I wait for element "#wp-toolbar"
      › [Url] https://test.local:8000/wp-admin/
      › [Browser:Error] Failed to load resource: net::ERR_NAME_NOT_RESOLVED
      › [Browser:Error] Failed to load resource: net::ERR_NAME_NOT_RESOLVED
      › [Browser:Log] JQMIGRATE: Migrate is installed, version 1.4.1JSHandle:JQMIGRATE: Migrate is installed, version 1.4.1
      › [Browser:Warning] Mixed Content: The page at 'https://test.local:8000/wp-admin/' was loaded over HTTPS, but requested an insecure image 'http://netdna.yoast.com/yoast-logo-rss.png'. This co…
      › [Browser:Warning] Mixed Content: The page at 'https://test.local:8000/wp-admin/' was loaded over HTTPS, but requested an insecure image 'http://netdna.yoast.com/email_sub.png'. This content…
    Emitted | step.passed (I wait for element "#wp-toolbar")
    Emitted | step.finish (I wait for element "#wp-toolbar")
    Emitted | step.start (I am on page "/wp-admin/post-new.php")
    I: createPost
      I am on page "/wp-admin/post-new.php"
      › [Url] https://test.local:8000/wp-admin/post-new.php
      › [Browser:Log] JQMIGRATE: Migrate is installed, version 1.4.1JSHandle:JQMIGRATE: Migrate is installed, version 1.4.1
    Emitted | step.passed (I am on page "/wp-admin/post-new.php")
    Emitted | step.finish (I am on page "/wp-admin/post-new.php")
    Emitted | step.start (I fill field "#title", "vi")
      I fill field "#title", "vi"
    Emitted | step.passed (I fill field "#title", "vi")
    Emitted | step.finish (I fill field "#title", "vi")
    Emitted | step.start (I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'))
      I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active')
    Emitted | step.passed (I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'))
    Emitted | step.finish (I execute script () => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'))
    Emitted | step.before (I execute script bodyText => tinyMCE.activeEditor.setContent(`<p>${bodyText}</p>`), "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicw…
    Emitted | step.after (I execute script bodyText => tinyMCE.activeEditor.setContent(`<p>${bodyText}</p>`), "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicwu…
    Emitted | step.start (I execute script bodyText => tinyMCE.activeEditor.setContent(`<p>${bodyText}</p>`), "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicwu…
      I execute script bodyText => tinyMCE.activeEditor.setContent(`<p>${bodyText}</p>`), "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicwu. Lej olukeabu zijor lod …
    Emitted | step.passed (I execute script bodyText => tinyMCE.activeEditor.setContent(`<p>${bodyText}</p>`), "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicw…
    Emitted | step.finish (I execute script bodyText => tinyMCE.activeEditor.setContent(`<p>${bodyText}</p>`), "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicw…
    Emitted | step.before (I click "#set-post-thumbnail")
    Emitted | step.after (I click "#set-post-thumbnail")
    Emitted | step.before (I wait for element ".media-router > a:last-child")
    Emitted | step.after (I wait for element ".media-router > a:last-child")
    Emitted | step.before (I click ".media-router > a:last-child")
    Emitted | step.after (I click ".media-router > a:last-child")
    Emitted | step.before (I wait for element "div.thumbnail img")
    Emitted | step.after (I wait for element "div.thumbnail img")
    Emitted | step.before (I click "li.attachment")
    Emitted | step.after (I click "li.attachment")
    Emitted | step.before (I wait for element "div.attachment-details")
    Emitted | step.after (I wait for element "div.attachment-details")
    Emitted | step.before (I grab attribute from "li.attachment img", "src")
    Emitted | step.after (I grab attribute from "li.attachment img", "src")
    Emitted | step.start (I click "#set-post-thumbnail")
      I click "#set-post-thumbnail"
    Emitted | step.passed (I click "#set-post-thumbnail")
    Emitted | step.finish (I click "#set-post-thumbnail")
    Emitted | step.start (I wait for element ".media-router > a:last-child")
      I wait for element ".media-router > a:last-child"
    Emitted | step.passed (I wait for element ".media-router > a:last-child")
    Emitted | step.finish (I wait for element ".media-router > a:last-child")
    Emitted | step.start (I click ".media-router > a:last-child")
      I click ".media-router > a:last-child"
    Emitted | step.passed (I click ".media-router > a:last-child")
    Emitted | step.finish (I click ".media-router > a:last-child")
    Emitted | step.start (I wait for element "div.thumbnail img")
      I wait for element "div.thumbnail img"
    Emitted | step.passed (I wait for element "div.thumbnail img")
    Emitted | step.finish (I wait for element "div.thumbnail img")
    Emitted | step.start (I click "li.attachment")
      I click "li.attachment"
    Emitted | step.passed (I click "li.attachment")
    Emitted | step.finish (I click "li.attachment")
    Emitted | step.start (I wait for element "div.attachment-details")
      I wait for element "div.attachment-details"
    Emitted | step.passed (I wait for element "div.attachment-details")
    Emitted | step.finish (I wait for element "div.attachment-details")
    Emitted | step.start (I grab attribute from "li.attachment img", "src")
      I grab attribute from "li.attachment img", "src"
    Emitted | step.passed (I grab attribute from "li.attachment img", "src")
    Emitted | step.finish (I grab attribute from "li.attachment img", "src")
    Emitted | step.before (I click "button.media-button-select")
    Emitted | step.after (I click "button.media-button-select")
    Emitted | step.before (I wait for element "#set-post-thumbnail img")
    Emitted | step.after (I wait for element "#set-post-thumbnail img")
    Emitted | step.before (I click "#publish")
    Emitted | step.after (I click "#publish")
    Emitted | step.before (I wait for navigation )
    Emitted | step.after (I wait for navigation )
    Emitted | step.before (I see "Post published")
    Emitted | step.after (I see "Post published")
    Emitted | step.before (I grab attribute from "#message p a", "href")
    Emitted | step.after (I grab attribute from "#message p a", "href")
    Emitted | step.start (I click "button.media-button-select")
      I click "button.media-button-select"
    Emitted | step.passed (I click "button.media-button-select")
    Emitted | step.finish (I click "button.media-button-select")
    Emitted | step.start (I wait for element "#set-post-thumbnail img")
      I wait for element "#set-post-thumbnail img"
    Emitted | step.passed (I wait for element "#set-post-thumbnail img")
    Emitted | step.finish (I wait for element "#set-post-thumbnail img")
    Emitted | step.start (I click "#publish")
      I click "#publish"
      › [Url] https://test.local:8000/wp-admin/post-new.php?wp-post-new-reload=true
    Emitted | step.passed (I click "#publish")
    Emitted | step.finish (I click "#publish")
    Emitted | step.start (I wait for navigation )
      I wait for navigation
      › [Url] https://test.local:8000/wp-admin/post.php?post=2943&action=edit&message=6
      › [Browser:Log] JQMIGRATE: Migrate is installed, version 1.4.1JSHandle:JQMIGRATE: Migrate is installed, version 1.4.1
      › [Url] https://test.local:8000/wp-admin/post.php?post=2943&action=edit
    Emitted | step.passed (I wait for navigation )
    Emitted | step.finish (I wait for navigation )
    Emitted | step.start (I see "Post published")
      I see "Post published"
    Emitted | step.passed (I see "Post published")
    Emitted | step.finish (I see "Post published")
    Emitted | step.start (I grab attribute from "#message p a", "href")
      I grab attribute from "#message p a", "href"
    Emitted | step.passed (I grab attribute from "#message p a", "href")
    Emitted | step.finish (I grab attribute from "#message p a", "href")
    Emitted | step.before (I am on page "https://test.local:8000/2018/09/28/vi/")
    Emitted | step.after (I am on page "https://test.local:8000/2018/09/28/vi/")
    Emitted | step.before (I see "vi")
    Emitted | step.after (I see "vi")
    Emitted | step.before (I see "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicwu. Lej olukeabu zijor lod nafwufzij cozcegov iko irihalhi sebnok goz ninut tii…
    Emitted | step.after (I see "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicwu. Lej olukeabu zijor lod nafwufzij cozcegov iko irihalhi sebnok goz ninut tiik…
    Emitted | step.before (I see in source "https://test.local:8000/wp-content/uploads/2018/05/cute-150x150.png")
    Emitted | step.after (I see in source "https://test.local:8000/wp-content/uploads/2018/05/cute-150x150.png")
    Emitted | step.before (I grab attribute from "#wp-admin-bar-logout > a", "href")
    Emitted | step.after (I grab attribute from "#wp-admin-bar-logout > a", "href")
    Emitted | step.start (I am on page "https://test.local:8000/2018/09/28/vi/")
      I am on page "https://test.local:8000/2018/09/28/vi/"
      › [Url] https://test.local:8000/2018/09/28/vi/
      › [Browser:Error] Failed to load resource: the server responded with a status of 404 ()
      › [Browser:Log] JQMIGRATE: Migrate is installed, version 1.4.1JSHandle:JQMIGRATE: Migrate is installed, version 1.4.1
    Emitted | step.passed (I am on page "https://test.local:8000/2018/09/28/vi/")
    Emitted | step.finish (I am on page "https://test.local:8000/2018/09/28/vi/")
    Emitted | step.start (I see "vi")
      I see "vi"
    Emitted | step.passed (I see "vi")
    Emitted | step.finish (I see "vi")
    Emitted | step.start (I see "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicwu. Lej olukeabu zijor lod nafwufzij cozcegov iko irihalhi sebnok goz ninut tiik…
      I see "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicwu. Lej olukeabu zijor lod nafwufzij cozcegov iko irihalhi sebnok goz ninut tiikmen bi. Orzehki zakoj lat…
    Emitted | step.passed (I see "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicwu. Lej olukeabu zijor lod nafwufzij cozcegov iko irihalhi sebnok goz ninut tii…
    Emitted | step.finish (I see "Niberpul ul cojo gomaw zehi otcileri afapieri cosadejo oh goc wu eh nosulu neka gicwu. Lej olukeabu zijor lod nafwufzij cozcegov iko irihalhi sebnok goz ninut tii…
    Emitted | step.start (I see in source "https://test.local:8000/wp-content/uploads/2018/05/cute-150x150.png")
      I see in source "https://test.local:8000/wp-content/uploads/2018/05/cute-150x150.png"
    Emitted | step.passed (I see in source "https://test.local:8000/wp-content/uploads/2018/05/cute-150x150.png")
    Emitted | step.finish (I see in source "https://test.local:8000/wp-content/uploads/2018/05/cute-150x150.png")
    Emitted | step.start (I grab attribute from "#wp-admin-bar-logout > a", "href")
    I: logout
      I grab attribute from "#wp-admin-bar-logout > a", "href"
    Emitted | step.passed (I grab attribute from "#wp-admin-bar-logout > a", "href")
    Emitted | step.finish (I grab attribute from "#wp-admin-bar-logout > a", "href")
    Emitted | step.before (I am on page "https://test.local:8000/wp-login.php?action=logout&_wpnonce=3d10de1cc8")
    Emitted | step.after (I am on page "https://test.local:8000/wp-login.php?action=logout&_wpnonce=3d10de1cc8")
    Emitted | step.before (I see "You are now logged out")
    Emitted | step.after (I see "You are now logged out")
    Emitted | step.start (I am on page "https://test.local:8000/wp-login.php?action=logout&_wpnonce=3d10de1cc8")
      I am on page "https://test.local:8000/wp-login.php?action=logout&_wpnonce=3d10de1cc8"
      › [Url] https://test.local:8000/wp-login.php?loggedout=true
      › [Browser:Log] JQMIGRATE: Migrate is installed, version 1.4.1JSHandle:JQMIGRATE: Migrate is installed, version 1.4.1
    Emitted | step.passed (I am on page "https://test.local:8000/wp-login.php?action=logout&_wpnonce=3d10de1cc8")
    Emitted | step.finish (I am on page "https://test.local:8000/wp-login.php?action=logout&_wpnonce=3d10de1cc8")
    Emitted | step.start (I see "You are now logged out")
      I see "You are now logged out"
    Emitted | step.passed (I see "You are now logged out")
    Emitted | step.finish (I see "You are now logged out")
    Emitted | test.passed ([object Object])
    Emitted | test.finish ([object Object])
  ✔ OK in 21168ms

    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

  OK  | 1 passed   // 21s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

Here is the actual test source code
```js
Feature('Test Site');

Scenario('Create Post as Content Manger User', async (I) => {
  I.login();
  await I.createPost();
  await I.logout();
});
```
I have created some custom steps to make writing tests easier, here are the definitions for login, createPost and logout:
```js
const chance = require('chance').Chance();

const loginDefaults = {
  url: '/admin',
  username: 'testUser',
  password: 'password',
};

const logoutDefaults = {
  message: 'You are now logged out',
};

const createPostDefaults = {
  url: '/wp-admin/post-new.php',
  title: false,
  body: false,
  successMsg: 'Post published',
};

module.exports = function customSteps() {
  return actor({
    login: function login(options = {}) {
      const params = Object.assign({}, loginDefaults, options);
      this.amOnPage(params.url);
      this.fillField('#user_login', params.username);
      this.fillField('#user_pass', params.password);
      this.click('#wp-submit');
      this.waitForElement('#wp-toolbar');
    },
    logout: async function logout(options = {}) {
      const params = Object.assign({}, logoutDefaults, options);
      this.amOnPage(await this.grabAttributeFrom('#wp-admin-bar-logout > a', 'href'));
      this.see(params.message);
    },
    createPost: async function createPost(options = {}) {
      const params = Object.assign({}, createPostDefaults, options);
      const title = params.title ? params.title : chance.word({ length: 2 });
      const body = params.body ? params.body : chance.paragraph({ sentences: 3 });

      // submit post
      this.amOnPage(params.url);
      this.fillField('#title', title);

      // check if the RTE is in visual or text mode
      const visualModeActive = await this.executeScript(() => document.querySelector('#wp-content-wrap').classList.contains('tmce-active'));

      if (visualModeActive) {
        await this.executeScript(bodyText => tinyMCE.activeEditor.setContent(`<p>${bodyText}</p>`), body);
      } else {
        this.fillField('#content', body);
      }

      // set featured image
      this.click('#set-post-thumbnail');
      this.waitForElement('.media-router > a:last-child');
      this.click('.media-router > a:last-child');
      this.waitForElement('div.thumbnail img');
      this.click('li.attachment');
      this.waitForElement('div.attachment-details');
      const selectedImgSrc = await this.grabAttributeFrom('li.attachment img', 'src');
      this.click('button.media-button-select');
      this.waitForElement('#set-post-thumbnail img');

      // submit post
      this.click('#publish');
      this.waitForNavigation();
      this.see(params.successMsg);

      // verify post was created correctly
      this.amOnPage(await this.grabAttributeFrom('#message p a', 'href'));
      this.see(title);
      this.see(body);
      this.seeInSource(selectedImgSrc);
    },
  });
};
```

### Details

* CodeceptJS version: 1.4.2
* NodeJS Version: v10.11.0 (I rebuilt the CodeceptJS image with this version as well)
* Operating System: MacOS "High Sierra"
* Puppeteer version: 1.8.0
* Configuration file:
```js
exports.config = {
  output: './output',
  helpers: {
    Puppeteer: {
      url: process.env.CODECEPT_URL,
      show: false,
      chrome: {
        ignoreHTTPSErrors: true,
        args: ['--no-sandbox'],
      },
      waitForTimeout: 5000,
    },
  },
  mocha: {},
  bootstrap: false,
  teardown: null,
  hooks: [],
  plugins: {
    screenshotOnFail: {
      enabled: true,
    },
  },
  include: {
    I: './custom_steps.js',
  },
  tests: './*_test.js',
  timeout: 10000,
  name: 'puppeteer-wordpress-tests',
};
```

**Comment by ChexWarrior** [comment]
Took a break from this and now I'm playing around with it again.  It turns out the issue is actually being caused by this.fillFields within the login method.  For whatever reason it chops off the first character of the value I pass to the user login field.

**Comment by ChexWarrior** [comment]
Okay, so it seems to have all come down to just timing.  I added **networkidle0** to my **waitForNavigation** configuration option and the **fillFields** method now correctly enters the entire string I pass.
