### ISSUE TITLE
(node:18328) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by LucasBrazi06** [Codeception/CodeceptJS#1275]
#### What are you trying to achieve?
No error after running a test.

#### What do you get instead?
The tests succeed but got an exception.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
(node:18328) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
    at Connection.NavigatorWatcher._eventListeners.helper.addEventListener (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\puppeteer\lib\FrameManager.js:1146:117)
    at emitNone (events.js:111:20)
    at Connection.emit (events.js:208:7)
    at Connection._onClose (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\puppeteer\lib\Connection.js:123:10)
    at WebSocketTransport._ws.addEventListener.event (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\puppeteer\lib\WebSocketTransport.js:45:22)
    at WebSocket.onClose (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\puppeteer\node_modules\ws\lib\event-target.js:124:16)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\puppeteer\node_modules\ws\lib\websocket.js:172:10)
    at Socket.socketOnClose (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\puppeteer\node_modules\ws\lib\websocket.js:781:15)
  -- ASYNC --
    at Frame.<anonymous> (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.waitForNavigation (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\puppeteer\lib\Page.js:599:49)
    at Page.<anonymous> (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\puppeteer\lib\helper.js:145:23)
    at Puppeteer.waitForNavigation (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\codeceptjs\lib\helper\Puppeteer.js:1711:22)
    at Puppeteer.proceedClick (C:\Data\Private\ChargeAngels\ev-dashboard-new\node_modules\codeceptjs\lib\helper\Puppeteer.js:1804:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)```

> Provide test source code if related

### Details

* CodeceptJS version: 1.9.0
* NodeJS Version: 8.11.3
* Operating System: Windows 10
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
{
   "output": "./output",
   "helpers": {
      "Puppeteer": {
         "url": "http://localhost:45000",
         "waitForNavigation": "networkidle0",
         "waitForAction": 200,
         "show": false,
         "restart": false,
         "windowSize": "1600x1200"
      },
      "Mochawesome": {
         "uniqueScreenshotNames": "true"
      }
   },
   "include": {
      "I": "./test/utils/Actor.js",
      "emailServer": "./test/utils/EmailServer.js",
      "loginPage": "./test/pages/LoginPage.js",
      "authLayoutPage": "./test/pages/AuthLayoutPage.js",
      "registerPage": "./test/pages/RegisterPage.js",
      "mailboxPage": "./test/pages/MailboxPage.js"
   },
   "mocha": {
      "reporterOptions": {
         "reportDir": "output"
      }
   },
   "bootstrap": false,
   "teardown": null,
   "hooks": [],
   "gherkin": {},
   "tests": "./test/tests/**/*Test.js",
   "timeout": 10000,
   "name": "ev-dashboard-new",
   "multiple": {
      "parallel": {
         "chunks": 2
      }
   }
}```

**Comment by PeterNgTr** [comment]
@DavertMik do you have some times for it?

**Comment by LukoyanovE** [comment]
@PeterNgTr , please, share your failing test code

**Comment by PeterNgTr** [comment]
@LukoyanovE just any test it will throw that error at the end

**Comment by LucasBrazi06** [comment]
Yes indeed, any tests whether it fails or not will lead to this exception.

**Comment by PeterNgTr** [comment]
Seemed that codeceptjs 1.4.4 doesn't produce this exception anymore. Just tried this morning.

**Comment by DavertMik** [comment]
Thanks @luismanuel001 for fixing this )

**Comment by LucasBrazi06** [comment]
> Seemed that codeceptjs 1.4.4 doesn't produce this exception anymore. Just tried this morning.

I'm using the version codeceptjs V1.9.0 or do you mean a dependency ?

**Comment by PeterNgTr** [comment]
use the codeceptJS v1.4.4 and that's it.

**Comment by LucasBrazi06** [comment]
You want me to downgrade to 1.4.4 instead of fixing it in 1.9.9 or I don't get it!?

**Comment by luismanuel001** [comment]
@LucasBrazi06 You are confusing codeceptjs (latest is v1.4.4) with puppeteer (latest is v1.9.0). upgrade your codeceptJS to v1.4.4 and try to see if it fixes your problem.

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 You are confusing codeceptjs (latest is v1.4.4) with puppeteer (latest is v1.9.0). upgrade your codeceptJS to v1.4.4 and try to see if it fixes your problem.

Sorry for the confusion!
I just upgraded to codeceptjs 1.4.4 and it works fine.
Thanks for your support!
