### ISSUE TITLE
Could not include object Step Definition from ./step_definitions/steps.js

### ISSUE THREAD

**Issue by natkrish** [Codeception/CodeceptJS#1282]
#### What are you trying to achieve?
I have a project in BDD setup using protractor helper. I normally run my features using tags like this - codeceptjs run --grep "@tag". Its been running absolutely fine until 23.10.2018.But it started failing since yesterday

#### What do you get instead?
Could not include object Step Definition from ./step_definitions/steps.js from module 'C:\Users\krish.murthy\intellijworkspace\codeceptjs-atdd-qa\step_definitions\steps.js'
Unexpected token {

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Error:
    at loadSupportObject (C:\Users\krish.murthy\node_modules\codeceptjs\lib\container.js:255:11)
    at loadGherkinSteps (C:\Users\krish.murthy\node_modules\codeceptjs\lib\container.js:244:5)
    at Function.create (C:\Users\krish.murthy\node_modules\codeceptjs\lib\container.js:36:25)
    at Codecept.init (C:\Users\krish.murthy\node_modules\codeceptjs\lib\codecept.js:37:15)
    at Command.module.exports (C:\Users\krish.murthy\node_modules\codeceptjs\lib\command\run.js:35:14)
    at Command.listener (C:\Users\krish.murthy\node_modules\codeceptjs\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:160:13)
    at Command.parseArgs (C:\Users\krish.murthy\node_modules\codeceptjs\node_modules\commander\index.js:654:12)
    at Command.parse (C:\Users\krish.murthy\node_modules\codeceptjs\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\krish.murthy\node_modules\codeceptjs\bin\codecept.js:139:9)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

### Details

* CodeceptJS version: 1.4.3
* NodeJS Version: 9.5.0
* Operating System: Windows 10
* Protractor  (if related)
* Configuration file:

```js
{
  "output": "./output",
  "helpers": {
    "Protractor": {
      "url": "http://localhost",
      "browser": "chrome",
      "smartWait": 1000,
      "restart": false,
      "angular": false,
      "chromeOptions": {
        "args": [
          "--window-size=1920,1080"
        ]
      }
    }
  },
  "include": {
    "I": "./steps_file.js",
  },
  "mocha": {
    "reporterOptions": {
      "reportDir": "output"
    },
    "name": "codeceptjs"
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "gherkin": {
    "features": "./features/*.feature",
    "steps": [
      "./step_definitions/steps.js"
    ]
  },
  "plugins": {
    "screenshotOnFail": {
      "enabled": true
    },
    "allure": {
      "enabled": true,
      "reportDir": "output"
    }
  },
  "multiple": {
    "parallel": {
      "chunks": 2
    }
  },
  "tests": "./*_test.js",
  "timeout": 1000,
  "Mochawesome": {
    "uniqueScreenshotNames": "true"
  }
}
```

**Comment by LukoyanovE** [comment]
Error message looks like there are typo in steps.

23.10.2018 Codeceptjs 1.4.4 was released with changes in it's init. But I don't see, how it affects You.
Can you share steps.js file?
To see, if there are any error

**Comment by LukoyanovE** [comment]
With which version of codeceptjs did you start to receive this message?

**Comment by GSasu** [comment]
I have experienced a similar behavior in the following situation:
- Had the project running codeceptjs version below 1.4.X
- Having pageObjects or StepObjects that use the _init declaration to enable I access i.e:
```
let I;

module.exports = {
    _init() {
        I = actor();
    },
```

- upgrading codeceptjs to 1.4.X and generating a new pageobject manually or automatic ending up with this new format:

```
const I = actor();

module.exports = {

  // insert your locators and methods here
}
```

- Ended up having to different style of objects and resulting in the same error you experienced.
- If this is your case, the solution is to stick to one single format by either migrating all files to the new style or keeping them in the older one but then again you would have to generate the file manually every time or modify after generation.

**Comment by arifkhanaj** [comment]
In my case it was a typo in steps file.

**Comment by Kstheking** [comment]
In my case I forgot to declare a step function `async` when it was using `await` inside of it, apparently this error will be raised for any error in your steps files
