### ISSUE TITLE
Unable to type and select any value from dropdown combobox.

### ISSUE THREAD

**Issue by vishal-lehar** [Codeception/CodeceptJS#1345]
#### What are you trying to achieve?
After login, need to select user account from a dropdown list, by typing or selecting name.
But unable to do it so.
#### What do you get instead?
can not type in to combobox to select a value 
     Clickable element valueCustomer was not found by text|CSS|XPath

> Provide console output if related. Use `--verbose` mode for more details.

```bash
codeceptjs run --steps --verbose
CodeceptJS v1.4.5
Using test root "/Users/kkkkkppppwal/test"
Helpers: WebDriverIO
Plugins: screenshotOnFail

Test1 --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  test something
    Emitted | test.before ([object Object])
16:20:59.392 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "chromeOptions": {
  },
  "handlesAlerts": true,
  "javascriptEnabled": true,
  "locationContextEnabled": true,
  "loggingPrefs": {
    "browser": "ALL",
    "driver": "ALL"
  },
  "requestOrigins": {
    "url": "http:\u002f\u002fwebdriver.io",
    "version": "4.14.0",
    "name": "webdriverio"
  },
  "rotatable": true
}
16:20:59.395 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052) on port 6700
Only local connections are allowed.
16:21:00.931 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
16:21:01.054 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session a24ab68fb2756fed40aac2094d903434 (org.openqa.selenium.chrome.ChromeDriverService)
    Emitted | test.start ([object Object])
    Emitted | step.before (I am on page "https://portal-stag.kkk.kkk.ppp/portal/")
    Emitted | step.after (I am on page "https://portal-stag.kkk.kkk.ppp/portal/")
    Emitted | step.before (I see "portal Login")
    Emitted | step.after (I see "portal Login")
    Emitted | step.before (I fill field "myusername", "xxx.yyyy+one@xxx.yyyy")
    Emitted | step.after (I fill field "myusername", "xxx.yyyy+one@xxx.yyyy")
    Emitted | step.before (I fill field "mypassword", "pppp@123")
    Emitted | step.after (I fill field "mypassword", "pppp@123")
    Emitted | step.before (I click "Submit")
    Emitted | step.after (I click "Submit")
    Emitted | step.before (I see "portal Panel")
    Emitted | step.after (I see "portal Panel")
    Emitted | step.before (I wait for visible "input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']", 30)
    Emitted | step.after (I wait for visible "input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']", 30)
    Emitted | step.before (I select option "valueCustomer", "xxx yyyy ( - Account No: 00098765 )")
    Emitted | step.after (I select option "valueCustomer", "xxx yyyy ( - Account No: 00098765 )")
    Emitted | step.before (I click "submit")
    Emitted | step.after (I click "submit")
    Emitted | step.start (I am on page "https://portal-stag.kkk.kkk.ppp/portal/")
    I am on page "https://portal-stag.kkk.kkk.ppp/portal/"
    Emitted | step.passed (I am on page "https://portal-stag.kkk.kkk.ppp/portal/")
    Emitted | step.finish (I am on page "https://portal-stag.kkk.kkk.ppp/portal/")
    Emitted | step.start (I see "portal Login")
    I see "portal Login"
    Emitted | step.passed (I see "portal Login")
    Emitted | step.finish (I see "portal Login")
    Emitted | step.start (I fill field "myusername", "xxx.yyyy+one@xxx.yyyy")
    I fill field "myusername", "xxx.yyyy+one@xxx.yyyy"
    Emitted | step.passed (I fill field "myusername", "xxx.yyyy+one@xxx.yyyy")
    Emitted | step.finish (I fill field "myusername", "xxx.yyyy+one@xxx.yyyy")
    Emitted | step.start (I fill field "mypassword", "pppp@123")
    I fill field "mypassword", "pppp@123"
    Emitted | step.passed (I fill field "mypassword", "pppp@123")
    Emitted | step.finish (I fill field "mypassword", "pppp@123")
    Emitted | step.start (I click "Submit")
    I click "Submit"
    Emitted | step.passed (I click "Submit")
    Emitted | step.finish (I click "Submit")
    Emitted | step.start (I see "portal Panel")
    I see "portal Panel"
    Emitted | step.passed (I see "portal Panel")
    Emitted | step.finish (I see "portal Panel")
    Emitted | step.start (I wait for visible "input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']", 30)
    I wait for visible "input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']", 30
    [1] Error | Error: element (input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']) still not visible after 30 sec
    Emitted | step.failed (I wait for visible "input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']", 30)
    Emitted | step.finish (I wait for visible "input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']", 30)
    [1] Error | Error: element (input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']) still not visible after 30 sec
    Emitted | step.failed (I select option "valueCustomer", "xxx yyyy ( - Account No: 00098765 )")
    Emitted | step.finish (I select option "valueCustomer", "xxx yyyy ( - Account No: 00098765 )")
    [1] Error | Error: element (input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']) still not visible after 30 sec
    Emitted | step.failed (I click "submit")
    Emitted | step.finish (I click "submit")
    [1] Error | Error: element (input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']) still not visible after 30 sec
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, saving screenshot
 › Screenshot has been saved to /Users/kkkkkppppwal/test/output/test_something.failed.png
  ✖ FAILED in 41576ms

    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) Test1
       test something:
     element (input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']) still not visible after 30 sec
  
  Scenario Steps:
  
  - I.waitForVisible("input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']", 30) at Test.Scenario (test1_test.js:27:4)
  - I.see("portal Panel") at Test.Scenario (test1_test.js:10:4)
  - I.click("Submit") at Test.Scenario (test1_test.js:9:4)
  - I.fillField("mypassword", "pppp@123") at Test.Scenario (test1_test.js:8:4)
  - I.fillField("myusername", "xxx.yyyy+one@xxx.yyyy") at Test.Scenario (test1_test.js:7:4)
  - I.see("portal Login") at Test.Scenario (test1_test.js:6:4)
  - I.amOnPage("https://portal-stag.kkk.kkk.ppp/portal/") at Test.Scenario (test1_test.js:5:4)
  
  Error: element (input[valueCustomer='xxx yyyy ( - Account No: 00098765 )']) still not visible after 30 sec
      at new WaitUntilTimeoutError (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:149:12)
      at /usr/local/lib/node_modules/webdriverio/build/lib/commands/waitUntil.js:29:19


  FAIL  | 0 passed, 1 failed   // 44s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
16:21:42.773 INFO [ActiveSessions$1.onStop] - Removing session a24ab68fb2756fed40aac2094d903434 (org.openqa.selenium.chrome.ChromeDriverService)
kkkFoxs-MacBook:test kkkkkppppwal$ 

```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: v1.4.5
* NodeJS Version: v10.12.0
* Operating System: MAC OS
* WebDriverIO : 
* Configuration file:
ChromeDriver 2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5)
Chrome: 70.xx.xx.110 latest
```js
# {
  "browserName": "chrome",
  "chromeOptions": {
  },
  "handlesAlerts": true,
  "javascriptEnabled": true,
  "locationContextEnabled": true,
  "loggingPrefs": {
    "browser": "ALL",
    "driver": "ALL"
  },
  "requestOrigins": {
    "url": "http:\u002f\u002fwebdriver.io",
    "version": "4.14.0",
    "name": "webdriverio"
  },
  "rotatable": true
}

```

**Comment by PeterNgTr** [comment]
@vishal-lehar too old versions. Closing for now. Just reopen if you encounter the same issue with latest version.
