### ISSUE TITLE
seeInField not work for textarea for webdriverio

### ISSUE THREAD

**Issue by Vorobeyko** [Codeception/CodeceptJS#1359]
#### What are you trying to achieve?
I want to check what value was setted to textarea

#### What do you get instead?
I get error 
```js
  - I.seeInField({"css":"textarea"}, "Hello world") at Test.Scenario.only (tests/user-scenario/Forms/Platinum/happy-path.test.js:14:11)
  - I.fillField({"css":"textarea"}, "Hello world") at Test.Scenario.only (tests/user-scenario/Forms/Platinum/happy-path.test.js:13:11)
  - I.saveScreenshot("debug.png") at Test.Scenario.only (tests/user-scenario/Forms/Platinum/happy-path.test.js:12:11)
  - I.amOnPage("https://html.com/tags/textarea/") at Test.Scenario.only (tests/user-scenario/Forms/Platinum/happy-path.test.js:11:11)

  TypeError: Cannot read property 'indexOf' of null
      at Object.comparator (node_modules/codeceptjs/lib/assert/include.js:16:23)
      at InclusionAssertion.assert (node_modules/codeceptjs/lib/assert.js:36:36)
      at Object.browser.elementIdAttribute.then.res (node_modules/codeceptjs/lib/helper/WebDriverIO.js:2010:144)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:191:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:540:32
      at _fulfilled (node_modules/q/q.js:854:54)
      at node_modules/q/q.js:883:30
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:624:44
```

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

If in proceedSeeField add part of code, test will be work is good
``` js
if (tag.value === 'textarea') {
    const proceedTextArea = el => this.browser.getValue(el).then(res => stringIncludes(`fields by ${field}`)[assertType](value, res));
    return proceedTextArea(res.selector)
  }
```

### Details

* CodeceptJS version: 1.4.6
* NodeJS Version: v10.14.0
* Operating System: Ubuntu 18.94
* Protractor || WebDriverIO || Nightmare version (if related) WebDriverIO
* Configuration file: 

```js
# paste suite config here
```

**Comment by SimonKlausLudwig** [comment]
Any update on this ?

**Comment by kobenguyent** [comment]
Please reopen if you encounter this with latest version.
