### ISSUE TITLE
selectOption not working with Material UI example

### ISSUE THREAD

**Issue by xavierguarch** [Codeception/CodeceptJS#1373]
#### What are you trying to achieve?

Use `I.selectOption("gender","Female")` in a test to select an option in a React project that's using Material UI form controls. I have set up this working example project to show the failure: 
https://github.com/xavierguarch/codecept_mui_example_1

#### What do you get instead?

The following error is shown:
```bash
Error: Option Female in gender was found neither by visible text not by value
```

This is detailed output of test execution:
```bash
$ codeceptjs run --steps --verbose
CodeceptJS v1.4.6
Using test root "c:\arrel\git\codecept_mui_example_1"
Helpers: WebDriverIO
Plugins: screenshotOnFail

Basic tests with Material-UI --
  ...
  √ OK in 1532ms

    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])
Select option in Material-UI --
    Emitted | suite.before ([object Object])
  Test select option
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I am on page "/")
    Emitted | step.after (I am on page "/")
    Emitted | step.before (I click "Super Secret Password")
    Emitted | step.after (I click "Super Secret Password")
    Emitted | step.before (I see "1-2-3-4-5")
    Emitted | step.after (I see "1-2-3-4-5")
    Emitted | step.before (I select option "gender", "Female")
    Emitted | step.after (I select option "gender", "Female")
    Emitted | step.before (I wait 3)
    Emitted | step.after (I wait 3)
    Emitted | step.before (I click "OK")
    Emitted | step.after (I click "OK")
    Emitted | step.start (I am on page "/")
    Test: I
      I am on page "/"
    Emitted | step.passed (I am on page "/")
    Emitted | step.finish (I am on page "/")
    Emitted | step.start (I click "Super Secret Password")
      I click "Super Secret Password"
    Emitted | step.passed (I click "Super Secret Password")
    Emitted | step.finish (I click "Super Secret Password")
    Emitted | step.start (I see "1-2-3-4-5")
      I see "1-2-3-4-5"
    Emitted | step.passed (I see "1-2-3-4-5")
    Emitted | step.finish (I see "1-2-3-4-5")
    Emitted | step.start (I select option "gender", "Female")
      I select option "gender", "Female"
    [1] Error | Error: Option Female in gender was found neither by visible text not by value
    Emitted | step.failed (I select option "gender", "Female")
    Emitted | step.finish (I select option "gender", "Female")
    [1] Error | Error: Option Female in gender was found neither by visible text not by value
    Emitted | step.failed (I wait 3)
    Emitted | step.finish (I wait 3)
    [1] Error | Error: Option Female in gender was found neither by visible text not by value
    Emitted | step.failed (I click "OK")
    Emitted | step.finish (I click "OK")
    [1] Error | Error: Option Female in gender was found neither by visible text not by value
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
 » <screenshotOnFail> Test failed, saving screenshot
 » Screenshot has been saved to c:\arrel\git\codecept_mui_example_1\test\output\Test_select_option.failed.png
  × FAILED in 1766ms

    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) Select option in Material-UI
       Test select option:
     Option Female in gender was found neither by visible text not by value

  Scenario Steps:

  - I.selectOption("gender", "Female") at Test.I (test\selectoption_test.js:7:5)
  - I.see("1-2-3-4-5") at Test.I (test\selectoption_test.js:6:5)
  - I.click("Super Secret Password") at Test.I (test\selectoption_test.js:5:5)
  - I.amOnPage("/") at Test.I (test\selectoption_test.js:4:5)

  Error: Option Female in gender was found neither by visible text not by value
      at new ElementNotFound (C:\Users\sysadmin\AppData\Roaming\nvm\v10.10.0\node_modules\codeceptjs\lib\helper\errors\ElementNotFound.js:14:11)
      at WebDriverIO.selectOption (C:\Users\sysadmin\AppData\Roaming\nvm\v10.10.0\node_modules\codeceptjs\lib\helper\WebDriverIO.js:651:13)
      at process._tickCallback (internal/process/next_tick.js:68:7)


  FAIL  | 1 passed, 1 failed   // 8s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

See test source code at: [selectoption_test.js](https://github.com/xavierguarch/codecept_mui_example_1/blob/master/test/selectoption_test.js)

### Details

The following project can be used to reproduce the bug:
https://github.com/xavierguarch/codecept_mui_example_1

* CodeceptJS version: v1.4.6
* NodeJS Version: v10.10.0
* Operating System: Windows 10
* WebDriverIO: v4.14.1
* Configuration file:

```js
{
  "tests": "./test/*_test.js",
  "timeout": 10000,
  "output": "./test/output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost:3000",
      "browser": "chrome"
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {},
  "name": "create-react-app"
}
```

**Comment by xavierguarch** [comment]
Hi there! If you need any other info to reproduce it, just let me know.
