### ISSUE TITLE
Shell fails to start 

### ISSUE THREAD

**Issue by smozely** [Codeception/CodeceptJS#138]
When trying to run the shell on a pretty fresh install I get the following error.

```
$ codeceptjs shell
Test root is assumed to be /Users/steve/src/codeceptjs
String interactive shell for current suite...
/Users/steve/src/codeceptjs/node_modules/codeceptjs/lib/command/interactive.js:18
  recorder.finishHandler(() => event.dispatcher.emit(event.test.teardown));
           ^

TypeError: recorder.finishHandler is not a function
    at Command.module.exports (/Users/steve/src/Atomic/codeceptjs/node_modules/codeceptjs/lib/command/interactive.js:18:12)
    at Command.listener (/Users/steve/src/Atomic/codeceptjs/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/Users/steve/src/Atomic/codeceptjs/node_modules/commander/index.js:615:12)
    at Command
```

**Comment by smozely** [comment]
Closing as I see its a dup of #67
