### ISSUE TITLE
Appium: Cannot find module 'babel-polyfill

### ISSUE THREAD

**Issue by hubidu** [Codeception/CodeceptJS#1391]
#### What are you trying to achieve?

I want to run my Appium tests using codeceptjs 1.4.6. When I do npm install and then run my tests with 

```
codeceptjs run
```

I get...

#### What do you get instead?

```bash

Cannot find module 'babel-polyfill'

Error:
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\cucumber-expressions\test\custom_parameter_type_test.js:10:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.mocha.loadFiles (C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\codeceptjs\lib\mochaFactory.js:48:40)
    at Mocha.run (C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\mocha\lib\mocha.js:536:10)
    at Codecept.run (C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\codeceptjs\lib\codecept.js:161:11)

    at codecept.runBootstrap (C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\codeceptjs\lib\command\run.js:41:16)
    at module.exports (C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\codeceptjs\lib\hooks.js:26:13)
    at Codecept.runBootstrap (C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\codeceptjs\lib\codecept.js:108:5)
    at Command.module.exports (C:\Users\stefan.huber\projects\codeceptjs-mobile\node_modules\codeceptjs\lib\command\run.js:37:14)

```

> Provide test source code if related

It seems that somehow codeceptjs picks up the  **bdd interface** (see cucumber-expressions stackframe in stacktrace).
The problem seems to be related to the **tests** config parameter:

```js
{
...
 "tests": "./**/*_test.js",
...
}
```

Somehow the pattern "./**/*_test.js" picks up tests located in the cucumber expression package and runs them. You can also see this in the stacktrace. Somehow the custom_parameter_type_test.js in cucumber-expressions has been executed.

When I change tests to "./my-test-folder/**/*_test.js" everything works fine since with this pattern codeceptjs will not find the tests in the cucumber-expression package.

### Details

* CodeceptJS version: 1.4.6
* NodeJS Version: 8.11.3
* Operating System: Windows/Linux
* Appium/WebdriverIO

**Comment by PeterNgTr** [comment]
@hubidu did you get the same issue with latest codeceptjs?

**Comment by dapriett** [comment]
try ` "tests": "./!(node_modules)/**/*_test.js" `

**Comment by kobenguyent** [comment]
Please reopen if you encounter this with latest version.
