### ISSUE TITLE
WebDriver: Error message on I.saveScreenshot 

### ISSUE THREAD

**Issue by hubidu** [Codeception/CodeceptJS#1422]
#### What are you trying to achieve?

Given the following test

```js
Feature('Search holiday destinations @datadriven', { retry: 1 })

const destinations = new DataTable(['destination', 'airport']);
destinations.add(['Mallorca', 'München'])
destinations.add(['Mallorca', 'Frankfurt'])

Data(destinations).Scenario(`When I search for various holiday destinations from different airports I should always get some results @search @holiday`,
async (I, current) => {

    I.say('I goto CHECK24 Reise')
    I.amOnPage('https://urlaub.check24.de/produkte')

    I.say('I enter destination')
    I.fillField('body #c24-travel-destination-element', current.destination)

    I.say('I enter origin')
    // I.pressKey('Enter')
    I.wait(1)
    I.pressKey('Tab')
    I.fillField('body #c24-travel-airport-element', current.airport)
    // I.pressKey('Enter')
    I.wait(1)

    I.saveScreenshot('after-destination-airport.png')

    I.say('I select the duration of my trip')
    I.pressKey('Tab')
    I.pressKey('Tab')
    I.pressKey('Tab')
    I.pressKey('Tab')
    I.pressKey('Tab')
    I.wait(1)
    // I.clickVisible('label[for="duration-2"]')
    I.selectOption('#c24-travel-travel-duration-element', '1w')

    I.say('I click the search button')
    I.click('Reise finden')

    I.say('I check the results')
    I.waitInUrl('/suche')
    I.waitForText('Ergebnisse', '.js-hotel-headline')
    I.waitForInvisible('span.detached-loader')
    I.waitForVisible('.hotel-list-offer-link')
    I.seeElement('.hotel-list-offer-link')
})
```

#### What do you get instead?

When codeceptjs hits line

```
I.saveScreenshot('after-destination-airport.png')
```

Then I get this error message:

```
 directory (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\__out) doesn't exist
```

> Provide console output if related. Use `--verbose` mode for more details.

```bash
1) Search holiday destinations @datadriven
       When I search for various holiday destinations from different airports I should always get some results @search @holiday | {"destination":"Mallorca","airport":"München"}:
     directory (C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\C:\Users\stefan.huber\projects\e2e-dashboard-client\examples\codeceptjs\__out) doesn't exist

  Scenario Steps:

  - I.saveScreenshot("after-destination-airport.png") at Test.Data.Scenario (bifrost-demo\search\search-holiday_test.js:27:7)
  - I.wait(1) at Test.Data.Scenario (bifrost-demo\search\search-holiday_test.js:25:7)
  - I.fillField("body #c24-travel-airport-element", "München") at Test.Data.Scenario (bifrost-demo\search\search-holiday_test.js:23:7)
  - I.pressKey("Tab") at Test.Data.Scenario (bifrost-demo\search\search-holiday_test.js:22:7)
  - I.wait(1) at Test.Data.Scenario (bifrost-demo\search\search-holiday_test.js:21:7)
  - I.fillField("body #c24-travel-destination-element", "Mallorca") at Test.Data.Scenario (bifrost-demo\search\search-holiday_test.js:17:7)
  - I.amOnPage("https://urlaub.check24.de/produkte") at Test.Data.Scenario (bifrost-demo\search\search-holiday_test.js:14:7)
```

### Details

* CodeceptJS version: 2.0.2
* NodeJS Version: 8.11.3
* Operating System: Windows
* WebDriver
* Configuration file:

```js
exports.config = {
...
    "output": '__out',
...
}

```

**Comment by hubidu** [comment]
Try this https://github.com/hubidu/codeceptjs-1422

Run this test:

codeceptjs run bifrost-demo/search/search-holiday_test.js

This should reproduce the above error

**Comment by rmlira** [comment]
When using WebDriver the script saveScreenshot.js (WebDriver) already concatenate the filepath with process.cwd()

```
const absoluteFilePath = filepath.startsWith('/') || fileath.startsWith('\\') ? filepath : _path.default.join(process.cwd(), filepath);
```

The lib WebDriver.js in function saveScreenshot calls the utils.js screenshotOutputFolder which already do it before too. In this case on Windows, the process.cwd() will return 'C:\...' which is not filtered in WebDriver method.

```
  async saveScreenshot(fileName, fullPage = false) {
    const outputFile = screenshotOutputFolder(fileName);

    if (!fullPage) {
      this.debug(`Screenshot has been saved to ${outputFile}`);
      return this.browser.saveScreenshot(outputFile);
    }
```

In this case is needed to change the screenshotOutputFolder to return an relative path with output dir and not the process.cwd()...
