### ISSUE TITLE
stepByStepReport not generated on Windows10x64

### ISSUE THREAD

**Issue by nkrishna79** [Codeception/CodeceptJS#1451]
Trying to run some tests using codeceptjs run --config myconfig.json --plugins stepByStepReport --plugins allure

-- FAILURES:
ENOENT: no such file or directory, open 'C:\Users\krish.murthy\intellijworkspace\codeceptjs-wdio\output\record_Navigating_to_page_2_1547653895\0000.png'

  Scenario Steps:

  Error: ENOENT: no such file or directory, open 'C:\Users\krish.murthy\intellijworkspace\codeceptjs-wdio\output\record_Navigating_to_page_2_1547653895\0000.png'
      at Object.fs.openSync (fs.js:660:18)
      at Object.fs.readFileSync (fs.js:565:33)
      at persistStep (node_modules\codeceptjs\lib\plugin\stepByStepReport.js:155:53)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:182:7)

  FAIL  | 0 passed, 1 failed   // 23s
    Emitted | global.result ([object Object])
(*) Step-by-step preview: file://C:\Users\krish.murthy\intellijworkspace\codeceptjs-wdio\output/records.html

### Details

* CodeceptJS version: 2.0.2
* NodeJS Version: 9.11.1
* Operating System: Windows 10 x64
* WebDriverIO
* Configuration file:

```js
{
  "name": "codeceptjs-wdio",
  "version": "1.0.0",
  "description": "codeceptjs webdriverio framework",
  "main": "steps_file.js",
  "scripts": {
    "feature-test-local": "codeceptjs run --config ./codecept-win10chrome-local.json --grep \"@reg86_1\" --plugins stepByStepReport --plugins allure --verbose",
  },
  "dependencies": {
    "codeceptjs": "^2.0.2",
    "gherkin": "^6.0.15",
    "mochawesome": "^3.1.1",
     "webdriverio": "^4.14.1"
  },
  "repository": {
    "type": "git",
    "url": "codeceptjs-wdio.git"
  },
  "author": "",
  "license": "ISC"
}

```

**Comment by tsuemura** [comment]
@nkrishna79 I'm not owner of this repository so I'm not granted to close any tickets... but maybe you can, because it is your ticket. Please do it by yourself!
