### ISSUE TITLE
assert not defined

### ISSUE THREAD

**Issue by aldarund** [Codeception/CodeceptJS#148]
Im trying to do same thing as described here:
http://codecept.io/helpers/WebDriverIO/#grabcookie

```
Scenario('Test Create Application', function*(I, applicationEditPage) {
    ...
    var form_descr = yield I.grabValueFrom('.form-reports #name');
    assert(form_descr, 'test form');
```
And im getting this error:
```

  ReferenceError: assert is not defined
      at Test.<anonymous> (C:\Users\ShapeR\PycharmProjects\ratest\dashboard_test.js:45:5)
      at next (native)
      at C:\Users\ShapeR\PycharmProjects\ratest\node_modules\codeceptjs\lib\scenario.js:40:32
```

**Comment by aldarund** [comment]
nvm found it

**Comment by nayaramoura** [comment]
Hi, @aldarund !

Could you please share what was the solution?

Cheers

**Comment by aldarund** [comment]
@nayaramoura 
let assert = require('assert');
