### ISSUE TITLE
Webdriver (wdio 5) - Update the seeElement method

### ISSUE THREAD

**Issue by PeterNgTr** [Codeception/CodeceptJS#1518]
#### What are you trying to achieve?
Using the `I.seeElement` with Safari 12
#### What do you get instead?
Got the following error

> Provide console output if related. Use `--verbose` mode for more details.

```
The command 'GET /session/f02975f75743107ec61f41bb498de5f53bff9605/element/node-57BEB84A-0250-4B87-A857-7B82438559C9/displayed' was not found.

  Scenario Steps:

  - I.seeElement("[data-qa="addressInput"]") at Object.addressInput (test/codeceptjs/components/searchAddress.js:9:11)
  - I.clearField("[data-qa="addressInput"]") at Object.addressInput (test/codeceptjs/components/searchAddress.js:8:11)

  unknown command: The command 'GET /session/f02975f75743107ec61f41bb498de5f53bff9605/element/node-57BEB84A-0250-4B87-A857-7B82438559C9/displayed' was not found.
      at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:342:10)
      at Request._callback (node_modules/webdriver/build/request.js:113:64)
      at Request.self.callback (node_modules/webdriver/node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:441:20)
      at Request.<anonymous> (node_modules/webdriver/node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:441:20)
      at IncomingMessage.<anonymous> (node_modules/webdriver/node_modules/request/request.js:1083:12)


  FAIL  | 0 passed, 1 failed   // 14s
Disconnected
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

### Details

* CodeceptJS version: v2.0.4
* NodeJS Version: 8+
* Operating System: MacOS Mojave
* WebDriver

### Resolutions
Update the method once this is finalised.
https://github.com/webdriverio/webdriverio/issues/2962

**Comment by LukoyanovE** [comment]
Tried fix bug, by changing WDIO call, but bug not here:
There are WDIO error, due to not implemented driver's API:
https://github.com/webdriverio/webdriverio/pull/3601

**Comment by PeterNgTr** [comment]
thanks @LukoyanovE for looking at it. Yeah, the issue is also from wdio itself. Should wait for the fix from their end.
