### ISSUE TITLE
Skipping data driven tests does not work

### ISSUE THREAD

**Issue by AdamOakman** [Codeception/CodeceptJS#1530]
#### What are you trying to achieve?

I skip datadriven test.

#### What do you get instead?

```bash
Data(...).xScenario is not a function

TypeError:
    at Object.<anonymous> (/tests/tests/demo.test.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /codecept/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)

Data(...).Scenario.only is not a function

TypeError:
    at Object.<anonymous> (/tests/tests/demo.test.js:16:24)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /codecept/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
```

> Provide test source code if related

```js
Data(clients).xScenario('test one', (I, current) => {
	I.addNewClient(current.client);
});

Data(clients).Scenario.only('test two', (I, current) => {
	I.addNewClient(current.client);
});
```

### Details

* CodeceptJS version: 2.0.4
* NodeJS Version: docker
* Operating System: docker
* Protractor
* Configuration file: not relevant

**Comment by LukoyanovE** [comment]
Why do you use `xScenario`, when there are `xData` ?

**Comment by AdamOakman** [comment]
Damn I didn't know, I did not see this in documentation. Maybe it is worth to add information to https://codecept.io/basics#skipping

Thank you, closing this issue.

**Comment by LukoyanovE** [comment]
Hmm, there are not info about `xData` too...
https://codecept.io/advanced/#data-drivern-tests

update is ned
