### ISSUE TITLE
Apppium.removeApp() fails in CodeceptJS 2.0.x

### ISSUE THREAD

**Issue by mirao** [Codeception/CodeceptJS#1535]
#### What are you trying to achieve?
I want to uninstall an Android app. It worked well in CodeceptJS 1.4.x with WebDriverIO 4.x, this way:
`I.removeApp("myapp.android.beta")`
#### What do you get instead?
It fails in CodeceptJS 2.0.x with WebDriver 5.
I tried `I.removeApp("myapp.android.beta")` and `I.removeApp("", "myapp.android.beta")` (according to https://codecept.io/helpers/Appium#removeapp), but nothing works.
> Provide console output if related. Use `--verbose` mode for more details.

```bash
    I remove app "", "myapp.android.beta"
2019-03-02T12:52:24.091Z ERROR webdriver: Request failed due to invalid argument: Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]],"optional":["options","sessionId","id"]} and you sent ["appId","bundleId"]
    at getErrorFromResponseBody (/home/mira/workspace/codeceptjs/node_modules/webdriver/build/utils.js:343:10)
    at Request._callback (/home/mira/workspace/codeceptjs/node_modules/webdriver/build/request.js:116:64)
    at Request.self.callback (/home/mira/workspace/codeceptjs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/home/mira/workspace/codeceptjs/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/home/mira/workspace/codeceptjs/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    [1] Error | invalid argument: Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]],"optional":["options","sessionId","id"]} and you …
    Emitted | step.failed (I remove app "", "myapp.android.beta")
    Emitted | step.finish (I remove app "", "myapp.android.beta")
    [1] Error | invalid argument: Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]],"optional":["options","sessionId","id"]} and you …
    Emitted | step.failed (I see app is not installed "myapp.android.beta")
    Emitted | step.finish (I see app is not installed "myapp.android.beta")
    [1] Error | invalid argument: Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]],"optional":["options","sessionId","id"]} and you …
    [1] Starting <teardown> session
```

> Provide test source code if related

```js
    I.removeApp("", commonPage.appName);
```
Finally I solved it by my own helper method, where I call Appium endpoint directly, passing `{"bundleId": appName}`
```js
    async removeApp(appName) {
        const browser = this.helpers["Appium"].browser;
        const {protocol, port, hostname, path} = browser.options;
        // Build path to Appium REST API endpoint
        const apiUrl = `${protocol}://${hostname}:${port}${path}`;
        
        const rest = this.helpers["REST"];
        // Remove app
        const result = await rest.sendPostRequest(`${apiUrl}/session/${browser.sessionId}/appium/device/remove_app`, {"bundleId": appName});
        const assert = require("assert");
        assert.strictEqual(result.status, 200);
        assert.deepStrictEqual(result.data, { "value": true }, "Removing of app failed");
    }
```
### Details

* CodeceptJS version: 2.0.6
* NodeJS Version: 10.15.1
* Operating System: Ubuntu 18.10
* WebDriverIO 5.6.4
* Appium server 1.11.1

**Comment by mirao** [comment]
It seems to be fixed in CodeceptJS 2.1.0 where the call of native method `I.removeApp(appName)` works well. The last version where it fails is 2.0.8
CC: @PeterNgTr
