### ISSUE TITLE
Tests silently pass when there is a broken import in the test code

### ISSUE THREAD

**Issue by poshaughnessy** [Codeception/CodeceptJS#1536]
#### What are you trying to achieve?

For the tests to fail if there is a broken import in the Codecept testing code.

#### What do you get instead?

The tests silently do not run. There is no output to say there is an error. Our build pipeline passes.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
$ codeceptjs run --debug
✨  Done in 4.46s.
```

> Provide test source code if related

This occurred when we had a broken import, which was incorrectly copied from our actual website source code, so it didn't resolve in the codecept project:

```js
-import { SOMETHING } from 'some/path/which/does/not/exist';
-
 Feature('Some feature to test');

Scenario('Some scenario', ...
```

### Details

* CodeceptJS version: 1.4.6
* NodeJS Version: v11.1.0
* Operating System: Mac OS 10.14.2. Also replicated in Docker on Linux.
* Protractor || WebDriverIO || Nightmare version (if related): Puppeteer 1.11.0
* Configuration file:

(Ommitting some additional parts of the file for brevity, here's the crux of it)

```js
const config = {
  name: process.env.E2E ? 'e2e-tests' : 'functional-tests',
  helpers: {
    Puppeteer: {
      fullPageScreenshots: true,
      url,
      restart: true,
      show,
      waitForNavigation: 'networkidle0',
      waitForTimeout: 5000,
      windowSize: screenRes.windowSize,
      chrome: {
        args: [
          '--no-sandbox',
          '--disable-setui-sandbox',
          '--ignore-certificate-errors',
          '--ignore-certificate-errors-spki-list',
          '--allow-insecure-localhost',
        ],
        ignoreHTTPSErrors: true,
      },
    },
  },
  output: './output',
  include: {},
  multiple: {},
  mocha: {},
  bootstrap: done => {
    // Waits until the url returns a 200 response before any tests are performed
    waitOn({
      resources: [queryBuilder(url)],
      strictSSL: false,
      timeout: 10000,
    })
      .then(() => {
        done();
      })
      // i.e. most likely a timeout has occurred
      // In this case a get request is performed for access to more diagnostic information
      .catch(() =>
        requestPromise({
          url: queryBuilder(url),
          strictSSL: false,
        })
      )
      .catch(err => {
        console.error(`Something is wrong with the application at ${url}`);
        console.error(`Response code ${err.response.statusCode}`);
        console.error(err.response.body);
        process.exit(1);
      });
  },
  hooks: process.env.E2E ? ['./utils/helpers/custom-hook.js'] : [],
  gherkin: {},
  plugins: {
    screenshotOnFail: {
      enabled: true,
    },
  },
  tests,
  timeout: 10000,
};
```

**Comment by PeterNgTr** [comment]
```
C02XR2AGJHD2:ucb-client-tests trung.nguyen$ ./node_modules/.bin/codeceptjs run --grep @test --verbose
2019-03-19T14:31:36.748Z DEBUG wdio-config: @wdio/sync not found, running tests asynchronous
[ 3, 42, 'foo' ]
Before tests clean up data Finished
(node:53995) UnhandledPromiseRejectionWarning: Error: Cannot find module 'some/path/which/does/not/exist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/trung.nguyen/Desktop/ucb-client-tests/tests/smokeCheck/linkedin.js:17:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/trung.nguyen/Desktop/ucb-client-tests/node_modules/node-hook/index.js:73:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
(node:53995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:53995) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
are you running against latest codeceptJs `2.0.7`?

**Comment by DevinWatson** [comment]
I'm seeing unhandled promise rejections in our steps file that are not causing tests to fail. Might be something similar. 

`(node:118) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: '393-494-951-070-6' == '039-349-494-818-0'
`

**Comment by zerkalica** [comment]
```js
Scenario('This test is lying', async () => {
  const one = await Promise.resolve(1);
  if (one !== 2) throw new Error('Test error');
});
```

Test always green. Any exceptions broken in async scenarios.

**Comment by Vorobeyko** [comment]
hi! Thank you for issue!
Your CodeceptJS version is oldest! 
And in last version this problem must to resolved.

But CodeceptJS is terrible works with import/export. Example, on my project I must to setting babel config for this.

**Comment by zerkalica** [comment]
> Your CodeceptJS version is oldest!

Same bug in latest stable 2.6.6 version.

**Comment by zerkalica** [comment]
I found a bug, problem with typescript + target: 'es5'

Uncomment `target: "es2017"` in https://github.com/zerkalica/codecept-ts-assert-bug/blob/master/tsconfig.codecept.json#L3

May be describe this moment in codecept documentation? I can't found anything about ts setup.

Related:

#1520 #2005
