### ISSUE TITLE
Not able to click any button/link in safari

### ISSUE THREAD

**Issue by stychu** [Codeception/CodeceptJS#1627]
I am unable to click any button or link running on safari browser.

```
@wdio/selenium-standalone-service": "5.7.8",
"codeceptjs": "2.1.0",
"webdriverio": "5.7.15"
```

```
-- FAILURES:
  Scenario Steps:
  
  - I.click("#hierarchyLink") at Test.Scenario (tests/raiseDeal.t2.test.js:17:5)
  - I.seeElement("#raise-deal-button:disabled") at Object.seeButtonDisabled (steps_file.js:19:12)
  - I.refreshPage() at Object.setHierarchy (steps/apiConnector.js:25:7)
  
  element not interactable: unknown error
      at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:348:10)
      at Request._callback (node_modules/webdriver/build/request.js:121:64)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:441:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:441:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)


  FAIL  | 1 passed, 1 failed   // 12s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
 › Stopped SeleniumStandaloneLauncher

```

**Comment by PeterNgTr** [comment]
seems like the error comes from webdriverio.

**Comment by PeterNgTr** [comment]
I tried with latest codeceptjs 2.1.2 on safari 12.1, it worked perfectly. May you use different codeceptjs version?
```
sysadmins-MacBook-Pro-3:codeceptjs-e2e-testing thanhnguyen$ ./node_modules/.bin/codeceptjs run --verbose
CodeceptJS v2.1.2
Using test root "/Users/thanhnguyen/Desktop/codeceptjs-e2e-testing"
Helpers: WebDriver, REST
Plugins: screenshotOnFail

Editor --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  Can be opened and the text input and bold formatting is working
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I am on page "/")
    Emitted | step.after (I am on page "/")
    Emitted | step.before (I click "WYSIWYG Editor")
    Emitted | step.after (I click "WYSIWYG Editor")
    Emitted | step.before (I execute script function () {
      document.querySelector("#mce_0_ifr").style.border = "thick solid #0000FF";
      setTimeout(function() {},1);
    })
    Emitted | step.after (I execute script function () {
      document.querySelector("#mce_0_ifr").style.border = "thick solid #0000FF";
      setTimeout(function() {},1);
    })
    Emitted | step.before (I switch to "#mce_0_ifr")
    Emitted | step.after (I switch to "#mce_0_ifr")
    Emitted | step.before (I fill field "#tinymce", "My text bold")
    Emitted | step.after (I fill field "#tinymce", "My text bold")
    Emitted | step.before (I double click "#tinymce")
    Emitted | step.after (I double click "#tinymce")
    Emitted | step.before (I switch to )
    Emitted | step.after (I switch to )
    Emitted | step.before (I click "#mceu_3")
    Emitted | step.after (I click "#mceu_3")
    Emitted | step.before (I switch to "#mce_0_ifr")
    Emitted | step.after (I switch to "#mce_0_ifr")
    Emitted | step.before (I click "#tinymce")
    Emitted | step.after (I click "#tinymce")
    Emitted | step.before (I switch to )
    Emitted | step.after (I switch to )
    Emitted | step.before (I save screenshot "editor_test.png")
    Emitted | step.after (I save screenshot "editor_test.png")
    Emitted | step.start (I am on page "/")
    Test: I 
      I am on page "/"
    Emitted | step.passed (I am on page "/")
    Emitted | step.finish (I am on page "/")
    Emitted | step.start (I click "WYSIWYG Editor")
      I click "WYSIWYG Editor"
    Emitted | step.passed (I click "WYSIWYG Editor")
    Emitted | step.finish (I click "WYSIWYG Editor")
    Emitted | step.start (I execute script function () {
      document.querySelector("#mce_0_ifr").style.border = "thick solid #0000FF";
      setTimeout(function() {},1);
    })
```

**Comment by stychu** [comment]
I've updated codeceptjs to 2.1.3 and I have Safari 12.1.1 and I am unable to click the link ;/ its very weird because on other browsers its working..

**Comment by stychu** [comment]
OKay found the problem. Seems like safari dont like react anchor tag and onClick on it. Changed it to div and its working
