### ISSUE TITLE
v2.1.5 breaks hooks

### ISSUE THREAD

**Issue by markjackson02** [Codeception/CodeceptJS#1745]
I tried to upgrade from 2.1.4 to 2.1.5 and Codecept it is failing now on the hook. I was able to replicate by starting with a fresh Codecept install and just adding the below config (8 lines total). v2.1.4 works as expected. 

#### What are you trying to achieve?
Use a custom hook

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
> npx codeceptjs run --steps

done is not a function

TypeError: 
    at callSync (/Users/markjackson/Documents/GitHub/issue-codecept-v2.1.5/node_modules/codeceptjs/lib/hooks.js:44:34)
    at module.exports (/Users/markjackson/Documents/GitHub/issue-codecept-v2.1.5/node_modules/codeceptjs/lib/hooks.js:15:7)
    at config.hooks.forEach.hook (/Users/markjackson/Documents/GitHub/issue-codecept-v2.1.5/node_modules/codeceptjs/lib/codecept.js:100:39)
    at Array.forEach (<anonymous>)
    at Codecept.runHooks (/Users/markjackson/Documents/GitHub/issue-codecept-v2.1.5/node_modules/codeceptjs/lib/codecept.js:100:23)
    at Codecept.init (/Users/markjackson/Documents/GitHub/issue-codecept-v2.1.5/node_modules/codeceptjs/lib/codecept.js:56:10)
    at Command.module.exports (/Users/markjackson/Documents/GitHub/issue-codecept-v2.1.5/node_modules/codeceptjs/lib/command/run.js:33:14)
    at Command.listener (/Users/markjackson/Documents/GitHub/issue-codecept-v2.1.5/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/Users/markjackson/Documents/GitHub/issue-codecept-v2.1.5/node_modules/commander/index.js:651:12)
```

### Details

* CodeceptJS version: 2.1.5
* NodeJS Version: 10.15.0
* Operating System: MacOS Mojave 10.14.3
* Configuration file:

```js
exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    Puppeteer: {
      url: 'http://localhost'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'test-new-codecept-version-2.1.5',
  hooks: ['./hooks/test.before.js'], // This is the only line added, rest is default config
}
```

* `./hooks/test.before.js`

```
require('codeceptjs');
const event = require('codeceptjs').event;

module.exports = async function () {
    event.dispatcher.on(event.test.before, () => {
        console.log('do something');
    });
};
```

**Comment by DavertMik** [comment]
Fixed in 2.2.0
