### ISSUE TITLE
Puppeteer/Firefox: I.setCookie does not seem to work

### ISSUE THREAD

**Issue by hubidu** [Codeception/CodeceptJS#1762]
#### What are you trying to achieve?

I want to set a cookie in my test:

```
I.setCookie({"domain":".check24-test.de","httpOnly":false,"name":"c24cb","path":"/","secure":false,"value":"1"}) at Object.loginWithSession (pages\customer-login.page.js:39:7)
```

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
1) Daten nachreichen
       Daten zu einem Fremdvertrag können flexibel nachgereicht werden @regression @story:VEVE-5471 | {"User":"teste2e-daten-nachreichen-04@check24.de","Versicherungsscheinnummer":"benötigt","Unterschrift":"vorhanden","Seiten":"policynumber,thankyou"}:
     Protocol error (Browser.deleteCookies): ERROR: failed to call method 'Browser.deleteCookies' with parameters {
  "browserContextId": null,
  "cookies": [
    {
      "url": "https://kundenbereich.check24-test.de/user/login.html",
      "domain": ".check24-test.de",
      "path": "/",
      "name": "c24cb"
    }
  ]
}
Expected "<root>.browserContextId" to be |string|; found |object| `null` instead. _dispatch@chrome://juggler/content/protocol/Dispatcher.js:100:15


  Scenario Steps:

  - I.setCookie({"domain":".check24-test.de","httpOnly":false,"name":"c24cb","path":"/","secure":false,"value":"1"}) at Object.loginWithSession (pages\customer-login.page.js:39:7)
```
### Details

* CodeceptJS version: 2.2.0
* NodeJS Version: 10.15.3
* Operating System: Windows
* Puppeteer
* Configuration file:

```js
Puppeteer: {
      url: 'http://localhost',
      browser: 'firefox',
      show: process.env.HEADLESS ? false : true,
      waitForAction: 0,
      waitForNavigation: 'domcontentloaded',
      waitForTimeout: getWaitForTimeout(),
      getPageTimeout: 30000,
      restart: true,
      fullPageScreenshots: true,
      windowSize: '1900x1048',
},
```

**Comment by DavertMik** [comment]
We didn't prepare test suite for Firefox and puppeteer. Probably when we
set it up we get even more issues 😁


пн, 8 лип. 2019, 16:42 користувач Stefan Huber <notifications@github.com>
пише:

**Comment by Vorobeyko** [comment]
Puppeteer-firefox has issue - https://github.com/GoogleChrome/puppeteer/issues/4470

**Comment by EgorBodnar** [comment]
The issue was fixed:  https://github.com/puppeteer/puppeteer/pull/4850

And then the experimental `puppeteer-firefox` package has been deprecated. No longer maintained.

@DavertMik close the issue pls
