### ISSUE TITLE
Node version 12 support

### ISSUE THREAD

**Issue by VikalpP** [Codeception/CodeceptJS#1763]
#### What are you trying to achieve?
Run tests on node v12.6.0

#### What do you get instead?
Extra text (`Runner: runTest`) from `stdout`.
It works fine in Node v10.16.0

> Provide console output if related. Use `--verbose` mode for more details.

```bash
  4) CodeceptJS session
       should run with 3 sessions:

      check steps execution order
      + expected - actual

       [
      -  "Runner: runTest "
         "I do \"writing\""
         "davert: I do \"reading\""
      -  "Runner: runTest "
         "I do \"playing\""
         "john: I do \"crying\""
         "davert: I do \"smiling\""
      -  "Runner: runTest "
         "I do \"laughing\""
         "mike: I do \"spying\""
         "john: I do \"lying\""
      -  "Runner: runTest "
         "I do \"waving\""
       ]
      
      at test/runner/session_test.js:24:19                                                                                                                                                      
      at ChildProcess.exithandler (child_process.js:288:7)                                                                                                                                      
      at maybeClose (internal/child_process.js:1021:16)                                                                                                                                         
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)                                                                                                                  

```

> Provide test source code if related
[`session_test.js:16`](https://github.com/Codeception/CodeceptJS/blob/38e04f564cbb3e954dc591636c9d2f26a3f8c920/test/runner/session_test.js#L16)

```js

  it('should run with 3 sessions', (done) => {
    exec(`${codecept_run} --steps --grep "@1"`, (err, stdout, stderr) => {
      const lines = stdout.match(/\S.+/g);

      const list = grepLines(lines, 'basic session @1');
      list.pop();
      testStatus = list.pop();
      testStatus.should.include('OK');
      list.should.eql([
        'I do "writing"',
        'davert: I do "reading"',
        'I do "playing"',
        'john: I do "crying"',
        'davert: I do "smiling"',
        'I do "laughing"',
        'mike: I do "spying"',
        'john: I do "lying"',
        'I do "waving"',
      ], 'check steps execution order');
      done();
    });
  });
```

### Details

* CodeceptJS version: 2.2.0
* NodeJS Version: 12.6.0
* Operating System: Linux

**Comment by VikalpP** [comment]
While debugging I found this response in `stdout`.


![found runner_ runTest](https://user-images.githubusercontent.com/11846339/60841531-a80a1700-a1ef-11e9-8c84-d1218e8fd57b.png)
