### ISSUE TITLE
Couldn't initialise "@wdio/selenium-standalone-service".

### ISSUE THREAD

**Issue by vitaly87** [Codeception/CodeceptJS#1770]
#### What are you trying to achieve?
Hi, I am trying to run selenium-standalone-servic
#### What do you get instead?

> 
> Could not load plugin wdio from module './plugin/wdio':
> Couldn't initialise "@wdio/selenium-standalone-service".
> Error: Cannot find module '@wdio/logger'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
>     at Module.require (internal/modules/cjs/loader.js:636:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
> 

    "@wdio/selenium-standalone-service": "^5.11.0"
"codeceptjs": "^2.1.4",

**Comment by vitaly87** [comment]
Working with npx codeceptjs run
