### ISSUE TITLE
UnhandledPromiseRejectionWarning with mockRequest

### ISSUE THREAD

**Issue by loadbrain** [Codeception/CodeceptJS#1818]
#### What are you trying to achieve?
I call I.mockRequest("GET", "/google-analytics/*path", 200);
#### What do you get instead?
 DeprecationWarning: Unhandled promise rejections
> Provide console output if related. Use `--verbose` mode for more details.

```bash
(node:656) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\puppeteer\lib\ExecutionContext.js:167:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async ExecutionContext._evaluateInternal (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\puppeteer\lib\ExecutionContext.js:120:56)
    at async ExecutionContext.evaluate (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\puppeteer\lib\Page.js:827:43)
    at Page.<anonymous> (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:112:23)
    at response (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\dist\cjs\pollyjs-adapter-puppeteer.js:2359:14)
    at new Promise (<anonymous>)
    at new F (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\dist\cjs\pollyjs-adapter-puppeteer.js:206:28)
    at PuppeteerAdapter.passthroughRequest (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\dist\cjs\pollyjs-adapter-puppeteer.js:2352:30)
    at PuppeteerAdapter.onPassthrough (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\node_modules\@pollyjs\adapter\dist\cjs\pollyjs-adapter.js:1344:33)
    at PuppeteerAdapter.passthrough (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\node_modules\@pollyjs\adapter\dist\cjs\pollyjs-adapter.js:1207:17)
    at PuppeteerAdapter.<anonymous> (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\node_modules\@pollyjs\adapter\dist\cjs\pollyjs-adapter.js:1188:19)
  -- ASYNC --
    at Page.<anonymous> (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:111:15)
    at response (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\dist\cjs\pollyjs-adapter-puppeteer.js:2359:14)
    at new Promise (<anonymous>)
    at new F (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\dist\cjs\pollyjs-adapter-puppeteer.js:206:28)
    at PuppeteerAdapter.passthroughRequest (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\dist\cjs\pollyjs-adapter-puppeteer.js:2352:30)
    at PuppeteerAdapter.onPassthrough (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\node_modules\@pollyjs\adapter\dist\cjs\pollyjs-adapter.js:1344:33)
    at PuppeteerAdapter.passthrough (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\node_modules\@pollyjs\adapter\dist\cjs\pollyjs-adapter.js:1207:17)
    at PuppeteerAdapter.<anonymous> (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\node_modules\@pollyjs\adapter\dist\cjs\pollyjs-adapter.js:1188:19)
    at PuppeteerAdapter.handleRequest (C:\Users\w7-wera\AppData\Roaming\npm\node_modules\@pollyjs\adapter-puppeteer\node_modules\@pollyjs\adapter\dist\cjs\pollyjs-adapter.js:1163:34)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

### Details

* CodeceptJS version: 2.2.1
* NodeJS Version: 12.7.0
* Operating System: Windows 10
* Polly || Puppeteer ```js

**Comment by DavertMik** [comment]
This is a usual error which we face in Puppeteer. A page is not loaded, so the error is thrown. In puppeteer we fix that by retrying the last action. But this is not enabled for Polly. 

Maybe something like this can help here?
https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/Puppeteer.js#L220
@VikalpP

**Comment by loadbrain** [comment]
Would be great!

**Comment by VikalpP** [comment]
Hey @loadbrain, It would be nice that you provide a full test case where this warning occurs.
I can't produce this warning.

**Comment by loadbrain** [comment]
Hi,
sorry, holiday... ;-)
Ok, seems to be a special case because of opening new windows.
In a normal test file, I can not reproduce the error.
