### ISSUE TITLE
mocha-multi reporter no longer works with mocha 6

### ISSUE THREAD

**Issue by xMutaGenx** [Codeception/CodeceptJS#1850]
#### What are you trying to achieve?

Generate reports after the test run.

#### What do you get instead?

```bash
TypeError: Cannot read property 'passes' of undefined
    at Spec.Base.epilogue (***/node_modules/mocha/lib/reporters/base.js:324:30)
    at Object.onceWrapper (events.js:286:20)
    at EventEmitter.emit (events.js:203:15)
    at EventEmitter.emit (domain.js:448:20)
    at withReplacedStdout (***/node_modules/mocha-multi/mocha-multi.js:197:14)
    at withReplacedStdout (***/node_modules/mocha-multi/mocha-multi.js:159:12)
    at Runner.runner.on.eventArgs (***/node_modules/mocha-multi/mocha-multi.js:196:7)
    at Runner.emit (events.js:203:15)
    at Runner.EventEmitter.emit (domain.js:448:20)
    at ***/node_modules/mocha/lib/runner.js:903:12
    at ***/node_modules/mocha/lib/runner.js:772:9
    at next (***/node_modules/mocha/lib/runner.js:362:14)
    at Immediate.<anonymous> (***/node_modules/mocha/lib/runner.js:425:5)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
Uncaught undefined exception
```

### Details

* CodeceptJS version: 2.3.0
* NodeJS Version: 10.16.2
* Operating System: OSX
* WebDriverIO: 5.12.1
* Configuration file:

```js
reporterOptions: {
        'codeceptjs-cli-reporter': {
            stdout: '-',
            options: {
                steps: true
            }
        },
        mochawesome: {
            stdout: './output/mochawesome.log',
            options: {
                reportDir: './output',
                html: false
            }
        }
    }
```

**Comment by elukoyanov** [comment]
Does mochawesome package update to ^4 version works?

**Comment by Avyiel** [comment]
Having the same issue, except I'm using the JUnit reporter:

```
TypeError: Cannot set property stats of #<EventEmitter> which has only a getter

Error:
    at Codecept.run (***/node_modules/codeceptjs/lib/codecept.js:174:13)
    at codecept.runBootstrap (***/node_modules/codeceptjs/lib/command/run.js:39:16)
    at module.exports (***/node_modules/codeceptjs/lib/hooks.js:27:13)
    at Codecept.runBootstrap (***/node_modules/codeceptjs/lib/codecept.js:110:5)
    at Command.module.exports (***/node_modules/codeceptjs/lib/command/run.js:35:14)
    at Command.listener (***/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (***/node_modules/commander/index.js:651:12)
    at Command.parse (***/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (***/node_modules/codeceptjs/bin/codecept.js:182:9)
```

**Details**
- CodeceptJS version: 2.3.0
- NodeJS Version: 10.15.3
- Operating System: OSX
- WebDriverIO: n/a
- Configuration file:

```javascript
mocha: {
    reporterOptions: {
      'mocha-junit-reporter': {
        stdout: './reports/console.log',
        options: {
          mochaFile: './reports/result.xml',
          testsuitesTitle: 'CodeceptJS Tests',
        },
      },
      'codeceptjs-cli-reporter': {
        stdout: '-',
        options: {
          steps: true,
        },
      },
    },
  },
```

Repo to reproduce: https://github.com/Avyiel/repro-codeceptjs-mocha6

**Comment by xMutaGenx** [comment]
@elukoyanov I was `mochawesome` v4.1.0, it seems that the latest release of `mocha-multi` v1.1.1 fixes this for me.
