### ISSUE TITLE
unable to enter iframe via switchTo(iframeID or iframeName) in edge and mobile chrome browser

### ISSUE THREAD

**Issue by chwolf** [Codeception/CodeceptJS#1851]
#### What are you trying to achieve?
enter iframe using I.switchTo(#iframe) with Microsoft Edge browser or Chrome on Android
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# error when executed in Edge browser 
# also frame was found by I.waitForElement() in previous step:
  
The specified frame was not found in the current frame or window.
no such frame: The specified frame was not found in the current frame or window.
    at getErrorFromResponseBody (/Users/wolf/WebstormProjects/newCodeceptJS/node_modules/webdriver/build/utils.js:215:10)
    at Request._callback (/Users/wolf/WebstormProjects/newCodeceptJS/node_modules/webdriver/build/request.js:103:64)
    at Request.self.callback (/Users/wolf/WebstormProjects/newCodeceptJS/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/Users/wolf/WebstormProjects/newCodeceptJS/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/Users/wolf/WebstormProjects/newCodeceptJS/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)

  Scenario Steps:
  - I.switchTo({"frame":"#ds24_heidelpay_cc_iframe"}) at Test.Scenario (ClassicOrderform_test.js:247:7)
  - I.waitForElement({"frame":"#ds24_heidelpay_cc_iframe"}) at Test.Scenario (ClassicOrderform_test.js:246:7)

# -------------
# error when executed in Mobile Chrome on Android phone
# also frame was found by I.waitForElement() in previous step:

Error: invalid argument: missing 'ELEMENT'
    (Session info: chrome=74.0.3729.136)
    (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 3.19.8-100.fc20.x86_64 x86_64)
      at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:215:10)
      at Request._callback (node_modules/webdriver/build/request.js:103:64)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:448:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:448:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)

 Scenario Steps:
  - I.switchTo({"frame":"#ds24_heidelpay_cc_iframe"}) at Test.Scenario (ClassicOrderform_test.js:247:7)
  - I.waitForElement({"frame":"#ds24_heidelpay_cc_iframe"}) at Test.Scenario (ClassicOrderform_test.js:246:7)

```

> identified workaround for both browsers

```js
// Step to fail:
I.switchTo('#iframeID');

// workaround for Edge and Chrome on Android browser via helper class:
 await this.helpers["WebDriver"].browser.switchToFrame('iframeID'); //without #
```

### Details

* CodeceptJS version: 2.3.0 and before
* WebDriverIO: 5.10.9
*[Appium] Creating new AndroidDriver (v1.24.1)

**Comment by juliofarah** [comment]
@chwolf do you mind sharing the test, helper file and `codecept.json` (or equivalent)?
I'm facing issues testing content within an iframe with CodeceptJS + Puppeteer and would love if I could find a workaround for my issue

Thanks!

**Comment by chwolf** [comment]
Hi @juliofarah,

actually we do not run our tests in either of the problematic browsers and therefor i do not have any code snippet available at the moment. 
Can you provide me with a concrete issue that you're facing so that i know what you need? Do you run your tests on mobile chrome or just desktop chrome? 
What error appears and maybe you can also tshare he webpage with iframe you try to automate?

Cheers!

**Comment by juliofarah** [comment]
thanks for your reply @chwolf !

I'm trying to run my tests in desktop chrome.
You can find the iframe at https://app.segment.com - you'd have to create an account and navigate to Visual Tagger - the product I'm trying to write integration tests for.

It's an unusual combination, where I have a chrome extension and an iframe to test - so I'm using Puppeteer + CodeceptJS.

I don't have any specific output, just a message that the element's I'm looking for cannot be found.

Here's how my config looks like:
```

{
  "tests": "./tests/*.test.ts",
  "output": "./output",
  "helpers": {
    "Puppeteer": {
      "url": "http://localhost:8000",
      "show": true,
      "windowSize": "1280x960",
      "waitForNavigation": "networkidle0",
      "waitForAction": 1000,
      "chrome": {
        "args": [
          "--disable-extensions-except=./dist/",
          "--load-extension=./dist/",
          "--force-dev-mode-highlighting",
          "--embedded-extension-options"
        ]
      }
    }
  },
  "include": {
    "I": "./steps_file.ts"
  },
  "bootstrap": null,
  "mocha": {},
  "name": "app",
  "plugins": {
    "retryFailedStep": {
      "enabled": true
    },
    "screenshotOnFail": {
      "enabled": true
    }
  }
}
```

My test:

```
Scenario('Tag Creation', async I => {
  I.fulfillVTPrerequisites(process.env.AUTH_TOKEN)
  I.click('Create Events')
  I.click('Add Event')

  I.click(locate('span').withText('Any Element Click'))
  I.seeElement(IFRAME_ID)

  within({ frame: '#segment-vt-iframe' }, function() {
    I.see('Do you even see me?') // text found inside the iframe
  })
})
```
