### ISSUE TITLE
mocha-multi + mocha-junit-reporter no longer works with mocha 6

### ISSUE THREAD

**Issue by Avyiel** [Codeception/CodeceptJS#1854]
#### What are you trying to achieve?
I'm trying to use `mocha-multi` with `mocha-junit-reporter` and the CLI reporter. Expecting an XML file in `./output/` and the usual CLI reporting.

#### What do you get instead?

```bash
TypeError: Cannot set property stats of #<EventEmitter> which has only a getter

Error:
    at Codecept.run (***/node_modules/codeceptjs/lib/codecept.js:174:13)
    at codecept.runBootstrap (***/node_modules/codeceptjs/lib/command/run.js:39:16)
    at module.exports (***/node_modules/codeceptjs/lib/hooks.js:27:13)
    at Codecept.runBootstrap (***/node_modules/codeceptjs/lib/codecept.js:110:5)
    at Command.module.exports (***/node_modules/codeceptjs/lib/command/run.js:35:14)
    at Command.listener (***/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (***/node_modules/commander/index.js:651:12)
    at Command.parse (***/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (***/node_modules/codeceptjs/bin/codecept.js:182:9)
```

### Details

- CodeceptJS version: 2.3.0
- NodeJS Version: 10.15.3
- Operating System: macOS 10.14.6
- Configuration file:

```js
mocha: {
    reporterOptions: {
      'mocha-junit-reporter': {
        stdout: './reports/console.log',
        options: {
          mochaFile: './reports/result.xml',
          testsuitesTitle: 'CodeceptJS Tests',
        },
      },
      'codeceptjs-cli-reporter': {
        stdout: '-',
        options: {
          steps: true,
        },
      },
    },
  },
```

Repo to reproduce: https://github.com/Avyiel/repro-codeceptjs-mocha6
1. `yarn install`
2. `yarn codeceptjs run --reporter mocha-multi`

**Comment by Avyiel** [comment]
It appears that this issue is not cause by CodeceptJS, but instead by `mocha-multi`.

 Please refer to glenjamin/mocha-multi#62 for further discussion.
