### ISSUE TITLE
Use of autoLogin Plugin and run-workers leads to DOMException [DataCloneError]

### ISSUE THREAD

**Issue by nitschSB** [Codeception/CodeceptJS#1885]
Sorry, I currently don't have the time to write all details. It looks like a bug. Please have a look at the error message.

```
CodeceptJS v2.3.1
Running tests in 2 workers...

internal/worker.js:144
    this[kPort].postMessage({
                ^

DOMException [DataCloneError]: I => fetchFunc(I) could not be cloned.
    at new Worker (internal/worker.js:144:17)
    at /workdir/node_modules/codeceptjs/lib/command/run-workers.js:71:14
    at Array.map (<anonymous>)
    at createWorkers (/workdir/node_modules/codeceptjs/lib/command/run-workers.js:69:28)
    at /workdir/node_modules/codeceptjs/lib/command/run-workers.js:63:24
    at module.exports (/workdir/node_modules/codeceptjs/lib/hooks.js:27:13)
    at Command.module.exports (/workdir/node_modules/codeceptjs/lib/command/run-workers.js:62:3)
    at Command.listener (/workdir/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:209:13)
    at Command.parseArgs (/workdir/node_modules/commander/index.js:651:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by DavertMik** [comment]
Similar to #1879

**Comment by nitschSB** [comment]
As soon as you define a function inside the `codecept.conf.js` the error will occurre.

Minimal example:
```js
exports.config = {
  output: './output',
  helpers: {
    Puppeteer: {
      url: 'http://localhost',
      browser: 'chrome',
      useless: () => {},
    },
  },
  tests: './*_test.js',
  timeout: 10000,
  name: 'tests',
};
```
