### ISSUE TITLE
Webdriverio error messages are not parsed correctly

### ISSUE THREAD

**Issue by xMutaGenx** [Codeception/CodeceptJS#1906]
#### What are you trying to achieve?

See correctly parsed error messages

#### What do you get instead?

```bash
element ([object Object]) is not in DOM or there is no element([object Object]) with text "text" after 10 sec
element ([object Object]) still not present on page after 10 sec

```

> Provide test source code if related

```js
I.waitForText("text", 10, {css:".selector"});
I.waitElement({css:".selector"});
```

### Details

* CodeceptJS version: 2.3.1
* NodeJS Version: 10
* Operating System: OSX
* WebDriverIO: 5.13.1

**Comment by PeterNgTr** [comment]
I think it's from wdio.
```
Scenario Steps:
  
  - I.waitForText("text", 10, {"css":".selector"}) at Test.<anonymous> (test/login_test.js:8:7)
  
  Error: element ([object Object]) is not in DOM or there is no element([object Object]) with text "text" after 10 sec
      at /Users/thanhnguyen/Desktop/test/node_modules/webdriverio/build/commands/browser/waitUntil.js:30:15
```

**Comment by PeterNgTr** [comment]
the provided locator is not parsed when printing on the console log. Such an easy fix. I could take a look at it.

**Comment by xMutaGenx** [comment]
@PeterNgTr Yeah it will be in the `codeceptjs/lib/helper/WebDriver.js` would do it myself, but currently don't have the time to contribute, so thought about at least reporting it. Would be ace if you could pick it up, there are a few others that will get caught by this as well.

**Comment by PeterNgTr** [comment]
no worries, I thought it is not in urgent. You could push a fix when you could.

**Comment by DavertMik** [comment]
Is this stil valid?

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
