### ISSUE TITLE
Integrating with Browserstack

### ISSUE THREAD

**Issue by therealtimhawkins** [Codeception/CodeceptJS#1970]
Hi, I'm having an issue setting up CodeceptJS with Browserstack.

My codecept.conf.js looks like:

```exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    WebDriver: {
      url: '<baseurl>',
      host: 'hub-cloud.browserstack.com',
      port: 80,
      user: '<myusername>',
      key: '<mykey>',
      browser: 'chrome'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'codecept'
}
```

This seems to be communicating with Browserstack correctly as when I run without a username or password I get the error:

`Can't connect to WebDriver.
Error: Authorization required`

However, when I add valid details I get the error:

```
Can't connect to WebDriver.
Error: write EPROTO 4571440576:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:


Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
  rror: write EPROTO 4571440576:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
  
      at _errnoException (util.js:992:11)
      at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```

I am not behing a proxy so I'm unsure what the issue could be. Do you have any ideas? Thanks in advance for your time.

**Comment by therealtimhawkins** [comment]
Will do, sorry about that.
