### ISSUE TITLE
install codeceptjs versi 2.3.3 get respond error "cannot find module './utils"

### ISSUE THREAD

**Issue by Kurniawan22** [Codeception/CodeceptJS#1976]
I am install codeceptjs new version and follow step by step install "https://codecept.io/quickstart"
but get respond error " cannot find module './utils'".

step by step :

- npm init -y
- yarn add codeceptjs puppeteer --save-dev
- npx npx codeceptjs init
   geeting respond = cannot find module './utils'

maybe codeceptjs versi 2,3,3 is corrupt?

**Comment by sky172839465** [comment]
I have the same problem, you can install `parse-function@5.2.11` for a workaround.

**Comment by hfrijlink** [comment]
Thanks @sky172839465 , that worked for me!

**Comment by pablopaul** [comment]
@sky172839465 how did you figured out that this is the dependency which requires the not available module?

**Comment by sky172839465** [comment]
@pablopaul my functional test's error log told me which line throw error

```diff
Error: Cannot find module './utils'
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
     at Module.require (internal/modules/cjs/loader.js:636:17)
     at require (internal/modules/cjs/helpers.js:20:18)
-    at Object.<anonymous> (/xxx/node_modules/parse-function/dist/cjs/index.js:1:731)
     at Module._compile (internal/modules/cjs/loader.js:688:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
     at Module.load (internal/modules/cjs/loader.js:598:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

I have been [report an issue][] to parse-function's repo, hope this issue can be fixed ASAP.

[report an issue]: https://github.com/tunnckoCore/parse-function/issues/202

**Comment by Kurniawan22** [comment]
hi @sky172839465 thanks for you solutions.

**Comment by tunnckoCore** [comment]
Install latest `parse-function` version :)

I'm in times of migration to monorepo for all my stuff and there can be bugs, so frequent updates may be needed for some time. Sorry for the problems :)
