### ISSUE TITLE
I.click() not working for floated element within fixed element

### ISSUE THREAD

**Issue by StaveleyHead** [Codeception/CodeceptJS#2029]
#### What are you trying to achieve?

I want to check that clicking an element opens a modal window.

#### What do you get instead?

I get an error: 'Node is either not visible or not an HTMLElement'. This is regardless of how I locate the element. I've tried XPath, CSS and the text in the link. I have a `seeElement()` check just beforehand that is able to find the element.

After a bit of fiddling I've managed to isolate the cause of the problem, but I'm not sure what I can do to fix it in my test. It's not finding the element because it's a `float` within a `position: fixed` element. I'm not sure if this is a bug in CodeceptJS or Puppeteer.

I've spent a few hours reducing the HTML and CSS to the bare minimum to make the problem reproducable without a lot of irrelevant stuff.

The following HTML and test should reproduce the bug as I am seeing it.

```HTML
<!DOCTYPE html>
<html>
<head>
<style>
#footer {
  position:fixed;
}
#footer ul {
  width:960px;
}
#footer #feedbutton {
  float:right;
}
</style>
</head>
<body>
<div id="footer">
    <ul id="info">
        <li id="id1"><a href="#">Normal link 1</a></li>
        <li id="id2"><a href="#">Normal link 2</a></li>
        <li id="feedbutton"><a href="#">Floated link</a></li>
    </ul>
</div>
</body>
</html>
```

```js
Feature('Bug reproducer');

Scenario('Show the bug', (I) => {
    I.amOnPage("/bugpage.php");
    I.see("Normal link 1");
    I.see("Normal link 2");
    I.see("Floated link");
    I.seeElement({css: '#feedbutton'});
    I.seeElement("//*[@id='feedbutton']");
    I.click("Normal link 1");
    I.click("Normal link 2");
    // All of the following fail when they shouldn't
    I.click("Floated link");
    I.click({css: '#feedbutton'});
    I.click("//*[@id='feedbutton']");
});
```
Removing any one of the three CSS rules in the page results in the traget element being seen as expected, but the three combined seem to render it invisible to CodeceptJS/Puppeteer.

My failure output:

```bash
-- FAILURES:

  1) Bug reproducer
       Show the bug:
     Node is either not visible or not an HTMLElement

  Scenario Steps:

  - I.click("Floated link") at Test.<anonymous> (tests/end2end/bugtest/bug_reproducer_test.js:14:7)
  - I.click("Normal link 2") at Test.<anonymous> (tests/end2end/bugtest/bug_reproducer_test.js:12:7)
  - I.click("Normal link 1") at Test.<anonymous> (tests/end2end/bugtest/bug_reproducer_test.js:11:7)
  - I.seeElement("//*[@id='feedbutton']") at Test.<anonymous> (tests/end2end/bugtest/bug_reproducer_test.js:10:7)
  - I.seeElement({"css":"#feedbutton"}) at Test.<anonymous> (tests/end2end/bugtest/bug_reproducer_test.js:9:7)
  - I.see("Floated link") at Test.<anonymous> (tests/end2end/bugtest/bug_reproducer_test.js:8:7)
  - I.see("Normal link 2") at Test.<anonymous> (tests/end2end/bugtest/bug_reproducer_test.js:7:7)
  - I.see("Normal link 1") at Test.<anonymous> (tests/end2end/bugtest/bug_reproducer_test.js:6:7)
  - I.amOnPage("/bugpage.php") at Test.<anonymous> (tests/end2end/bugtest/bug_reproducer_test.js:5:7)



  Run with --verbose flag to see NodeJS stacktrace
```

### Details

* CodeceptJS version: 2.3.5
* NodeJS Version: 12.13.0
* Operating System: Ubuntu 16.04.6 LTS
* Protractor || WebDriverIO || Nightmare version (if related): Puppeteer
* Configuration file:

```js
# paste suite config here
```

**Comment by PeterNgTr** [comment]
I tried your HTML. Seems working fine.

```js
    I am on page "file:///Users/thanhnguyen/Desktop/test.html"
    I see "Normal link 1"
    I see "Normal link 2"
    I see "Floated link"
    I see element {"css":"#feedbutton"}
    I see element "//*[@id='feedbutton']"
    I click "Normal link 1"
    I click "Normal link 2"
    I click "Floated link"
    I click {"css":"#feedbutton"}
    I click "//*[@id='feedbutton']"
  ✔ OK in 906ms


  OK  | 1 passed   // 3s
```

**Comment by StaveleyHead** [comment]
Hi Peter

Thanks for your reply.
That's odd. I suppose the only place there could be a difference between me and you is in the CodeceptJS config.
This is my config:

```js
const { exec } = require('child_process');
var server_pid;
var test_root = './tests/';

exports.config = {
  tests: test_root + 'end2end/*/*_test.js',
  output: test_root + '_output',
  helpers: {
    Puppeteer: {
      url: 'http://localhost:9050/',
    },
    FileSystem: {}
  },
  include: {
    I: test_root + 'end2end/steps_file.js'
  },
  bootstrap: function(done) {
      var setupPhpPromise = new Promise(function(resolve, reject) {
          // Start the test PHP server
          exec('php -S localhost:9050 -t ./ testrouterjs.php -c /usr/local/php/lib/php.ini > tests/_output/testserver.log 2>&1 & echo $!', (err, stdout, stderr) => {
              if(err) {
                  reject(err);
              }
              server_pid =  `${stdout}`;
              resolve("Finished test PHP server setup");
          });
      });

      Promise.all([setupPhpPromise]).then(function (results) {
          done();
      });
  },
  teardown: function(done) {
      var teardownPhpPromise = new Promise(function(resolve, reject) {
          exec('kill ' + server_pid, (err, stdout, stderr) => {
              if(err)
              {
                  reject(err);
              }
              resolve("Finished test server teardown");
          });
      });

      Promise.all([teardownPhpPromise]).then(function (results) {
          done();
      });
  },
  mocha: {},
  name: 'tests',
  plugins: {}
}
```

Our output is coming from a PHP framework (Phalcon), which is why I'm serving the files through the test PHP server. I don't think this should make a difference though as there's no PHP at all in the test HTML file.

Are there any big differences in the config you are using that might point me to where things are going wrong?

**Comment by PeterNgTr** [comment]
my config is as following:

```js
const selenium = require('selenium-standalone');
require('import-export');

exports.config = {
  tests: "./tests/**/*.js",
  timeout: 10000,
  output: "./output",
  helpers: {
    // WebDriver: {
    //   url: 'https://www.pizza.de',
    //   basicAuth: { username: 'postman', password: 'password' },
    //   browser: "chrome",
    //   desiredCapabilities: {
    //     chromeOptions: {
    //       args: ["--disable-gpu", "--window-size=800,600"]
    //     }
    //   },
    //   restart: true,
    //   windowSize: "1440x700",
    //   waitForNavigation: ["networkidle2", "domcontentloaded"],
    // },
    Puppeteer: {
      url: 'https://www.pizza.de',
      windowSize: "1440x700",
      show: true
    },
    FileSystem: {}
  },
  // bootstrap: (done) => {
  //   selenium.start((err, child) => {
  //     if (err) {
  //       throw err;
  //     }

  //     selenium.__child = child;
  //     done();
  //   });
  // },
  // teardown: (done) => {
  //   setTimeout(() => {
  //     try {
  //       if (selenium.__child) selenium.__child.kill();
  //     } catch (e) { }
  //   }, 3000);
  //   done();
  // },
  mocha: {
    reporterOptions: {
      reportDir: "output"
    }
  },
  name: "pizza-ui-tests",
  multiple: {
    parallel: {
      chunks: 2
    }
  },
  include: {
    homePage: './pages/HomePage.js',
    loginPage: './pages/LoginPage.js',
    data: './develop.data.js',
  },
  plugins: {
    allure: {
      outputDir: "report",
      enabled: true
    }
  }
}
```

I don't there are any much differences.

**Comment by StaveleyHead** [comment]
I've got it. It's the 'windowSize'. I wasn't setting one, and the fixed width of `960px` was obviously overflowing the default screen width so that the right-floated element was off-screen. I've set a width of 1024 and the test is passing as expected now.

Thanks for your help finding this.
