### ISSUE TITLE
I.waitForClickable throws res.waitForClickable is not a function

### ISSUE THREAD

**Issue by costasovo** [Codeception/CodeceptJS#2067]
#### What are you trying to achieve?
I updated CodeceptJS to version 2.3.6 and wanted to use the new `waitForClickable` within my custom steps file.

#### What do you get instead?
`res.waitForClickable is not a function`

```bash
res.waitForClickable is not a function

  Scenario Steps:

  - I.waitForClickable("[data-automation-id='admin-nav']", 10) at Object.waitAndClick (test/acceptance/custom_steps.js:76:12)
  - I.amOnPage("/account") at Test.<anonymous> (test/acceptance/tests/admin_customers_test.js:12:5)
  - I.waitInUrl("/account", 20) at login (test/acceptance/custom_steps.js:20:5)
  - I.click("[data-automation-id="login-form-button"]") at login (test/acceptance/custom_steps.js:19:5)
  - I.fillField("password", "password123") at login (test/acceptance/custom_steps.js:18:5)
  - I.fillField("email", "admin@mailpoet.com") at login (test/acceptance/custom_steps.js:17:5)
  - I.waitForElement("[data-automation-id="login-form-button"]") at login (test/acceptance/custom_steps.js:16:5)
  - I.amOnPage("/login") at login (test/acceptance/custom_steps.js:15:5)

  TypeError: res.waitForClickable is not a function
      at WebDriver.waitForClickable (node_modules/codeceptjs/lib/helper/WebDriver.js:1752:16)
      at processTicksAndRejections (internal/process/task_queues.js:82:5)

  TypeError: res.waitForClickable is not a function
      at WebDriver.waitForClickable (node_modules/codeceptjs/lib/helper/WebDriver.js:1752:16)
      at processTicksAndRejections (internal/process/task_queues.js:82:5)
```
I logged the res variable on WebDriver.js:1752. Here is what i got:

```bash
Element {
  sessionId: '0511db82b7c6e9eed4a48a7489dcafcb',
  elementId: '6bb2be49-6716-4650-b4b2-01935eeb363d',
  'element-6066-11e4-a52e-4f735466cecf': '6bb2be49-6716-4650-b4b2-01935eeb363d',
  selector: "[data-automation-id='admin-nav']",
  parent: Browser {
    sessionId: '0511db82b7c6e9eed4a48a7489dcafcb',
    capabilities: {
      acceptInsecureCerts: false,
      browserName: 'chrome',
      browserVersion: '77.0.3865.75',
      chrome: [Object],
      'goog:chromeOptions': [Object],
      networkConnectionEnabled: false,
      pageLoadStrategy: 'normal',
      platformName: 'linux',
      proxy: {},
      setWindowRect: true,
      strictFileInteractability: false,
      timeouts: [Object],
      unhandledPromptBehavior: 'dismiss and notify',
      'webdriver.remote.sessionid': '0511db82b7c6e9eed4a48a7489dcafcb'
    },
    addCommand: [Function],
    overwriteCommand: [Function]
  },
  index: 0,
  emit: [Function: bound ],
  addCommand: [Function],
  overwriteCommand: [Function]
}
```

> Source code

```js
    /**
     * Wait until element is available and then clicks it
     * @param element CSS or XPath
     */
    waitAndClick(element) {
      this.waitForClickable(element, 10);
      this.click(element);
    }
```

### Details

* CodeceptJS version: 2.3.6
* NodeJS Version: 12.5
* Operating System: I used [NodeJS docker image](https://github.com/nodejs/docker-node/blob/4f49f67ebd8d577dd7c97dabf5df69e6d947406c/12/stretch/Dockerfile)
* webdriverio 
* Configuration file:

```js
 {
  tests: './tests/*_test.js',
  timeout: 10000,
  output: './output',
  helpers: {
    WebDriver: {
      browser: 'chrome',
      fullPageScreenshots: true,
      host: 'selenium',
      restart: true,
      smartWait: 5000,
      timeouts: {
        script: 60000,
        'page load': 10000,
      },
      url: 'http://localhost:3000/',
      waitForTimeout: 20000,
      windowSize: 'maximize',
    }
  },
  include: {
    I: './custom_steps.js',
  },
  bootstrap: './bootstrap.js',
  plugins: {},
  mocha: {},
  require: [],
};
```

**Comment by pablopaul** [comment]
@costasovo what webdriverio version are you using? I assume it is not the latest, please try to upgrade it.

**Comment by costasovo** [comment]
@pablopaul It helped! I forgot to upgrade it. 🤦‍♂ My bad. Thanks for the help.
