### ISSUE TITLE
Appium: I.seeElement and I.fillField produce ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by mirao** [Codeception/CodeceptJS#2074]
It seems to be a regression in WebDriverIO 5.16.13.
It works without errors in WebDriverIO 5.16.11.
Note that the version 5.16.12 (between 5.16.11 and 5.16.13) contains a bug `fn(...).apply is not a function`, see https://github.com/webdriverio/webdriverio/issues/4859
#### What are you trying to achieve?
I'm testing Android app using Appium/WebDriver. The following two method calls should be working:
```js
I.seeElement("~SPORK logo");
...
I.fillField(commonPage.getResourceId("/tv_backup_code"), "atpasswd");
```
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
  Emitted | step.start (I see element "~SPORK logo")
    I see element "~SPORK logo"
    › [SmartWait (20000ms)] Locating ~SPORK logo in 20000
2019-12-08T14:37:26.244Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined
    at resolve (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:32:21)
    at new Promise (<anonymous>)
    at hooks.map.hook (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:29)
    at Array.map (<anonymous>)
    at Element.executeHooksWithArgsShim (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:17)
    at Element.wrapCommandFn (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:66:34)
    at Element.elementErrorHandlerCallback (/home/mira/workspace/codeceptjs/node_modules/webdriverio/build/middlewares.js:40:8)
    at forEachAsync (/home/mira/workspace/codeceptjs/node_modules/codeceptjs/lib/helper/WebDriver.js:1084:61)
    at forEachAsync (/home/mira/workspace/codeceptjs/node_modules/codeceptjs/lib/helper/WebDriver.js:2210:19)
    at Appium.seeElement (/home/mira/workspace/codeceptjs/node_modules/codeceptjs/lib/helper/WebDriver.js:1084:28)
2019-12-08T14:37:26.251Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined
    at resolve (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:32:21)
    at new Promise (<anonymous>)
    at hooks.map.hook (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:29)
    at Array.map (<anonymous>)
    at Element.executeHooksWithArgsShim (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:17)
    at Element.wrapCommandFn (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:66:34)
    at Element.elementErrorHandlerCallbackFn (/home/mira/workspace/codeceptjs/node_modules/webdriverio/build/middlewares.js:21:57)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-12-08T14:37:26.252Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined
    at resolve (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:32:21)
    at new Promise (<anonymous>)
    at hooks.map.hook (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:29)
    at Array.map (<anonymous>)
    at Element.executeHooksWithArgsShim (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:17)
    at Element.wrapCommandFn (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:66:34)
    at Element.elementErrorHandlerCallback (/home/mira/workspace/codeceptjs/node_modules/webdriverio/build/middlewares.js:40:8)
    at Element.isDisplayed (/home/mira/workspace/codeceptjs/node_modules/webdriverio/build/commands/element/isDisplayed.js:28:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-12-08T14:37:26.257Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined
    at resolve (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:32:21)
    at new Promise (<anonymous>)
    at hooks.map.hook (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:29)
    at Array.map (<anonymous>)
    at Element.executeHooksWithArgsShim (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:17)
    at Element.wrapCommandFn (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:66:34)
    at Element.elementErrorHandlerCallbackFn (/home/mira/workspace/codeceptjs/node_modules/webdriverio/build/middlewares.js:21:57)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-12-08T14:37:26.707Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined
    at resolve (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:32:21)
    at new Promise (<anonymous>)
    at hooks.map.hook (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:29)
    at Array.map (<anonymous>)
    at Element.executeHooksWithArgsShim (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:17)
    at Element.wrapCommandFn (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:82:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-12-08T14:37:26.707Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined
    at resolve (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:32:21)
    at new Promise (<anonymous>)
    at hooks.map.hook (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:29)
    at Array.map (<anonymous>)
    at Element.executeHooksWithArgsShim (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:17)
    at Element.wrapCommandFn (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:82:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-12-08T14:37:26.707Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined
    at resolve (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:32:21)
    at new Promise (<anonymous>)
    at hooks.map.hook (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:29)
    at Array.map (<anonymous>)
    at Element.executeHooksWithArgsShim (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:17)
    at Element.wrapCommandFn (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:82:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-12-08T14:37:26.708Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined
    at resolve (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:32:21)
    at new Promise (<anonymous>)
    at hooks.map.hook (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:29)
    at Array.map (<anonymous>)
    at Element.executeHooksWithArgsShim (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:17)
    at Element.wrapCommandFn (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:82:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    Emitted | step.passed (I see element "~SPORK logo")
    Emitted | step.finish (I see element "~SPORK logo")
```
```bash
    Emitted | step.start (I fill field "#com.spork.dev:id/tv_backup_code", "atpasswd")
    I fill field "#com.spork.dev:id/tv_backup_code", "atpasswd"
    › [SmartWait (20000ms)] Locating //*[@resource-id='com.spork.dev:id/tv_backup_code'] in 20000
2019-12-08T14:37:57.803Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'apply' of undefined
    at resolve (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:32:21)
    at new Promise (<anonymous>)
    at hooks.map.hook (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:29)
    at Array.map (<anonymous>)
    at Element.executeHooksWithArgsShim (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:28:17)
    at Element.wrapCommandFn (/home/mira/workspace/codeceptjs/node_modules/@wdio/utils/build/shim.js:66:34)
    at Element.elementErrorHandlerCallback (/home/mira/workspace/codeceptjs/node_modules/webdriverio/build/middlewares.js:40:8)
    at Appium.fillField (/home/mira/workspace/codeceptjs/node_modules/codeceptjs/lib/helper/WebDriver.js:783:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
...
```
I noticed that the test passes even though those errors occur.
### Details

* CodeceptJS version: 2.3.6
* NodeJS Version: 10.17.0
* Operating System: Ubuntu 19.10
* webdriverio 5.16.13
* appium 1.15.1
* Android 8.1

**Comment by mirao** [comment]
Fixed in @wdio/sync@5.16.14, see https://github.com/webdriverio/webdriverio/issues/4859#issuecomment-562958552
