### ISSUE TITLE
Could not require module 'mochawesome/addContext'

### ISSUE THREAD

**Issue by Anikethana** [Codeception/CodeceptJS#2110]
#### What are you trying to achieve?
Run codeceptjs inside codeception/codeceptjs docker with mocha Mochawesome Helper
I do not get the error when I run outside the docker
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Could not load helper Mochawesome from module './helper/Mochawesome':
Could not require module 'mochawesome/addContext'

Error:
    at createHelpers (/codecept/lib/container.js:159:13)
    at Function.create (/codecept/lib/container.js:35:25)
    at Codecept.init (/codecept/lib/codecept.js:55:15)
    at Command.module.exports (/codecept/lib/command/run.js:33:14)
    at Command.listener (/codecept/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:209:13)
    at Command.parseArgs (/codecept/node_modules/commander/index.js:651:12)
    at Command.parse (/codecept/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/codecept/bin/codecept.js:188:9)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 2.3.6
* NodeJS Version: 10.16.0
* Operating System: Mac
* puppeteer: 2.0.0
* Configuration file:

```js
{
    tests: config[process.profile].tests || './codecept/test/*_test.js',
    output: codeceptTargetPath + process.profile,
    helpers: {
        Puppeteer: {
            url: 'https://127.0.0.1:10000',
            rootElement: 'body',
            show: false,
            restart: true,
            keepBrowserState: false,
            uniqueScreenshotNames: false,
            keepCookies: true,
            waitForAction: 1000,
            waitForNavigation: ['load', 'domcontentloaded'],
            slowMo: 200,
            userAgent: config[process.profile].userAgent || browserUserAgent,
            windowSize: config[process.profile].windowSize || '1200x800',
            chrome: {
                ignoreHTTPSErrors: true,
                w3c: false,
                args: ['--disable-web-security', '--disable-gpu', '--no-sandbox']
            }
        },
        Util: {
            require: codeceptPath + 'helper/util_helper.js',
        },
        Accessibility: {
            require: codeceptPath + 'helper/accessibility_helper.js',
        },
        Mochawesome: {
            uniqueScreenshotNames: true
        },
        MockRequest: {}
    },
    include: {},
    mocha: {
        reporterOptions: {
            mochawesome: {
                reportDir: codeceptTargetPath + process.profile,
                stdout: codeceptProfilePath + '/console.log',
                screenshotsFolder: codeceptTargetPath + process.profile,
                options: {
                    reportDir: codeceptProfilePath,
                    inlineAssets: false,
                    uniqueScreenshotNames: true
                }
            },
            'mocha-junit-reporter': {
                stdout: targetPath + 'failsafe-reports/' + process.profile + '-console.log',
                options: {
                    mochaFile: targetPath + 'failsafe-reports/' + process.profile + '-codecept-result.xml'
                }
            }
        }
    }
```

**Comment by PeterNgTr** [comment]
I suppose this can be closed. Adding your required modules in your `package.json` would help. @Anikethana just reopening it if there is something else.
