### ISSUE TITLE
codeceptjs docker container won't run

### ISSUE THREAD

**Issue by TechSvcs** [Codeception/CodeceptJS#2137]
#### What are you trying to achieve?
Run the docker codeceptjs container:
- docker pull codeception/codeceptjs
- docker run -it codeception/codeceptjs
#### What do you get instead?
CodeceptJS directory has been found.
Error: Can not load config from /tests/codecept.conf.js or /tests/codecept.json
CodeceptJS is not initialized in this dir. Execute 'codeceptjs init' to start
    at Function.load (/codecept/lib/config.js:81:11)
    at module.exports.getConfig (/codecept/lib/command/utils.js:16:33)
    at Command.module.exports (/codecept/lib/command/run.js:17:16)
    at Command.listener (/codecept/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:209:13)
    at Command.parseArgs (/codecept/node_modules/commander/index.js:651:12)
    at Command.parse (/codecept/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/codecept/bin/codecept.js:225:9)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
### Details

- CodeceptJS version: latest
- NodeJS Version: container
- Operating System: Windows 10 ver 1909  
- Hyper-V 
- Docker ver 19.03.5
- Linux container

**Comment by PeterNgTr** [comment]
@TechSvcs did you mount your test folder as described here https://codecept.io/docker.html#how-to-use

**Comment by TechSvcs** [comment]
Sorry for the delayed response. I'm hung on "Mount in your CodeceptJS config directory into the /tests directory in the docker container." Haven't learned enough Docker yet.

**Comment by PeterNgTr** [comment]
you can refer to this https://github.com/Codeception/CodeceptJS/blob/master/test/docker-compose.yml. This is how our tests are setup to run within docker.

**Comment by TechSvcs** [comment]
Thank you. Another question: Are you aware of a way to export a codeceptjs test to Java with selenium?

**Comment by PeterNgTr** [comment]
@TechSvcs could we close this?
