### ISSUE TITLE
selectors not working after routing to new page 

### ISSUE THREAD

**Issue by ayrshid99** [Codeception/CodeceptJS#2168]
#### What are you trying to achieve?
i am trying to test single page application with codeceptjs and protractor, after the route is changed none of the selectors seem to be working and times out. i also tried in interactive mode but the results are same

#### What do you get instead?

  
```bash
npx codeceptjs run --steps
CodeceptJS v2.4.1
Using test root "C:\Users\ArshidDar\Desktop\codecept3"

(node:10112) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
sample --
  test something
    I am on page "/auth/login"
    I fill field "email", "admin@indiassetz.com"
    I fill field "password", "Password#123#"
    I click "sign in"
    I wait 4
    I click "#customer_arrow"
  × FAILED in 74790ms


-- FAILURES:

  1) sample
       test something:
     script timeout: result was not received in 10 seconds
  (Session info: chrome=79.0.3945.117)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.18363 x86_64)

  Scenario Steps:

  - I.click("#customer_arrow") at Test.Scenario (sample_test.js:9:7)
  - I.wait(4) at Test.Scenario (sample_test.js:8:7)
  - I.click("sign in") at Test.Scenario (sample_test.js:7:7)
  - I.fillField("password", "Password#123#") at Test.Scenario (sample_test.js:6:7)
  - I.fillField("email", "admin@indiassetz.com") at Test.Scenario (sample_test.js:5:7)
  - I.amOnPage("/auth/login") at Test.Scenario (sample_test.js:4:7)



  Run with --verbose flag to see NodeJS stacktrace
```

> Provide test source code if related

```js
  I.amOnPage('/auth/login');
     I.fillField("email","admin@abc.com")
     I.fillField("password","Password#123#")
     I.click("sign in")
     I.wait(4)
     I.click("#customer_arrow")

```

### Details

* CodeceptJS version:2.4.1
* NodeJS Version:10.16.0
* Operating System:win10
* protractor 
* Configuration file:

```js
exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    Protractor: {
      url: 'http://localhost',
      driver: 'hosted',
      browser: 'chrome',
      rootElement: 'body',
      angular: true
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'codecept3',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    },
    wdio: {
      enabled: true,
      services: ['selenium-standalone']
  }
  }
}```

**Comment by elukoyanov** [comment]
Try please with actual chromedriver
Driver 2.43.600210 does not supports 72+ chromes

See actual versions here
https://chromedriver.chromium.org/downloads

**Comment by ayrshid99** [comment]
i downloaded standalone jar and passed chrome driver as argument now getting this error 
```
test something
    I am on page "/auth/login"
    I fill field "email", "admin@admin.com"
    I fill field "password", "Password"
    I click "sign in"
    I wait 2
    I click "#customer_arrow"
  × FAILED in 72163ms


-- FAILURES:

  1) sample
       test something:
     script timeout
  (Session info: chrome=79.0.3945.130)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'VBIND000004', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: unknown

```

**Comment by DavertMik** [comment]
Sorry this is chrome-chromedriver issue, we can't do anything about it
