### ISSUE TITLE
screenshotOnFail not working with wdio and allure reports

### ISSUE THREAD

**Issue by dlopespg** [Codeception/CodeceptJS#2177]
#### What are you trying to achieve?

Add screenshots on fail on allure reports

#### What do you get instead?
Browser image is not captured, using default config or disabling allure reports

> Provide console output if related. Use `--verbose` mode for more details.

```bash
PS C:\Projetos\Test> ./node_modules/.bin/codeceptjs run --steps --plugins allure --verbose
CodeceptJS v2.4.3
Using test root "C:\Projetos\itms"
Helpers: Webdriver
Plugins: screenshotOnFail, allure, wdio, autoDelay

Go --
    Emitted | suite.before ([object Object])
 » Started SeleniumStandaloneLauncher
  Print
    Emitted | test.before ([object Object])
 » [Window Size] [object Object]
    Emitted | test.start ([object Object])
    Emitted | step.before (I am on page "/")
    Emitted | step.after (I am on page "/")
    Emitted | step.before (I see "Print")
    Emitted | step.after (I see "Print")
    Emitted | step.start (I am on page "/")
    I am on page "/"
    Emitted | step.passed (I am on page "/")
    Emitted | step.finish (I am on page "/")
    Emitted | step.start (I see "Print")
    I see "Print"
    » [SmartWait (5000ms)] Locating body in 5000
    [1] Error | Error
    Emitted | step.failed (I see "Print")
    Emitted | step.finish (I see "Print")
    [1] Error | Error
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
  × FAILED in 4553ms

    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) Go
       Print:

      expected web page to include "Print"
      + expected - actual

      -HOMESHIPMENT EXPLORER
      -Select user:
      -Permissions
      ---( 13 lines more )---
      +Print


  Scenario Steps:

  - I.see("Print") at Test.<anonymous> (teste_test.js:5:5)
  - I.amOnPage("/") at Test.<anonymous> (teste_test.js:4:5)




  FAIL  | 0 passed, 1 failed   // 21s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
 » Stopped SeleniumStandaloneLauncher
```

> Provide test source code if related

```js
Feature('Go');

Scenario('Print', (I) => {
  I.amOnPage('/');
  I.see('Print');
});
```

### Details

* CodeceptJS version:2.4.3
* NodeJS Version:v12.13.1
* Operating System:Windows 10
* wdio/selenium-standalone-service:5.16.10
* allure-commandline: 2.13.0
* codeceptjs: 2.4.3
* wdio: 4.0.0
* webdriverio: 5.18.6
* webdriver: 5.17.0
  
* Configuration file:

```js
exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    Webdriver: {
      url: 'http://localhost/sso',
      browser: 'chrome',
      restart: true,
      windowSize:'maximize',
      smartWait: 5000
      }
  },
  include: {
    I: './steps_file.js',
  },
  plugins: {
    allure: {
      enabled: true
    },
    wdio: {
      enabled: true,
      services: ['selenium-standalone']
    },
    autoDelay: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  },
  bootstrap: null,
  mocha: {},
  name: 'Test Automation'
}
```

**Comment by dlopespg** [comment]
Changed helper name from ` Webdriver: {` to ` WebDriver: {` fixed the issue
