### ISSUE TITLE
[Playwright] - Error thrown when trying to saving screenshot

### ISSUE THREAD

**Issue by PeterNgTr** [Codeception/CodeceptJS#2246]
#### What are you trying to achieve?
No error thrown for failed case.

#### What do you get instead?

I got an error of trying to save the screenshot for failed case

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Scenario Steps:
  
  - I.see("abc") at Test.<anonymous> (test/PUT_test.js:21:4)
  - I.amOnPage("https://google.de") at Test.<anonymous> (test/PUT_test.js:20:4)
  
  
  
  Run with --verbose flag to see NodeJS stacktrace


  FAIL  | 0 passed, 1 failed   // 8s
(node:61443) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.captureScreenshot): Target closed.
    at /Users/thanhnguyen/Desktop/codeceptjs-rest-demo/node_modules/playwright-core/lib/chromium/crConnection.js:121:63
    at new Promise (<anonymous>)
    at CRSession.send (/Users/thanhnguyen/Desktop/codeceptjs-rest-demo/node_modules/playwright-core/lib/chromium/crConnection.js:120:16)
    at CRPage.takeScreenshot (/Users/thanhnguyen/Desktop/codeceptjs-rest-demo/node_modules/playwright-core/lib/chromium/crPage.js:361:43)
    at async Screenshotter._screenshot (/Users/thanhnguyen/Desktop/codeceptjs-rest-demo/node_modules/playwright-core/lib/screenshotter.js:109:24)
    at async /Users/thanhnguyen/Desktop/codeceptjs-rest-demo/node_modules/playwright-core/lib/screenshotter.js:72:20
  -- ASYNC --
    at Page.<anonymous> (/Users/thanhnguyen/Desktop/codeceptjs-rest-demo/node_modules/playwright-core/lib/helper.js:54:23)
    at Playwright.saveScreenshot (/Users/thanhnguyen/Desktop/codeceptjs-rest-demo/node_modules/codeceptjs/lib/helper/Playwright.js:1552:22)
(node:61443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:61443) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

> Provide test source code if related

```js
// paste test
```

### Details

```js
codeceptVersion:  "2.5.0"
nodeInfo:  12.16.0
osInfo:  macOS 10.15.1
cpuInfo:  (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
chromeInfo:  80.0.3987.122
edgeInfo:  N/A
firefoxInfo:  Not Found
safariInfo:  Not Found
helpers:  {
 "Playwright": {
  "url": "http://localhost",
  "show": true,
  "waitForNavigation": "networkidle0"
 }
}
plugins:  {
 "screenshotOnFail": {
  "enabled": true
 },
 "allure": {
  "enabled": false
 },
 }
}
```

**Comment by PeterNgTr** [comment]
that was my bad! Closed this for now!
