### ISSUE TITLE
[Selenium Webdriver] Error:  "Could not load plugin wdio from module './plugin/wdio', and Cannot read property 'outputDir' of undefined"

### ISSUE THREAD

**Issue by hungdao-testing** [Codeception/CodeceptJS#2288]
I got the same issue
Here is my configuration
```
const { setHeadlessWhen } = require("@codeceptjs/configure");

// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: "./*_test.js",
  output: "./output",
  helpers: {
    WebDriver: {
      url: "http://localhost",
      browser: "chrome",
      host: "127.0.0.1",
      port: 4444,
      restart: false,
      windowSize: "1920x1680"
    }
  },
  include: {
    I: "./steps_file.js"
  },
  bootstrap: null,
  mocha: {},
  name: "googlecalendar",
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    },
    wdio: {
      enabled: true,
      services: ["selenium-standalone"]
    }
  }
};

```
```
{
  "name": "googlecalendar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {},
  "dependencies": {
    "@wdio/selenium-standalone-service": "^6.0.4",
    "codeceptjs": "^2.5.0"
  }
}

```
Notes: already install selenium-standalone

When I run a test case, with basic steps
```
Feature("Login");

Scenario("Login to calendar", I => {
  I.amOnPage("https://calendar.google.com/");
});

```
I got the issue as in the title of the bug
_Originally posted by @hungdao-testing in https://github.com/Codeception/CodeceptJS/issues/2151#issuecomment-605547416_

**Comment by KateKorneeva** [comment]
I am also having this for  "codeceptjs": "^2.6.0"

**Comment by PeterNgTr** [comment]
seemed like this issue is raised in https://github.com/webdriverio/webdriverio/issues/5155

after digging into the issue, here is the stacktrace

```sh
MBP-Thanh-Home:amazon-ui-tests thanhnguyen$ npx codeceptjs run --grep @test --verbose
TypeError: Cannot read property 'outputDir' of undefined
    at new SeleniumStandaloneLauncher (/Users/thanhnguyen/Desktop/amazon-ui-tests/node_modules/@wdio/selenium-standalone-service/build/launcher.js:41:46)
    at module.exports (/Users/thanhnguyen/Desktop/amazon-ui-tests/node_modules/codeceptjs/lib/plugin/wdio.js:102:24)
    at createPlugins (/Users/thanhnguyen/Desktop/amazon-ui-tests/node_modules/codeceptjs/lib/container.js:273:44)
    at Function.create (/Users/thanhnguyen/Desktop/amazon-ui-tests/node_modules/codeceptjs/lib/container.js:45:25)
    at Codecept.init (/Users/thanhnguyen/Desktop/amazon-ui-tests/node_modules/codeceptjs/lib/codecept.js:57:15)
    at Command.module.exports (/Users/thanhnguyen/Desktop/amazon-ui-tests/node_modules/codeceptjs/lib/command/run.js:28:14)
    at Command.listener (/Users/thanhnguyen/Desktop/amazon-ui-tests/node_modules/codeceptjs/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:209:13)
    at Command.parseArgs (/Users/thanhnguyen/Desktop/amazon-ui-tests/node_modules/codeceptjs/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/thanhnguyen/Desktop/amazon-ui-tests/node_modules/codeceptjs/node_modules/commander/index.js:474:21)

Could not load plugin wdio from module './plugin/wdio':
Cannot read property 'outputDir' of undefined
```
