### ISSUE TITLE
[WebDriver 6.x]: Random failure "GotError: read ECONNRESET/socket hang up" in Appium tests

### ISSUE THREAD

**Issue by mirao** [Codeception/CodeceptJS#2332]
It's a regression in `WebDriver 6.x` (tested with 6.0.0 and with the latest version 6.0.15, both are affected)
It works well with `WebDriver 5.18.6`
#### What do you get instead?
Sometimes (2 or 3 test runs of 10 tries) my test of Android App fails with the error "read ECONNRESET" or "socket hang up".

> Provide console output if related. Use `--verbose` mode for more details.

**test log:**
```bash
...
Remove app
    Emitted | test.before ([object Object])
 › [Test Config] Appium {"desiredCapabilities":{"appWaitActivity":"com.spork.android.controllers.activities.Home"}}
2020-04-10T14:30:13.390Z ERROR webdriver: GotError: socket hang up
    at onError (/home/mirao/workspace/codeceptjs/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/home/mirao/workspace/codeceptjs/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketCloseListener (_http_client.js:364:25)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at TCP._handle.close (net.js:607:12)
    [1] Error | Error: Can't connect to WebDriver.
Error: Failed to create session.
socket hang up

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
    Emitted | test.failed ([object Object])
  ✖ "before each" hook: codeceptjs.before for "Remove app" in 35ms
    [1] Error | Error: Can't connect to WebDriver.
Error: Failed to create session.
socket hang up

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
Error: Can't connect to WebDriver.
Error: Failed to create session.
socket hang up

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

```
**appium log:** (from the same time as test log)
```bash
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"app":"http://192.168.10.133/SPORK-new.apk","appWaitActivity":"com.spork.android.controllers.activities.ProvisioningMain","platformName":"Android","platformVersion":"8.1","autoGrantPermissions":true,"noReset":true,"adbExecTimeout":120000,"noSign":true,"deviceName":"emulator"},"firstMatch":[{}]},"desiredCapabilities":{"app":"http://192.168.10.133/SPORK-new.apk","appWaitActivity":"com.spork.android.controllers.activities.ProvisioningMain","platformName":"Android","platformVersion":"8.1","autoGrantPermissions":true,"noReset":true,"adbExecTimeout":120000,"noSign":true,"deviceName":"emulator"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"http://192.168.10.133/SPORK-new.apk","appWaitActivity":"com.spork.android.controllers.activities.ProvisioningMain","platformName":"Android","platformVersion":"8.1","autoGrantPermissions":true,"noReset":true,"adbExecTimeout":120000,"noSign":true,"deviceName":"emulator"},null,{"alwaysMatch":{"app":"http://192.168.10.133/SPORK-new.apk","appWaitActivity":"com.spork.android.controllers.activities.ProvisioningMain","platformName":"Android","platformVersion":"8.1","autoGrantPermissions":true,"noReset":true,"adbExecTimeout":120000,"noSign":true,"deviceName":"emulator"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1586529013423 (14:30:13 GMT+0000 (Coordinated Universal Time))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   app
[BaseDriver]   appWaitActivity
[BaseDriver]   platformVersion
[BaseDriver]   autoGrantPermissions
[BaseDriver]   noReset
[BaseDriver]   adbExecTimeout
[BaseDriver]   noSign
[BaseDriver]   deviceName
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator2' by default and using the 
[Appium]   UiAutomator2 Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   In previous versions (Appium <= 1.13.x), the default was 
[Appium]   'automationName=UiAutomator1'
[Appium] 
[Appium]   If you wish to use that automation instead of UiAutomator2, please 
[Appium]   add 'automationName=UiAutomator1' to your desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Appium v1.17.0 creating new AndroidUiautomator2Driver (v1.44.2) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "appium:app": "http://192.168.10.133/SPORK-new.apk",
[debug] [BaseDriver]     "appium:appWaitActivity": "com.spork.android.controllers.activities.ProvisioningMain",
[debug] [BaseDriver]     "platformName": "Android",
[debug] [BaseDriver]     "appium:platformVersion": "8.1",
[debug] [BaseDriver]     "appium:autoGrantPermissions": true,
[debug] [BaseDriver]     "appium:noReset": true,
[debug] [BaseDriver]     "appium:adbExecTimeout": 120000,
[debug] [BaseDriver]     "appium:noSign": true,
[debug] [BaseDriver]     "appium:deviceName": "emulator"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: c6910fca-807e-4aa8-9bb7-74fa10985d0b
[BaseDriver] Using downloadable app 'http://192.168.10.133/SPORK-new.apk'
[debug] [Instrumentation] .
[debug] [BaseDriver] App Last-Modified: Thu, 26 Mar 2020 22:04:36 GMT
[BaseDriver] Reusing previously downloaded application at '/tmp/2020310-6-1p6oztd.owgb/SPORK-new.apk'
[debug] [UiAutomator2] Checking whether app is actually present
[ADB] Using 'adb' from '/Android_Sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Looking for a device with Android '8.1.0'
[debug] [ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 8.1.0
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/Android_Sdk/platform-tools/adb'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 27
[debug] [ADB] Device API level: 27
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Package name: 'com.spork.dev'
[ADB] Main activity name: 'com.spork.android.controllers.activities.Home'
[debug] [AndroidDriver] Parsed package and activity are: com.spork.dev/com.spork.android.controllers.activities.Home
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [Instrumentation] Time: 6.094
[debug] [Instrumentation] 
[debug] [Instrumentation] OK (1 test)
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [Instrumentation] The process has exited with code 0
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.1.0' >= '3.1.0')
[debug] [ADB] There is no need to install/upgrade '/usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[debug] [ADB] Forwarding system: 8200 to device: 6790
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\:8200 tcp\:6790'
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is installed
[debug] [ADB] Getting package info for 'io.appium.uiautomator2.server'
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.5.5' >= '4.5.5')
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[debug] [ADB] Checking app cert for /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.5.apk
[ADB] Using 'apksigner.jar' from '/Android_Sdk/build-tools/30.0.0-rc2/lib/apksigner.jar'
[debug] [ADB] Starting apksigner: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Xmx1024M -Xss1m -jar /Android_Sdk/build-tools/30.0.0-rc2/lib/apksigner.jar verify --print-certs /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.5.apk
[ADB] Cannot use apksigner tool for signature verification. Original error: Command '/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Xmx1024M -Xss1m -jar /Android_Sdk/build-tools/30.0.0-rc2/lib/apksigner.jar verify --print-certs /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.5.apk' exited with code 1
[debug] [ADB] Defaulting to verify.jar
[debug] [ADB] '/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.5.apk' is signed with the default certificate
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is installed
[debug] [ADB] Checking app cert for /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting apksigner: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Xmx1024M -Xss1m -jar /Android_Sdk/build-tools/30.0.0-rc2/lib/apksigner.jar verify --print-certs /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[ADB] Cannot use apksigner tool for signature verification. Original error: Command '/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Xmx1024M -Xss1m -jar /Android_Sdk/build-tools/30.0.0-rc2/lib/apksigner.jar verify --print-certs /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' exited with code 1
[debug] [ADB] Defaulting to verify.jar
[debug] [ADB] '/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is signed with the default certificate
[UiAutomator2] Server packages are not going to be (re)installed
[debug] [UiAutomator2] Waiting up to 30000ms for services to be available
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm list instrumentation'
[debug] [UiAutomator2] Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[debug] [ADB] Getting install status for com.spork.dev
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package com.spork.dev'
[debug] [ADB] 'com.spork.dev' is installed
[debug] [ADB] Getting package info for 'com.spork.dev'
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package com.spork.dev'
[debug] [ADB] The version name of the installed 'com.spork.dev' is greater or equal to the application version name ('1.2.10' >= '1.2.10')
[debug] [ADB] There is no need to install/upgrade '/tmp/2020310-6-1p6oztd.owgb/SPORK-new.apk'
[debug] [UiAutomator2] Performing shallow cleanup of automation leftovers
[debug] [UiAutomator2] No obsolete sessions have been detected (Error: socket hang up)
[debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server.test'
[UiAutomator2] Starting UIAutomator2 server 4.5.5
[UiAutomator2] Using UIAutomator2 server from '/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.5.apk' and test from '/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[debug] [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body

```
> Provide test source code if related

```js
Scenario("Remove app", () => {
    I.removeApp(commonPage.appName);
    I.seeAppIsNotInstalled(commonPage.appName);
}).config("Appium", activityHome);
```

### Details

* CodeceptJS version: 2.6.1
* NodeJS Version: 10.18.1
* Operating System: Ubuntu 20.04
* webdriverio 6.0.15
* Appium 1.17
* Configuration file:

```js
const commonPage = require("./pages/common");

exports.config = {
    output: "./output",
    helpers: {
        Appium: {
            platform: "Android",
            waitForTimeout: 10000,
            smartWait: 20000,
            device: "emulator",
            desiredCapabilities: {
                app: "http://192.168.10.133/SPORK-new.apk",
                appWaitActivity: commonPage.getActivityProvisioningSelection(),
                platformName: "Android",
                platformVersion: "8.1",
                autoGrantPermissions: true,
                noReset: true,
                adbExecTimeout: 120000,
                noSign: true
            }
        },
        REST: {},
        Spork: {
            require: "./spork_helper.js",
            user: {
                firstName: "Androidovic",
                lastName: "Autotest",
            },
            schoolName: "AT Laboratory School",
            tenantId: 1, // Charter tenant
            serialNumber: "EMU-AT" // Serial number of tablet
        },
        Mochawesome: {},
    },
    include: {
        I: "./steps_file.js",
        commonPage: "./pages/common.js"
    },
    mocha: {
        reporterOptions: {
            "codeceptjs-cli-reporter": {
                stdout: "-",
                options: {
                    verbose: false,
                    debug: true,
                    steps: true
                }
            },
            mochawesome: {
                stdout: "./output/console.log",
                options: {
                    reportDir: "./output",
                    reportFilename: "report"
                }
            },
            "mocha-junit-reporter": {
                stdout: "./output/console.log",
                options: {
                    mochaFile: "./output/result.xml",
                    jenkinsMode: true,
                    attachments: true //add screenshot for a failed test
                },
            }
        }
    },
    bootstrap: false,
    teardown: null,
    hooks: [],
    gherkin: {},
    tests: "./*_test.js",
    timeout: 10000,
    name: "spork-android-app"
};

```

**Comment by idxn** [comment]
Do you have the appium server log with the timestamp? I suspect it relates to newCommandTimeout config.

**Comment by mirao** [comment]
@idxn , here is:
**appium log:**
```bash
...
2020-04-11 17:34:43:541 - [HTTP] --> DELETE /wd/hub/session/4476161b-45bf-4cce-9fe9-6e07f057b6ea
2020-04-11 17:34:43:541 - [HTTP] {}
2020-04-11 17:34:43:542 - [debug] [W3C (4476161b)] Calling AppiumDriver.deleteSession() with args: ["4476161b-45bf-4cce-9fe9-6e07f057b6ea"]
2020-04-11 17:34:43:542 - [debug] [BaseDriver] Event 'quitSessionRequested' logged at 1586626483542 (17:34:43 GMT+0000 (Coordinated Universal Time))
2020-04-11 17:34:43:542 - [Appium] Removing session 4476161b-45bf-4cce-9fe9-6e07f057b6ea from our master session list
2020-04-11 17:34:43:543 - [debug] [UiAutomator2] Deleting UiAutomator2 session
2020-04-11 17:34:43:543 - [debug] [UiAutomator2] Deleting UiAutomator2 server session
2020-04-11 17:34:43:543 - [debug] [WD Proxy] Matched '/' to command name 'deleteSession'
2020-04-11 17:34:43:544 - [debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/wd/hub/session/aa2d249a-b351-4176-8164-4f8152d48f11] with no body
2020-04-11 17:34:43:556 - [debug] [WD Proxy] Got response with status 200: {"sessionId":"aa2d249a-b351-4176-8164-4f8152d48f11","value":null}
2020-04-11 17:34:43:557 - [debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.spork.dev'
2020-04-11 17:34:43:625 - [debug] [Logcat] Stopping logcat capture
2020-04-11 17:34:43:626 - [debug] [ADB] Removing forwarded port socket connection: 8200 
2020-04-11 17:34:43:626 - [debug] [ADB] Running '/Android_Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
2020-04-11 17:34:43:643 - [debug] [BaseDriver] Event 'quitSessionFinished' logged at 1586626483643 (17:34:43 GMT+0000 (Coordinated Universal Time))
2020-04-11 17:34:43:644 - [debug] [W3C (4476161b)] Received response: null
2020-04-11 17:34:43:644 - [debug] [W3C (4476161b)] But deleting session, so not returning
2020-04-11 17:34:43:645 - [debug] [W3C (4476161b)] Responding to client with driver.deleteSession() result: null
2020-04-11 17:34:43:647 - [debug] [W3C (4476161b)] Destroying socket connection
2020-04-11 17:34:43:652 - [HTTP] <-- DELETE /wd/hub/session/4476161b-45bf-4cce-9fe9-6e07f057b6ea 200 106 ms - 14
2020-04-11 17:34:43:652 - [HTTP] 
2020-04-11 17:34:44:459 - [debug] [Instrumentation] .
2020-04-11 17:34:44:724 - [debug] [Instrumentation] Time: 20.1
2020-04-11 17:34:44:725 - [debug] [Instrumentation] 
2020-04-11 17:34:44:725 - [debug] [Instrumentation] OK (1 test)
2020-04-11 17:34:44:763 - [debug] [Instrumentation] The process has exited with code 0
```
**test log:**
```bash
...
   Emitted | test.after ([object Object])
 › [Test Config] Reverted for Appium
  Remove app
    Emitted | test.before ([object Object])
2020-04-11T17:34:43.657Z ERROR webdriver: GotError: socket hang up
    at onError (/home/mirao/workspace/codeceptjs/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at ClientRequest.request.on.error (/home/mirao/workspace/codeceptjs/node_modules/got/dist/source/request-as-event-emitter.js:157:17)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at ClientRequest.origin.emit.args (/home/mirao/workspace/codeceptjs/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketOnEnd (_http_client.js:426:9)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [1] Error | Error: Can't connect to WebDriver.
Error: Failed to create session.
socket hang up

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
    Emitted | test.failed ([object Object])
  ✖ "before each" hook: codeceptjs.before for "Remove app" in 15ms
    [1] Error | Error: Can't connect to WebDriver.
Error: Failed to create session.
socket hang up

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
Error: Can't connect to WebDriver.
Error: Failed to create session.
socket hang up

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])
```

**Comment by mirao** [comment]
It seems that things work well with latest stable Appium `1.15.1` whereas problematic is pre-release version `1.17`.

**Summary:**
WebDriver 5.x <=> Appium 1.17.0 ... test passes :heavy_check_mark:
WebDriver 6.x <=> Appium 1.17.0 ... test fails ❌
WebDriver 6.x <=> Appium 1.15.1 ... test passes :heavy_check_mark:

**Comment by idxn** [comment]
@mirao do you have the log before delete session line?

**Comment by mirao** [comment]
@idxn, here are the logs with info before delete session line
- WebDriver 5.x <=> Appium 1.17.0
-- appium log: https://gist.github.com/mirao/36cc132ff1d47ac630b2528ab303052c
-- test log: https://gist.github.com/mirao/9839785840838d2718d8e89efcfaf9b9
- WebDriver 6.x <=> Appium 1.17.0
-- appium log: https://gist.github.com/mirao/a13251c7d5327c6d39c3b457330cedac
-- test log: https://gist.github.com/mirao/e46e7c6b92bd566b39d867ea64594d01

**Comment by idxn** [comment]
From the appium server log, I suspect it's the timeout at client level. Could you increase the timeout from 10 secs to 15 secs?

``    helpers: {
        Appium: {
            platform: "Android",
            waitForTimeout: 10000
...
    tests: "./*_test.js",
    timeout: 10000,
,

**Comment by mirao** [comment]
@idxn Tested with both values set to 15000 and 60000.
I also tested all values in [timeouts](http://webdriver.io/docs/timeouts.html) hash in Appium helper set to 60000 and all possible timeouts in Appium's desired capabilities, also set to 60 sec.

No success with those settings, the test fails (not always but sometimes).

**Comment by mirao** [comment]
Now I'm staying at the latest "stable" Appium [1.15](https://github.com/appium/appium-desktop/releases/tag/v1.15.1) which works for me with WebDriver 6.x.
So **workaround** for this issue is: Use Appium 1.15

We will see if the issue persists once next stable Appium is released

**Comment by mirao** [comment]
I think it was solved in past, because now I'm running Appium 1.22.3 and WebDriverIO 8.3.8 and everything works fine.
