### ISSUE TITLE
Can not run test with playwright

### ISSUE THREAD

**Issue by ledaivuong** [Codeception/CodeceptJS#2334]
#### What are you trying to achieve?
I'm a new player on codeceptjs with playwright so I just compose simple test script using Gherkin but it can not load the browser?
> Provide console output if related. Use `--verbose` mode for more details.

```bash
CodeceptJS v2.6.1
Using test root "C:\git\my-project"
Helpers: Playwright
Plugins: screenshotOnFail, retryFailedStep

Business rules --
  In order to achieve my goals
  As a persona
  I want to be able to interact with a system
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
 » [Session] Starting singleton browser session
    [1] Error | Error: Arguments can not specify page to be opened
    Emitted | test.failed ([object Object])
  × "before all" hook: codeceptjs.beforeSuite for "do something" in 5ms
    [1] Error | Error: Arguments can not specify page to be opened
Error: Arguments can not specify page to be opened
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) Business rules
       "before all" hook: codeceptjs.beforeSuite for "do something":
     Arguments can not specify page to be opened
  rror: Arguments can not specify page to be opened
      at Chromium._defaultArgs (node_modules\playwright-core\lib\server\chromium.js:130:19)
      at Chromium._launchServer (node_modules\playwright-core\lib\server\chromium.js:67:42)


  FAIL  | 0 passed, 1 failed   // 10ms
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

* Configuration file:

```js
require('import-export');

exports.config = {
  output: './output',
  helpers: {
    Playwright: {
      url: 'https://www.google.com',
      show: true,
      browser: 'chromium',
      waitForNavigation: ['domcontentloaded', 'networkidle0'],
      waitForAction: 1000,
      getPageTimeout: 10000,
      waitForTimeout: 10000,
      windowSize: '1366x784',
      chromium: {
        args: ['--disable-gpu',
          '--disable-extensions',
          'disable-popup-blocking',
          'disable-infobars'
        ]
      }
    }
  },
  include: {
    I: './steps_file.js',
    testPage: './pages/test.js'
  },
  mocha: {},
  bootstrap: null,
  teardown: null,
  hooks: [],
  gherkin: {
    features: './features/*.feature',
    steps: ['./step_definitions/steps.js']
  },
  plugins: {
    screenshotOnFail: {
      enabled: true
    },
    retryFailedStep: {
      enabled: true
    }
  },
  name: 'my-project'
}
```

### Details

* CodeceptJS version: v2.6.1
* NodeJS Version: v10.16.0
* Operating System: Windows 10
* playwright

**Comment by PeterNgTr** [comment]
Check this #2329 to modify your config, the waitForNagivation section.

**Comment by ledaivuong** [comment]
> Check this #2329 to modify your config, the waitForNagivation section.

I have changed: 
```
waitForNavigation: 'domcontentloaded',
```
but it still got same error

**Comment by PeterNgTr** [comment]
Could you post your test file?

**Comment by ledaivuong** [comment]
Page:
```
const { I } = inject();

class GooglePage {
  constructor() {
    this.searchTextBox = '//input[@name="q"]'
    this.searchButton = '(//input[@name="btnK"])[2]'
  }

  inputSearchTextBox(value) {
    I.appendField($this.searchButton, value)
  }

  clickSearchButton() {
    I.click(this.searchButton)
  }
}

export default new GooglePage()
```

Step:
```
const { I, testPage } = inject();
// Add in your custom step files

When('I input "([^"]*)"', (value) => {
  testPage.inputSearchTextBox(value)
});
```

Feature:
```
Feature: Business rules
  In order to achieve my goals
  As a persona
  I want to be able to interact with a system

  Scenario: do something
    Then I input "XYZ"

```

**Comment by PeterNgTr** [comment]
Oh, don’t you have the step I.amOnPage()?

**Comment by ledaivuong** [comment]
I have just added it into Step:
```
When('I am on page', () => {
  I.amOnPage()
})
```

This step can be recognized by Gherkin:
```
$ npx codeceptjs gherkin:steps
Gherkin Step definitions:

  I input "([^"]*)"
    => (C:\git\gf-service-booking-service-testing\step_definitions\steps.js:4:1)
  I am on page
    => (C:\git\gf-service-booking-service-testing\step_definitions\steps.js:8:1)

(node:18944) ExperimentalWarning: The fs.promises API is experimental
```

Feature:
```
Feature: Business rules
  In order to achieve my goals
  As a persona
  I want to be able to interact with a system

  Scenario: do something
    When I am on page
    When I input "XYZ"
```

But it still got same error

**Comment by PeterNgTr** [comment]
Did you inject I actor?


// use I  via inject() function
const { I } = inject();

**Comment by ledaivuong** [comment]
> Did you inject I actor?
> 
> // use I via inject() function
> const { I } = inject();

off course. I generate this file by codepceptjs cli so it auto add ```const { I } = inject();``` at the top of page/steps_definition files.

**Comment by PeterNgTr** [comment]
Have you tried?

I.amOnPage('/')

**Comment by ledaivuong** [comment]
> Have you tried?
> 
> I.amOnPage('/')

also tried that, not working

**Comment by PeterNgTr** [comment]
So could you provide a repo that could easily reproduce your issue?

**Comment by ledaivuong** [comment]
Have just upload it on this: https://github.com/ledaivuong/codeceptjs-testing-sample

**Comment by PeterNgTr** [comment]
I’m suspicious that you’re using playright v0.13 causes issue. Have you tried with v0.12?

**Comment by ledaivuong** [comment]
> I’m suspicious that you’re using playright v0.13 causes issue. Have you tried with v0.12.1?

It happens with v0.12.1 so I try to update it. Both of them have the same issue

**Comment by ledaivuong** [comment]
@PeterNgTr Any news or solutions to work around with that. I wonder how can we connect remote chromium or selenium on local manually

**Comment by PeterNgTr** [comment]
@ledaivuong I found out, it's your passed args, you missed the two dashes `--`
```js
...
          '--disable-popup-blocking',
          '--disable-infobars'
...
```

**Comment by ledaivuong** [comment]
It's correct. Thank you very much for your time
