### ISSUE TITLE
Test fails with plugin stepByStepReport applied on step in function BeforeSuite

### ISSUE THREAD

**Issue by mirao** [Codeception/CodeceptJS#2337]
#### What are you trying to achieve?
The plugin `stepByStepReport` works if you enable it in config file. Test shouldn't fail.

#### What do you get instead?
$ npx codeceptjs run Concepts_test.js --verbose
```bash
...
Context: BeforeSuite 
      I get random string "ATConceptNew"
    [1] Error | TypeError: Cannot read property 'toString' of undefined
    Emitted | step.failed (I get random string "ATConceptNew")
    Emitted | step.finish (I get random string "ATConceptNew")
    [1] Error | TypeError: Cannot read property 'toString' of undefined
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Error processing test.failed event:
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at persist (/home/mirao/workspace/codeceptjs/node_modules/codeceptjs/lib/plugin/stepByStepReport.js:182:24)
    at EventEmitter.event.dispatcher.on (/home/mirao/workspace/codeceptjs/node_modules/codeceptjs/lib/plugin/stepByStepReport.js:109:5)
    at EventEmitter.emit (events.js:203:15)
    at EventEmitter.emit (domain.js:448:20)
    at Object.emit (/home/mirao/workspace/codeceptjs/node_modules/codeceptjs/lib/event.js:115:28)
    at errHandler (/home/mirao/workspace/codeceptjs/node_modules/codeceptjs/lib/scenario.js:101:13)
    at recorder.catch (/home/mirao/workspace/codeceptjs/node_modules/codeceptjs/lib/scenario.js:132:11)
    at promise.catch (/home/mirao/workspace/codeceptjs/node_modules/codeceptjs/lib/recorder.js:227:9)
    [1] <teardown> Stopping recording promises

```

> Provide test source code if related

```js
BeforeSuite(async () => {
    addedConceptName = await I.getRandomString("ATConceptNew");
    renamedConceptName = await I.getRandomString("ATConceptRenamed");
});
```
helper's method:
```js
/**
* Generate random string with prefix
* @return {Promise<string>}
*/
getRandomString(prefix = "") {
    return prefix + Math.random().toString().substring(2);
}
```
Note that if you disable the plugin in config, the test works well.

### Details

* CodeceptJS version: 2.6.1
* NodeJS Version: 10.18.1
* Operating System: Ubuntu 20.04
* webdriverio 6.0.15
* Configuration file:

```js
...
    plugins: {
        screenshotOnFail: {
            enabled: true,
            uniqueScreenshotNames: true,
        },
        "stepByStepReport": {
            "enabled": true,
        },
        autoDelay: {
            enabled: true,
            delayBefore: 500
        }
    },
...
```

**Comment by mirao** [comment]
It's not related to `await` call, but to the fact that if I call a helper's method in `BeforeSuite` function, it's considered as a step by CodeceptJS. And as there is no event listener `event.suite.before` defined in `node_modules/codeceptjs/lib/plugin/stepByStepReport.js`, test finally fails on some undefined property (I guess on `stepNum`). IMHO it makes no sense to create screenshots in steps in `BeforeSuite` because `BeforeSuite` doesn't have any access to web browser.

If I call a method of test (not of helper) named `getRandomString` from `BeforeSuite`, test passes because the method call is not handled as a step.
```js
function getRandomString(prefix = "") {
    return prefix + Math.random().toString().substring(2);
}

BeforeSuite(async () => {
    addedConceptName = getRandomString("ATConceptNew");
    renamedConceptName = getRandomString("ATConceptRenamed");
});
```
A fix which works for me is this change in function `persistStep()` in  `node_modules/codeceptjs/lib/plugin/stepByStepReport.js`:
```js
async function persistStep(step) {
  if (isStepIgnored(step)) return;
  if (savedStep === step) return; // already saved
    
  // This is my fix
  // Ignore steps in BeforeSuite function
  if (step.metaStep && step.metaStep.name === "BeforeSuite") return; 
...
}
```

Anybody can respond if the solution is correct?

**Comment by mirao** [comment]
It seems that the function `AfterSuite` works well with stepByStepPlugin. Screenshots for steps in it are created in the folder with last test's scenario (though they cannot be reached from `index.html`).
So only `BeforeSuite` is affected.
