### ISSUE TITLE
Yahoo Example fail and hangs with nightmarejs

### ISSUE THREAD

**Issue by Zougi** [Codeception/CodeceptJS#262]
yahoo example from page <http://codecept.io/nightmare/> fails & hangs forever...
That's ok that it fails. In my opinion that makes it even a better example than a test that succeed..but codecept should not hang forever!

```
$ node .\node_modules\codeceptjs\bin\codecept.js run --verbose
CodeceptJS v0.4.7
Using test root "C:\Users\zougi\Documents\GitHub\myproject"

FirstTest.js --
   [1] Starting recording promises
   Emitted | suite.before
 > Nightmare._beforeSuite
   [1] Queued | hook Nightmare._beforeSuite()
 test something
   [2] Starting recording promises
   Emitted | test.before
 > Nightmare._before
   [2] Queued | hook Nightmare._before()
   Emitted | test.start ([object Object])
   [2] Queued | amOnPage: http://yahoo.com
   [2] Queued | fillField: p, github nightmare
   [2] Queued | click: Search Web
   [2] Queued | waitForElement: #main
   [2] Queued | seeElement: #main .searchCenterMiddle li a
   [2] Queued | seeElement: //a[contains(@href,'github.com/segmentio/nightmare')]
   [2] Queued | see: segmentio/nightmare, #main li a
   [2] Queued | finish test
   Emitted | step.before (I am on page "http://yahoo.com")
 * I am on page "http://yahoo.com"
   Emitted | step.after (I am on page "http://yahoo.com")
 > log: DARLA notice: 405
 > log: instantiating uh search component
 > [URL] https://fr.yahoo.com/?p=us
 > [Code] 200
 > [Headers] {"age":["0"],"cache-control":["no-store, no-cache, private, max-age=0"],"content-encoding":["gzip"],"content-type":["text/html; charset=UTF-8"],"date":["Mon, 17 Oct 2016 07:32:51 GMT"],"expires":["-1"],"p3p":["policyref=\"https://policies.yahoo.com/w3c/p3p.xml\", CP=\"CAO DSP COR CUR ADM DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV\""],"server":["ATS"],"set-cookie":["autorf=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=fr.yahoo.com"],"status":["200"],"strict-transport-security":["max-age=2592000"],"vary":["Accept-Encoding"],"via":["http/1.1 ir1.fp.ir2.yahoo.com (ApacheTrafficServer)"],"x-frame-options":["DENY"]}
   Emitted | step.before (I fill field "p", "github nightmare")
 * I fill field "p", "github nightmare"
   Emitted | step.after (I fill field "p", "github nightmare")
 > log: no outcome. setting it to null
   Emitted | step.before (I click "Search Web")
 * I click "Search Web"
   Emitted | step.after (I click "Search Web")
   [2] Error | Element #{}
   [2] Starting <teardown> session
   Emitted | test.failed ([object Object])
 > Nightmare._failed
   [2] <teardown> Queued | hook Nightmare._failed()
   Error processing test.failed event:
   TypeError: Cannot assign to read only property 'stack' of Element #{}
    at EventEmitter.<anonymous> (C:\Users\zougi\Documents\GitHub\myproject\node_modules\codeceptjs\lib\listener\trace.js:28:13)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
    at Object.module.exports.emit (C:\Users\zougi\Documents\GitHub\myproject\node_modules\codeceptjs\lib\event.js:34:28)
    at C:\Users\zougi\Documents\GitHub\myproject\node_modules\codeceptjs\lib\scenario.js:22:13
    at C:\Users\zougi\Documents\GitHub\myproject\node_modules\codeceptjs\lib\recorder.js:90:9
    at process._tickCallback (node.js:369:9)
 > Screenshot is saving to C:\Users\zougi\Documents\GitHub\myproject\test\e2e\errorShots\test_something.failed.png
```
fyi I'm on windows7 with node v4.5.0, nightmare v2.7.0

**Comment by DavertMik** [comment]
Thanks for the fix!
