### ISSUE TITLE
Unexpected strict mode reserved word on init

### ISSUE THREAD

**Issue by TrustNik** [Codeception/CodeceptJS#3]
Hi
I've done ```sudo npm install -g codeceptjs```, now when I am doing ```codeceptjs init``` in my project's root folder I get:
```
/usr/local/lib/node_modules/codeceptjs/lib/config.js:2
let fs = require('fs');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/codeceptjs/bin/codecept.js:6:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
````

Some env info
```
$ npm -v
3.3.12
$ node -v
v0.12.0
```

**Comment by DavertMik** [comment]
Please update NodeJS to current LTS 4.2.0
Then it should work. From my side I will need to update requirements

**Comment by TrustNik** [comment]
@DavertMik yep, putting requirements somewhere in the readme would be helpful. Thanks.
