### ISSUE TITLE
Get text from input field?

### ISSUE THREAD

**Issue by eduard-lind** [Codeception/CodeceptJS#318]
#### What are you trying to achieve?
I'm trying to get text, which was entered into input field
 
#### What do you get instead?
Empty string

> Provide console output if related. Use `--verbose` mode for more details.

-- FAILURES:

  1) @E2E Check ändern links on summary-page: @only ändern link for policy-holder page for non log-in person:

      '' == 'Max'
      + expected - actual

      +Max

npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid codecept-starter@1.0.0
npm verb cwd C:\Users\eduard.lind\Documents\unfall.uitestswebsitedesktop
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "grep" "--verbose"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! codecept-starter@1.0.0 grep: `cross-env NODE_ENV=qa codeceptjs run --steps --grep @only`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the codecept-starter@1.0.0 grep script 'cross-env NODE_ENV=qa codeceptjs run --steps --grep @only'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the codecept-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=qa codeceptjs run --steps --grep @only
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codecept-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls codecept-starter
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:

>Scenario:
Scenario('@only ändern link for policy-holder page for non log-in person', function* (I, insuredPersonsInputPage, policyHolder, resultsPage, paymentPage, summaryPage) {
  var assert = require('assert');
  //this.retries(2);
  insuredPersonsInputPage.enterBirthday('Ihre Angaben','20', '05', '1990');
  insuredPersonsInputPage.enterOccupation('#myself-0-occupation', 'Sekretär,in Steno');
  I.clickNext('Ihre Leistungen'); // click on weiter-button and waiting till loading of page. See custom steps
  I.clickNext('Grundschutz');
  resultsPage.clickOnTariffButton('Online Antrag', 'Grundschutz', 'HanseMerkur');
  policyHolder.fillRandomEmail();
  policyHolder.fillFullName('Herr', 'Max', 'Pecu');
  policyHolder.fillAdress('81825', 'Barbenweg');
  policyHolder.fillPhone('089 54355234');
  I.clickNext('eine Unfallversicherung?');
  I.clickNext('SEPA-Mandat');
  paymentPage.fillInIBAN('16532500000000000017');
  paymentPage.agreeWithSEPA();
  I.clickNext('noch etwas mitteilen?');
  summaryPage.clickAendernLink('Angaben Antragsteller', 'Jetzt anmelden');
  var currentName = yield I.grabTextFrom('//input[@id="firstName"]');
  assert.equal($currentName, 'Max');
  .....

Is it possible at all to get text from input field?

**Comment by eduard-lind** [comment]
I used wrong function. to get text from element need to use .grabValueFrom
