### ISSUE TITLE
Playwright: Chromium headless: Actions click(), saveScreenshot() etc. fail on timeout if an action in beforeSuite() takes longer time

### ISSUE THREAD

**Issue by mirao** [Codeception/CodeceptJS#3252]
It's a regression in Playwright 1.19 with Chromium 100.
It works well with Playwright 1.18 with Chromium 99.0.4812.0

I noticed the bug because in my production tests I have some longer actions in "prepare" stage in helper.

#### What are you trying to achieve?
The following test passes in Chromium headless.

#### What do you get instead?
The following test fails in Chromium headless. Note that it passes in Chromium headed ("windowed").

> Provide console output if related. Use `--verbose` mode for more details.

```bash
$ codeceptjs run --verbose
context
CodeceptJS v3.3.0
Using test root "/home/mirao/workspace/playwright"
Helpers: Playwright, MyHelper
Plugins: screenshotOnFail

My --
    [1]  Starting recording promises
    Timeouts: 
 › [Session] Starting singleton browser session
  Test click
    I am on page "/"
    I click {xpath: .//a[contains(., 'Get started')]}
    [1] Error | TimeoutError: elementHandle.click: Timeout 10000ms exceeded.
=========================== logs ===========================
attempting click action
  waiting for element to be visible, enabled and stable
============================================================
    [1] Error | TimeoutError: elementHandle.click: Timeout 10000ms exceeded.
=========================== logs ===========================
attempting click action
  waiting for element to be visible, enabled and stable
============================================================
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /home/mirao/workspace/playwright/output/Test_click.failed.png
 › <TimeoutError: page.screenshot: Timeout 10000ms exceeded.> 
  ✖ FAILED in 20648ms

    [2]  Starting recording promises

-- FAILURES:

  1) My
       Test click:
     elementHandle.click: Timeout 10000ms exceeded.
=========================== logs ===========================
attempting click action
  waiting for element to be visible, enabled and stable
============================================================
      at Playwright.proceedClick (node_modules/codeceptjs/lib/helper/Playwright.js:2507:19)
  
  Scenario Steps:
  - I.click({xpath: .//a[contains(., 'Get started')]}) at Test.<anonymous> (./My_test.js:5:7)
  - I.amOnPage("/") at Test.<anonymous> (./My_test.js:4:7)
  


  FAIL  | 0 passed, 1 failed   // 51s
```

Test:
```js
Feature('My');

Scenario('Test click', ({ I }) => {
    I.amOnPage("/");
    I.click(locate("a").withText("Get started"));
});
```

Helper:
```js
const Helper = require('@codeceptjs/helper');

class MyHelper extends Helper {
    async _beforeSuite() {
        // It simulates a "prepare" action before a test starts, it takes 30 sec
        await new Promise(resolve => setTimeout(resolve, 30000));
    }
}

module.exports = MyHelper;

```
### Details

* CodeceptJS version: 3.3.0
* NodeJS Version: v14.18.3
* Operating System: Ubuntu 21.10
* Playwright 1.19.1, Chromium 100.0.4863.0 headless
* Configuration file:

```js
exports.config = {
    tests: './*_test.js',
    output: './output',
    helpers: {
        Playwright: {
            url: 'https://playwright.dev',
            timeout: 10000,
            show: false,
            browser: 'chromium'
        },
        MyHelper: {
            require: './myhelper_helper.js',
        },
    },
    include: {
        I: './steps_file.js'
    },
    bootstrap: null,
    mocha: {},
    name: 'playwright'
}
```

**Comment by mirao** [comment]
**Workaround:** Change order of helpers in config so that custom helper `_beforeSuite()` starts before Playwright's helper `_beforeSuite()`:
```js
exports.config = {
    tests: './*_test.js',
    output: './output',
    helpers: {
        MyHelper: {
            require: './myhelper_helper.js',
        },
        Playwright: {
            url: 'https://playwright.dev',
            timeout: 10000,
            show: false,
            browser: 'chromium'
        },
    },
    include: {
        I: './steps_file.js'
    },
    bootstrap: null,
    mocha: {},
    name: 'playwright'
}
```

**Comment by mirao** [comment]
I did some more testing and the test:

- passes with `await new Promise(resolve => setTimeout(resolve, 1000));` in `_beforeSuite()`
- passes with `await new Promise(resolve => setTimeout(resolve, 1500));` in `_beforeSuite()`
- fails with `await new Promise(resolve => setTimeout(resolve, 2000));` in `_beforeSuite()`

Is there an internal timeout that is applied for Chromium headless in `_beforeSuite()`, regardless of custom timeout set in Playwright helper config?

**Comment by mirao** [comment]
It can be simulated even without custom helper. Just move the waiting from helper's `_beforeSuite` to test's `BeforeSuite()`:
```js
Feature('My');

BeforeSuite(({I}) => {
    I.wait(30);
})

Scenario('Test click', ({ I }) => {
    I.amOnPage("/");
    I.click(locate("a").withText("Get started"));
});
```
and test fails.

But if you move the waiting to the test's Scenario instead:
```js
Scenario('Test click', ({ I }) => {
    I.wait(30);
    I.amOnPage("/");
    I.click(locate("a").withText("Get started"));
});
```

then test works well.

**Comment by mirao** [comment]
Still can reproduce with Playwright [1.19.2](https://github.com/microsoft/playwright/releases/tag/v1.19.2) (Chromium 100.0.4863.0) :lady_beetle: 
Cannot reproduce with Playwright [1.20.0](https://github.com/microsoft/playwright/releases/tag/v1.20.0) (Chromium 101.0.4921.0), so it seems to be fixed :heavy_check_mark: 

Tested in CodeceptJS 3.3.0
