### ISSUE TITLE
Unable to use BeforeSuite and AfterSuite hooks

### ISSUE THREAD

**Issue by viveklandeWK** [Codeception/CodeceptJS#3353]
#### What are you trying to achieve?
I am trying to use BeforeSuite and AfterSuite hooks

#### What do you get instead?
Could not include object Step Definition from ../step_definitions/hooks.js from module 'C:\Projects\Aura-Core\aura-accelerate-seed\step_definitions\hooks.js'
BeforeSuite is not a function
TypeError: BeforeSuite is not a function
    at Object.<anonymous> (C:\Projects\Aura-Core\aura-accelerate-seed\step_definitions\hooks.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadSupportObject (C:\Projects\Aura-Core\aura-accelerate-seed\node_modules\codeceptjs\lib\container.js:338:17)
    at loadGherkinSteps (C:\Projects\Aura-Core\aura-accelerate-seed\node_modules\codeceptjs\lib\container.js:317:7)
    at Function.create (C:\Projects\Aura-Core\aura-accelerate-seed\node_modules\codeceptjs\lib\container.js:48:25)
> Provide console output if related. Use `--verbose` mode for more details.

> Provide test source code if related
![image](https://user-images.githubusercontent.com/92156668/177276191-ec0a0a71-e6a7-4a0c-a122-dc73e49b7518.png)
```

### Details

* CodeceptJS version: 3.3.3
* NodeJS Version: 16.5
* Operating System: Windows
* playwright
* Configuration file:

```js
# paste config here
```

**Comment by dyaroman** [comment]
@viveklandeWK I think you should try to use `_beforeSuite` and `_afterSuite` instead of `BeforeSuite` and `AfterSuite` according to documentation of [hooks](https://codecept.io/helpers/#configuration)

**Comment by viveklandeWK** [comment]
Hi @dyaroman, Thanks, will give a try

**Comment by VivekLande** [comment]
Hi @dyaroman, browser session not available in _beforeSuite(), do we have any way to make it available?

**Comment by DavertMik** [comment]
Following documentation before creating an issue is highly recommended
Thanks
