### ISSUE TITLE
npx codeceptjs run --override '{ "helpers": {"WebDriver": {"browser": "chrome"}}}'  not working

### ISSUE THREAD

**Issue by rebajz** [Codeception/CodeceptJS#3362]
i use codecept.conf.js
and when i run:
npx codeceptjs run --override '{ "helpers": {"WebDriver": {"browser": "chrome"}}}'

i got this message:
Unexpected token h in JSON at position 2

SyntaxError: 
    at JSON.parse (<anonymous>)
    at module.exports (C:\_git\typescriptCodeceptJs\node_modules\codeceptjs\lib\command\run.js:16:33)
    at Command.<anonymous> (C:\_git\typescriptCodeceptJs\node_modules\codeceptjs\bin\codecept.js:9:11)
    at Command.listener (C:\_git\typescriptCodeceptJs\node_modules\commander\index.js:315:8)
    at Command.emit (node:events:527:28)
    at Command.parseArgs (C:\_git\typescriptCodeceptJs\node_modules\commander\index.js:651:12)
    at Command.parse (C:\_git\typescriptCodeceptJs\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\_git\typescriptCodeceptJs\node_modules\codeceptjs\bin\codecept.js:203:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

**Comment by DavertMik** [comment]
Can't confirm:

```
➜ npx codeceptjs run --override '{ "helpers": {"Playwright": {"browser": "chromium"}}}'
context
CodeceptJS v3.3.4 #StandWithUkraine
Using test root "/home/davert/projects/codeceptjs/examples"

...
```

probably the issue is in your terminal as it incorrectly escapes quotes

**Comment by rebajz** [comment]
i use win 10.
started from IDE webstorm or from CMD

I try to escape " by \\:
npx codeceptjs run --override '{\\"helpers\\": {\\"TestCafe\\": {\\"myOwnParam\\": \\"dynamic text by override\\"}}}'

this working.

It might be a good idea to add this tip to the documentation somewhere...
