### ISSUE TITLE
I.waitForElement is broken 

### ISSUE THREAD

**Issue by cjoshmartin** [Codeception/CodeceptJS#338]
#### What are you trying to achieve?
Hello I was trying to wait for an element to appear. 
#### What do you get instead?
But when I use I.waitForElement the program will pause (longer then I set) then will timeout, no matter what element I am looking for. I used I.waitForText to get around this problem.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
CodeceptJS Demonstration --
   [1] Starting recording promises
   Emitted | suite.before
 > Nightmare._beforeSuite
   [1] Queued | hook Nightmare._beforeSuite()
 test some forms
   [2] Starting recording promises
   Emitted | test.before
 > Nightmare._before
   [2] Queued | hook Nightmare._before()
   Emitted | test.start ([object Object])
   [2] Queued | amOnPage: https://www.thecn.com/login
   [2] Queued | waitForElement: .submit, 2
   [2] Queued | fillField: #username, joshmartin5001@gmail.com
   [2] Queued | fillField: #password, charles24
   [2] Queued | click: .submit
   [2] Queued | wait: 10
   [2] Queued | seeInCurrentUrl: /user
   [2] Queued | see: @CM379
   [2] Queued | finish test
   Emitted | step.before (I am on page "https://www.thecn.com/login")
 • I am on page "https://www.thecn.com/login"
   Emitted | step.after (I am on page "https://www.thecn.com/login")
 > [URL] https://www.thecn.com/login
 > [Code] 200
 > [Headers] {"cache-control":["no-cache"],"connection":["keep-alive"],"content-encoding":["gzip"],"content-type":["text/html; charset=UTF-8"],"date":["Wed, 21 Dec 2016 20:06:27 GMT"],"expires":["Wed, 21 Dec 2016 20:06:26 GMT"],"last-modified":["Fri, 09 Dec 2016 10:04:48 GMT"],"server":["nginx"],"strict-transport-security":["max-age=16070400"],"transfer-encoding":["chunked"],"vary":["Accept-Encoding"],"x-content-type-options":["nosniff"],"x-xss-protection":["1; mode=block"]}
   Emitted | step.before (I wait for element ".submit", 2)
 • I wait for element ".submit", 2
   Emitted | step.after (I wait for element ".submit", 2)
   [2] Error | Error: .wait() timed out after 30000msec
   [2] Starting <teardown> session
   Emitted | test.failed ([object Object])
 > Nightmare._failed
   [2] <teardown> Queued | hook Nightmare._failed()
   [2] <teardown> Queued | () => done(err)
   [2] <teardown> Stopping recording promises
 > Screenshot is saving to /Users/Josh/Documents/Cyberlab/testtest/logs/test_some_forms.failed.png
 ✖ FAILED in 34664ms

   Emitted | test.after
 > Nightmare._after
   [2] <teardown> Queued | hook Nightmare._after()
   [3] Starting recording promises
   Emitted | suite.after
 > Nightmare._afterSuite
   [3] Queued | hook Nightmare._afterSuite()

-- FAILURES:

  1) CodeceptJS Demonstration: test some forms:
     .wait() timed out after 30000msec
  
  Scenario Steps:
  
  - I.waitForElement(".submit", 2) at Test.Scenario (tests/test1.js:7:6)
  - I.amOnPage("https://www.thecn.com/login") at Test.Scenario (tests/test1.js:6:6)
  
  Error: .wait() timed out after 30000msec
      at Timeout._onTimeout (/usr/local/lib/node_modules/nightmare/lib/actions.js:453:10)


  FAIL  | 0 passed, 1 failed   // 35s
   Emitted | global.result ([object Object])

```
> Provide test source code if related

```javascript
Feature('CodeceptJS Demonstration');

Scenario('test some forms', (I) => {
   I.amOnPage('https://www.thecn.com/login');
   I.waitForElement('.submit', 2);
  // I.waitForText("Don't have an account?",5);
   I.fillField('#username','joshmartin5001@gmail.com');
   I.fillField('#password','charles24');
   I.click('.submit');
   I.wait(10);
   I.seeInCurrentUrl('/user');
   I.see('@CM379');
  //pause(); creates a break point to start testing commands
});

```
### Details

* CodeceptJS version: v0.4.12
* NodeJS Version: v6.6.0
* Operating System: macOS Sierra (v.10.12.1)
* Nightmare version: v2.9.0
* Configuration file:

```js
{
  "tests": "./tests/*.js",
  "timeout": 10000,
  "output": "./logs",
  "helpers": {
    "Nightmare": {
     "show": true,
     "dock":true
   }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {},
  "name": "testtest"
}

```

**Comment by DavertMik** [comment]
Yep, I discovered that by myself by writing a test to this method. And yes, I have it fixed :+1: 
Fix should be available in 0.4.13
