### ISSUE TITLE
testCafe resizeWindow causes a TestCafe error and fails tests

### ISSUE THREAD

**Issue by malsaid000** [Codeception/CodeceptJS#3388]
#### What are you trying to achieve?
Trying to Change TestCafe Window Size using either Config or inside a test

#### What do you get instead?
<img width="1182" alt="2022-08-12_11-27-38" src="https://user-images.githubusercontent.com/88502469/184388224-16c6df31-0c79-4438-8b26-c75489244ba6.png">

```bash
TestCafe Error: {"filename":"/Users/malsaid/Documents/codeCeptJS/node_modules/codeceptjs/lib/helper/TestCafe.js","lineNum":345,"callsiteFrameIdx":5,"stackFrames":[{},{},{},{},{},{},{},{},{}],"isV8Frames":true} {"code":"E55","isTestCafeError":true,"callsite":{"filename":"/Users/malsaid/Documents/codeCeptJS/node_modules/codeceptjs/lib/helper/TestCafe.js","lineNum":345,"callsiteFrameIdx":5,"stackFrames":[{},{},{},{},{},{},{},{},{}],"isV8Frames":true},"id":"yuBHn4P"}
      at mapError (node_modules/codeceptjs/lib/helper/testcafe/testcafe-utils.js:32:9)
      at invokeCallback (node_modules/pinkie/index.js:60:12)
      at Array.forEach (<anonymous>)
  
  Scenario Steps:
  - I.resizeWindow(2200, 1500) at Test.<anonymous> (./src/Desktop/AddressTesting/NewAddress/AMS21notZip5_Edit_test.js:31:49)

```
Fails at First Step in the Scenario which is:
```js
await I.resizeWindow(2200, 1500);
```

### Details

* CodeceptJS version: v3.3.4
* NodeJS Version:  16.15.1
* Operating System: macOS Monterey
* testcafe version: v1.20.1
* Configuration file: 

```js
		TestCafe: {
			url: 'url',
			waitForTimeout: 5000,
			getPageTimeout: 20000,
			show: true,
			browser: process.env.BROWSER,
			//windowSize: '2200x1500', // If this is uncommented and the resizeWindow step is removed I get the same result
		},
```

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
