### ISSUE TITLE
npx codeceptjs init fails

### ISSUE THREAD

**Issue by mirao** [Codeception/CodeceptJS#3516]
#### What are you trying to achieve?
This should work
```bash
$ npm init -y
$ npx codeceptjs init
```
#### What do you get instead?

If you answer **"Y"** on the question "Do you plan to write tests in TypeScript?" and keep default for other questions, the wizard fails with the error `export const config: CodeceptJS.MainConfig = { ... SyntaxError: Unexpected token 'export'` :x: 
```
$ npm init -y
$ npx codeceptjs init
Welcome to CodeceptJS initialization tool
  It will prepare and configure a test environment for you

 Useful links:

  👉 How to start testing ASAP: https://codecept.io/quickstart/#init
  👉 How to select helper: https://codecept.io/basics/#architecture
  👉 TypeScript setup: https://codecept.io/typescript/#getting-started

Installing to /home/mirao/tmp
? Do you plan to write tests in TypeScript? Yes
? Where are your tests located? ./*_test.ts
? What helpers do you want to use? Playwright
? Where should logs, screenshots, and reports to be stored? ./output
? Would you prefer to use promise-based typings for all I.* commands? http://bit.ly/3XIMq6n No
? Do you want to enable localization for tests? http://bit.ly/3GNUBbh English (no localization)
Configure helpers...
? [Playwright] Base url of site to be tested http://localhost
? [Playwright] Show browser window Yes
? [Playwright] Browser in which testing will be performed. Possible options: chromium, firefox, webkit or electron chromium

Steps file created at ./steps_file.ts
Config created at /home/mirao/tmp/codecept.conf.ts
Directory for temporary output files created at './output'
CodeceptJS should be installed locally
Installing packages:  typescript, ts-node, @types/node, codeceptjs

added 297 packages, and audited 298 packages in 12s

59 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
ts-node package is required to parse codecept.conf.ts config correctly
/home/mirao/tmp/codecept.conf.ts:1
export const config: CodeceptJS.MainConfig = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at loadConfigFile (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/config.js:156:26)
    at Function.load (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/config.js:95:16)
    at module.exports.getConfig (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/command/utils.js:15:33)
```

If you answer **"N"** on the question "Do you plan to write tests in TypeScript?" and keep default for other questions, you get an error `Couldn't generate type definitions ... Error: Could not load helper Playwright from module './helper/Playwright'` :x:  

```
$ npm init -y
$ npx codeceptjs init

  Welcome to CodeceptJS initialization tool
  It will prepare and configure a test environment for you

 Useful links:

  👉 How to start testing ASAP: https://codecept.io/quickstart/#init
  👉 How to select helper: https://codecept.io/basics/#architecture
  👉 TypeScript setup: https://codecept.io/typescript/#getting-started

Installing to /home/mirao/tmp
? Do you plan to write tests in TypeScript? No
? Where are your tests located? ./*_test.js
? What helpers do you want to use? Playwright
? Where should logs, screenshots, and reports to be stored? ./output
? Do you want to enable localization for tests? http://bit.ly/3GNUBbh English (no localization)
Configure helpers...
? [Playwright] Base url of site to be tested http://localhost
? [Playwright] Show browser window Yes
? [Playwright] Browser in which testing will be performed. Possible options: chromium, firefox, webkit or electron chromium

Steps file created at ./steps_file.js
Config created at /home/mirao/tmp/codecept.conf.js
Directory for temporary output files created at './output'
Intellisense enabled in /home/mirao/tmp/jsconfig.json
CodeceptJS should be installed locally
Installing packages:  codeceptjs

added 279 packages, and audited 280 packages in 4s

59 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
WARNING: CodeceptJS is not installed locally. It is recommended to switch to local installation
Couldn't generate type definitions
Error: Could not load helper Playwright from module './helper/Playwright':
Required modules are not installed.

RUN: [sudo] npm install -g playwright@^1.18
Error: Required modules are not installed.

RUN: [sudo] npm install -g playwright@^1.18
    at createHelpers (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/container.js:179:17)
    at Function.create (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/container.js:44:25)
    at Codecept.init (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/codecept.js:56:15)
    at module.exports (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/command/definitions.js:131:12)
    at finish (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/command/init.js:293:9)
    at /home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/command/init.js:325:7
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Skipping type definitions...
To get auto-completion support, please generate type definitions: npx codeceptjs def

 Almost ready... Next step:
Creating a new test...
----------------------
? Feature which is being tested (ex: account, login, etc) My
? Filename of a test My_test.js
WARNING: CodeceptJS is not installed locally. It is recommended to switch to local installation
(node:338550) UnhandledPromiseRejectionWarning: Error: Could not load helper Playwright from module './helper/Playwright':
Required modules are not installed.

RUN: [sudo] npm install -g playwright@^1.18
Error: Required modules are not installed.

RUN: [sudo] npm install -g playwright@^1.18
    at createHelpers (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/container.js:179:17)
    at Function.create (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/container.js:44:25)
    at /home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/command/generate.js:60:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at createHelpers (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/container.js:184:13)
    at Function.create (/home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/container.js:44:25)
    at /home/mirao/.npm/_npx/9bb2bd9fa07a0a83/node_modules/codeceptjs/lib/command/generate.js:60:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:338550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:338550) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Note that generating of test fails in 3.3.7 (it's most likely the same issue as #3512), it works well in 3.3.6

### Details

* CodeceptJS version: 3.3.6/3.3.7 (both versions are affected)
* NodeJS Version: 14.21.1
* Operating System: Ubuntu 22.04

**Comment by mirao** [comment]
Well, it's not a bug.

I forgot that it's needed to install codeceptjs and playwright before `npx codeceptjs init`.

- Either this way `npx create-codeceptjs .` (as you can see on https://codecept.io/quickstart/) 
- Or this way: `npm i codeceptjs playwright`

Then everything works as expected.
