### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'debug')

### ISSUE THREAD

**Issue by aprilahijriyan** [Codeception/CodeceptJS#3567]
#### What are you trying to achieve?

I want to create a test script, using the `npx codeceptjs generate:test` command

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
➜  mobile-tests git:(main) ✗ npx codeceptjs generate:test
Creating a new test...
----------------------
? Feature which is being tested (ex: account, login, etc) Order
? Filename of a test Order.js

Could not load helper Appium from module './helper/Appium':
Cannot read properties of undefined (reading 'debug')
TypeError: Cannot read properties of undefined (reading 'debug')
    at Appium.debug (/Users/u/Workspace/company/mobile-tests/node_modules/@codeceptjs/helper/helper.js:185:12)
    at new WebDriver (/Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/lib/helper/WebDriver.js:392:12)
    at new Appium (/Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/lib/helper/Appium.js:135:5)
    at createHelpers (/Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/lib/container.js:182:29)
    at Container.create (/Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/lib/container.js:44:25)
    at /Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/lib/command/generate.js:60:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/bin/codecept.js:9:5)

Error: 
    at createHelpers (/Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/lib/container.js:184:13)
    at Container.create (/Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/lib/container.js:44:25)
    at /Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/lib/command/generate.js:60:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/Users/u/Workspace/company/mobile-tests/node_modules/codeceptjs/bin/codecept.js:9:5)
(node:12460) Warning: Accessing non-existent property 'output' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

```

### Details

* CodeceptJS version: 3.3.7
* NodeJS Version: 18.5.0
* Operating System: Mac
* webdriverio: 8.1.3
* Configuration file:

```js
# codecept.conf.js
const { setHeadlessWhen, setCommonPlugins } = require('@codeceptjs/configure');
// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

// enable all common plugins https://github.com/codeceptjs/configure#setcommonplugins
setCommonPlugins();

/** @type {CodeceptJS.MainConfig} */
exports.config = {
  tests: './tests/*.js',
  output: './output',
  helpers: {
    Appium: {
      app: 'http://localhost',
      platform: 'Android',
      device: 'emulator'
    }
  },
  include: {
    I: './steps_file.js'
  },
  name: 'mobile-tests'
}
```

Is there any solution for this ?
I followed the guide from https://codecept.io/mobile/#setting-up

**Comment by Hristovski** [comment]
Since I updated NodeJS from 16.x to 18.x, I changed the "localhost" to "0.0.0.0" as appium server and it works now...

**Comment by DavertMik** [comment]
Can't say what was that 
I suspect something with the nodejs version
if someone could reproduce or tell the cause of issue, please reopen it
