### ISSUE TITLE
Listing commands on 0.4.13 throws exception

### ISSUE THREAD

**Issue by justinwiley** [Codeception/CodeceptJS#357]
#### What are you trying to achieve?
Listing codeceptjs commands using `codeceptjs list`

#### What do you get instead?

An unhandled exception "TypeError: done is not a function".  The same goes for generating a new codeceptjs test via:

`codeceptjs gt foobar`

> Provide console output if related. Use `--verbose` mode for more details.

```bash
~/tmp ∴ node -v
v6.9.1
~/tmp ∴ npm install -g codeceptjs@0.4.13
/Users/j/.nvm/versions/node/v6.9.1/bin/codeceptjs -> /Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/bin/codecept.js
/Users/j/.nvm/versions/node/v6.9.1/lib
└── codeceptjs@0.4.13 
~/tmp ∴ cd ..
~ ∴ rm -rf tmp
~ ∴ mkdir tmp
~ ∴ cd tmp
~/tmp ∴ codeceptjs init

  Welcome to CodeceptJS initialization tool
  It will prepare and configure a test environment for you

Installing to /Users/j/tmp
? Where are your tests located? ./*_test.js
? What helpers do you want to use? 
? Where should logs, screenshots, and reports to be stored? ./output
? Would you like to extend I object with custom steps? Yes
? Do you want to choose localization for tests? English (no localization)
? Where would you like to place custom steps? ./steps_file.js
Steps file created at /Users/j/tmp/steps_file.js
Config created at /Users/j/tmp/codecept.json
Directory for temporary output files created at `_output`
Almost done! Create your first test by executing `codeceptjs gt` (generate test) command
~/tmp ∴ codeceptjs list
List of test actions: -- 
PS: Actions are retrieved from enabled helpers. 
Implement custom actions in your helper classes.
/Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/hooks.js:22
  done();
  ^

TypeError: done is not a function
    at module.exports (/Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/hooks.js:22:3)
    at Codecept.teardown (/Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/codecept.js:59:5)
    at /Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/command/list.js:48:14
    at module.exports (/Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/hooks.js:22:3)
    at Codecept.bootstrap (/Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/codecept.js:54:5)
    at Codecept.init (/Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/codecept.js:49:10)
    at Command.module.exports (/Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/command/list.js:16:12)
    at Command.listener (/Users/j/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)

```
### Details

* CodeceptJS version: 0.4.13
* NodeJS Version: 6.9.1
* Operating System: mac sierra
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {},
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "tmp"
}

```js
# paste suite config here
```

**Comment by cvega** [comment]
+1, I'm seeing the same behavior with nearly identical details on my end (Node 7 being the difference). The issue is compounded when you have custom steps:

```
vega@work[~/dev/example][casey ?] $ node_modules/.bin/codeceptjs list
[11:31:52] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
/Users/cvega/dev/example/node_modules/codeceptjs/lib/container.js:49
      throw new Error(`Could not include object ${name} from module '${module}'\n${err.message}`);
      ^

Error: Could not include object I from module '/Users/cvega/dev/example/steps_file.js'
Unexpected identifier
    at createSupportObjects (/Users/cvega/dev/example/node_modules/codeceptjs/lib/container.js:49:13)
    at Object.create (/Users/cvega/dev/example/node_modules/codeceptjs/lib/container.js:104:15)
    at Codecept.init (/Users/cvega/dev/example/node_modules/codeceptjs/lib/codecept.js:43:15)
    at Command.module.exports (/Users/cvega/dev/example/node_modules/codeceptjs/lib/command/list.js:16:12)
    at Command.listener (/Users/cvega/dev/example/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/cvega/dev/example/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/cvega/dev/example/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/cvega/dev/example/node_modules/codeceptjs/bin/codecept.js:90:9)```

**Comment by DavertMik** [comment]
Thanks for the report. I fixed it and added few tests to check this cases
