### ISSUE TITLE
Catching JS exceptions in nightmare to fail test

### ISSUE THREAD

**Issue by cjhille** [Codeception/CodeceptJS#358]
I intended to extend the nightmare helper to catch JS exceptions in the browser in order to fail the current test. Since nightmare allows to listen for javascript exceptions [(doc here)](https://github.com/segmentio/nightmare#onpage-functiontypeerror-message-stack) I figured it shouldn't be to hard by doing something similar to this:

```js
class NightmareHelper extends Helper {
   _before() {
      let browser = this.helpers['Nightmare'].browser;
      browser.on('page', (type, message, stack) => { 
         console.log(`${message}\n ${stack}`);
         throw new Error('JS Exception in Browser!');
      });
   }
}
```

This code does return the browser stacktrace, but unfortunately it also kills the entire process instead of failing the current test. Usually throwing an error within a test just fails the current test. 

Is it at all possible to do this with a custom helper or could this eventually be supported by codeception itself?

CodeceptJS version: 0.4.13

**Comment by DavertMik** [comment]
I am trying to reproduce the error but test fails, not crashes. 
It would be good if you provide complete stack trace of failure by running test with `--verbose` flag.
I can assume that the problem is within the order of loading helpers. 

```js
 let browser = this.helpers['Nightmare'].browser;
```

this should be executed only when browser is instantiated, this means that NightmareHelper should be started after Nightmare itself. Please check that your config have the same order:

```json
    "Nightmare": {
      "url": "http://127.0.0.1:8000",
      "show": true
    },
    "NightmareHelper": {
      "require": "./nightmare_helper.js"
    }
```

**Comment by DavertMik** [comment]
Sorry, checked once again. The test actually failed. Need to review it better

**Comment by cjhille** [comment]
Hey Michael, thank you for taking an interest :) Unfortunately the order of helpers isn't the issue.
Here are more details for the test (don't mind the weird directory structure):

config via javascript codecept.conf.js
```javascript
exports.config = {
  name: "helpertest",
  tests: "./tests/codeceptjs/*/*_test.js",
  output: "./tests/codeceptjs/output",
  helpers: {
    Nightmare: {
      url:  "", //override below
      show: (process.profile=="show")?true:false,
    },
    NightmareHelper: {
      require: "./tests/codeceptjs/nightmare_helper.js"
    }
  },
  mocha: {}
}
```
helper_test.js
```javascript
Feature('helper test suite');
Scenario('test1', (I) => {
	I.setupHelperForJSError()
	I.amOnPage('http://localhost:8001/tests/codeceptjs/tmp/index.html'); //page with JS error
	I.wait(1);
	I.see('Dynamic');
});
Scenario('test2', (I) => {
	I.amOnPage('http://example.org/');
	I.see('Example');
});
Scenario('test3', (I) => {
	I.amOnPage('http://example.org/');
	I.see('Example');
});
```
nightmare_helper.js
```javascript
'use strict';
class NightmareHelper extends Helper {
  setupHelperForJSError() {
    // <- throwing an error here is fine
    let browser = this.helpers['Nightmare'].browser;
    browser.on('page', (type, message, stack) => { 
       console.log(`${message}\n ${stack}`);
       throw new Error('JS Exception in Browser!'); // <- here not so much
    });
  } 
}
module.exports = NightmareHelper;
```

### And the very verbose result.
Please note: All 3 tests would usually pass if it wasn't for the helper. What's weird is, that the failing first test also makes the second test fail and the third one is back to normal.
Also the part of the log that states:
``` 
TypeError: Cannot read property 'render' of undefined
    at Object.setupMenu (http://localhost:8001/tests/codeceptjs/tmp/app.js:2568:14)
    at Object.epaper_viewer_Core [as __class__] (http://localhost:8001/tests/codeceptjs/tmp/app.js:2377:7)
    at Function.epaper_viewer_Boot.main (http://localhost:8001/tests/codeceptjs/tmp/app.js:2231:2)
    at http://localhost:8001/tests/codeceptjs/tmp/app.js:8630:20
    at http://localhost:8001/tests/codeceptjs/tmp/app.js:8631:3
```
 is the JS exception from the client, which get's logged.
```javascript
helper test suite --
   [1] Starting recording promises
   Emitted | suite.before
 > Nightmare._beforeSuite
   [1] Queued | hook Nightmare._beforeSuite()
 > NightmareHelper._beforeSuite
   [1] Queued | hook NightmareHelper._beforeSuite()
 test1
   [2] Starting recording promises
   Emitted | test.before
 > Nightmare._before
   [2] Queued | hook Nightmare._before()
 > NightmareHelper._before
   [2] Queued | hook NightmareHelper._before()
   Emitted | test.start ([object Object])
   [2] Queued | setupHelperForJSError:
   [2] Queued | amOnPage: http://localhost:8001/tests/codeceptjs/tmp/index.html
   [2] Queued | wait: 1
   [2] Queued | see: Dynamic
   [2] Queued | fire test.passed
   [2] Queued | finish test
   Emitted | step.before (I setup helper for j s error )
 * I setup helper for j s error
   Emitted | step.after (I setup helper for j s error )
   Emitted | step.before (I am on page "http://localhost:8001/tests/codeceptjs/tmp/index.html")
 * I am on page "http://localhost:8001/tests/codeceptjs/tmp/index.html"
   Emitted | step.after (I am on page "http://localhost:8001/tests/codeceptjs/tmp/index.html")
 > log: linkintern.png
Uncaught TypeError: Cannot read property 'render' of undefined
 TypeError: Cannot read property 'render' of undefined
    at Object.setupMenu (http://localhost:8001/tests/codeceptjs/tmp/app.js:2568:14)
    at Object.epaper_viewer_Core [as __class__] (http://localhost:8001/tests/codeceptjs/tmp/app.js:2377:7)
    at Function.epaper_viewer_Boot.main (http://localhost:8001/tests/codeceptjs/tmp/app.js:2231:2)
    at http://localhost:8001/tests/codeceptjs/tmp/app.js:8630:20
    at http://localhost:8001/tests/codeceptjs/tmp/app.js:8631:3
 × FAILED in undefinedms

   Emitted | test.after
 > Nightmare._after
   [2] Queued | hook Nightmare._after()
 > NightmareHelper._after
   [2] Queued | hook NightmareHelper._after()
 > log: justTesting
 test2
   [3] Starting recording promises
   Emitted | test.before
 > Nightmare._before
   [3] Queued | hook Nightmare._before()
 > NightmareHelper._before
   [3] Queued | hook NightmareHelper._before()
   Emitted | test.start ([object Object])
   [3] Queued | amOnPage: http://example.org/
   [3] Queued | see: Example
   [3] Queued | fire test.passed
   [3] Queued | finish test
   Emitted | step.before (I am on page "http://example.org/")
 * I am on page "http://example.org/"
   Emitted | step.after (I am on page "http://example.org/")
 > [URL] http://localhost:8001/tests/codeceptjs/tmp/index.html
 > [Code] 200
 > [Headers] {"cache-control":["max-age=0"],"connection":["keep-alive"],"content-length":["117074"],"content-type":["text/html; charset=utf-8"],"date":["Tue, 10 Jan 2017 21:02:17 GMT"],"etag":["W/\"1c952-1597e5e5d11\""],"last-modified":["Sun, 08 Jan 2017 13:57:10 GMT"]}
   Emitted | step.before (I wait 1)
 * I wait 1
   Emitted | step.after (I wait 1)
   Emitted | step.before (I see "Dynamic")
 * I see "Dynamic"
   Emitted | step.after (I see "Dynamic")
                                                                                                             [3] Error | Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
   [3] Starting <teardown> session
   Emitted | test.failed ([object Object])
 > Nightmare._failed
   [3] <teardown> Queued | hook Nightmare._failed()
 > NightmareHelper._failed
   [3] <teardown> Queued | hook NightmareHelper._failed()
   [3] <teardown> Queued | () => done(err)
   [3] <teardown> Stopping recording promises
 > Screenshot is saving to C:\Users\Christo\dev.local\tgd-html5-epaper-player.git@develop\tests\codeceptjs\output\test2.failed.png
 × FAILED in 31454ms

   Emitted | test.after
 > Nightmare._after
   [3] <teardown> Queued | hook Nightmare._after()
 > NightmareHelper._after
   [3] <teardown> Queued | hook NightmareHelper._after()
 test3
   [4] Starting recording promises
   Emitted | test.before
 > Nightmare._before
   [4] Queued | hook Nightmare._before()
 > NightmareHelper._before
   [4] Queued | hook NightmareHelper._before()
   Emitted | test.start ([object Object])
   [4] Queued | amOnPage: http://example.org/
   [4] Queued | see: Example
   [4] Queued | fire test.passed
   [4] Queued | finish test
   Emitted | step.before (I am on page "http://example.org/")
 * I am on page "http://example.org/"
   Emitted | step.after (I am on page "http://example.org/")
 > [URL] http://example.org/
 > [Code] 200
 > [Headers] {"cache-control":["max-age=604800"],"content-encoding":["gzip"],"content-length":["606"],"content-type":["text/html"],"date":["Tue, 10 Jan 2017 21:02:53 GMT"],"etag":["\"359670651+gzip\""],"expires":["Tue, 17 Jan 2017 21:02:53 GMT"],"last-modified":["Fri, 09 Aug 2013 23:54:35 GMT"],"server":["ECS (iad/182A)"],"vary":["Accept-Encoding"],"x-cache":["HIT"],"x-ec-custom-error":["1"]}
   Emitted | step.before (I see "Example")
 * I see "Example"
   Emitted | step.after (I see "Example")
   Emitted | test.passed ([object Object])
 √ OK in 1764ms

   Emitted | test.after
 > Nightmare._after
   [4] Queued | hook Nightmare._after()
 > NightmareHelper._after
   [4] Queued | hook NightmareHelper._after()
   [5] Starting recording promises
   Emitted | suite.after
 > Nightmare._afterSuite
   [5] Queued | hook Nightmare._afterSuite()
 > NightmareHelper._afterSuite
   [5] Queued | hook NightmareHelper._afterSuite()

-- FAILURES:

  1) helper test suite: test1:
     Uncaught Error: JS Exception in Browser!
      at EventEmitter.browser.on (tests\codeceptjs\nightmare_helper.js:11:14)
      at ChildProcess.<anonymous> (node_modules\nightmare\lib\ipc.js:49:10)
      at process.nextTick (internal/child_process.js:744:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) helper test suite: test2:
     Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?

  Scenario Steps:

  - I.see("Dynamic") at Test.Scenario (tests\codeceptjs\01_acceptance\helper_test.js:8:4)
  - I.wait(1) at Test.Scenario (tests\codeceptjs\01_acceptance\helper_test.js:7:4)
  - I.amOnPage("http://example.org/") at Test.Scenario (tests\codeceptjs\01_acceptance\helper_test.js:13:4)

  Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
      at Timeout._onTimeout (node_modules\nightmare\lib\actions.js:509:10)


  FAIL  | 1 passed, 2 failed   // 35s
   Emitted | global.result ([object Object])
```

**Comment by DavertMik** [comment]
Thanks. I worked on this part today and here is the summary of my work.

Unfortunately, this code won't work:
```js
    browser.on('page', (type, message, stack) => { 
       console.log(`${message}\n ${stack}`);
       throw new Error('JS Exception in Browser!'); // <- here not so much
    });
```
Looks like this callback is executed in another process so `throw` can't be catched by CodeceptJS. Fortunately we can log an error and throw error after. 
This code worked for me:

```js
class NightmareHelper extends Helper {

  // before/after hooks
   _before() {
      this.err = null;
      let browser = this.helpers['Nightmare'].browser;
      browser.on('page', (type, message, stack) => { 
         this.err = `JS Exception in Browser: ${message} ${stack}`;
      });
   }

  _after() {
    if (this.err) {
      console.log('erroring....');
      throw new Error(this.err);
    }
    this.err = null;
  }
}

module.exports = NightmareHelper;
```

It fails only in the very end of a test (`_after`). I did some [improvements in hooks system](https://github.com/Codeception/CodeceptJS/pull/360) and it should be included in 0.4.14, so since next version you can stop test just on related step:

```js

class NightmareHelper extends Helper {

  // before/after hooks
   _before() {
      this.err = null;
      let browser = this.helpers['Nightmare'].browser;
      browser.on('page', (type, message, stack) => { 
         this.err = `JS Exception in Browser: ${message} ${stack}`;
      });
   }

  // works since 0.4.14
  _afterStep() {
    if (this.err) {
      console.log('erroring....');
      throw new Error(this.err);
    }
    this.err = null;
  }
}
```

So this should allow you to implement JS errors handling.

**Comment by cjhille** [comment]
Thank you for giving this so much effort. Good and bad news: 
The above example with _before and _after still doesn't work on setup (neither with 0.4.13 or 0.4.14), however I can confirm that the second example did work flawlessly (on the soon to be 0.4.14 code). Since it should be the preferred way to handle client exceptions after each step, I'd consider the issue solved. 
Thanks again.

**Comment by willcooley** [comment]
Yeah, apparently I'm having the same issue on this as well. The website provides an example on to create a helper for nightmare, and probably needs to be updated on the site if this is the path we go with. I'm having module instantistion problems when trying to extend nightmare to create new helpers.
