### ISSUE TITLE
ResembleHelper was compiled against a different Node.js version

### ISSUE THREAD

**Issue by openmindculture** [Codeception/CodeceptJS#3590]
After upgrading to CodeceptJS 3.4.0, the tests fail with an error message about a ResembleHelper version conflict.

#### What do you get instead?

```bash
Node.js v19.2.0

Could not load helper ResembleHelper from module 'codeceptjs-resemblehelper':
The module '/home/ingo/Code/ingo-steinke.de/node_modules/resemblejs/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Error: The module '/home/ingo/Code/ingo-steinke.de/node_modules/resemblejs/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1302:18)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ingo/Code/ingo-steinke.de/node_modules/resemblejs/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)

Error: 
    at createHelpers (/home/ingo/Code/ingo-steinke.de/node_modules/codeceptjs/lib/container.js:184:13)
    at Container.create (/home/ingo/Code/ingo-steinke.de/node_modules/codeceptjs/lib/container.js:44:25)
    at Codecept.init (/home/ingo/Code/ingo-steinke.de/node_modules/codeceptjs/lib/codecept.js:56:15)
    at module.exports (/home/ingo/Code/ingo-steinke.de/node_modules/codeceptjs/lib/command/run.js:28:14)
    at Command.<anonymous> (/home/ingo/Code/ingo-steinke.de/node_modules/codeceptjs/bin/codecept.js:9:11)
    at Command.listener (/home/ingo/Code/ingo-steinke.de/node_modules/codeceptjs/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:513:28)
    at Command.parseArgs (/home/ingo/Code/ingo-steinke.de/node_modules/codeceptjs/node_modules/commander/index.js:651:12)
    at Command.parse (/home/ingo/Code/ingo-steinke.de/node_modules/codeceptjs/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/ingo/Code/ingo-steinke.de/node_modules/codeceptjs/bin/codecept.js:240:9)
```

The suggested `npm rebuild` did not help, same error message afterwards.

### Details

* CodeceptJS version: 3.4.0
* NodeJS Version: v19.2.0
* Operating System: GNU/Linux 5.15.0-10058-tuxedo x86_64 Ubuntu 22.04.1 LTS
* Configuration file:

```js
module.exports = {
  tests: './codecept/*_test.js',
  output: './codecept/output',
  helpers: {
    Puppeteer: {
      url: '',
      show: true,
      windowSize: '1200x900'
    },
    "ResembleHelper" : {
      "require": "codeceptjs-resemblehelper",
      "screenshotFolder" : "./codecept/output/",
      "baseFolder": "./codecept/screenshots/base/",
      "diffFolder": "./codecept/screenshots/diff/"
    }
  },
  include: {
    I: './codecept/steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'ingo-steinke.de',
  plugins: {
    testomatio: {
      enabled: true,
      require: '@testomatio/reporter/lib/adapter/codecept',
      apiKey: process.env.TESTOMATIO,
    },
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}

```

**Comment by openmindculture** [comment]
Deleted `node_modules` and `package-lock.json`, and set the latest versions for CodeceptJS-related tools in `package.json`:

```
    "devDependencies": {
        "@codeceptjs/configure": "^0.10.0",
        "@codeceptjs/ui": "^0.5.0",
        "@testomatio/reporter": "^0.7.4",
        "codeceptjs": "^3.4.0",
```

Then run `npm install` again, and now my `npm run test` runs CodeceptJS again without any problem!
