### ISSUE TITLE
Could not create _test.ts file

### ISSUE THREAD

**Issue by zhigulin-n** [Codeception/CodeceptJS#3603]
I'm trying to create _test.ts file using the command
`npx codeceptjs gt`

But i get an error
```
Could not load helper ChaiWrapper from module 'codeceptjs-chai':
Helper is not defined
ReferenceError: Helper is not defined
    at Object.<anonymous> (/home/work/project/node_modules/codeceptjs-chai/index.js:15:27)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Object.require.extensions.<computed> [as .js] (/home/work/project/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at createHelpers (/home/work/project/node_modules/codeceptjs/lib/container.js:168:27)
    at Function.create (/home/work/project/node_modules/codeceptjs/lib/container.js:44:25)
```
`npm i codeceptjs-chai` doesn't help

My codecept.conf.ts:

```
import {
  setHeadlessWhen,
  setCommonPlugins
} from '@codeceptjs/configure';
// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);
const env = require('dotenv').config({
  path: '.env.test'
})

if (env.error && env.error.code === 'ENOENT') {
  throw new Error('Please, recreate env.test file')
}

const base_url = process.env.URL 
const currentBrowser = process.env.profile ?? 'chromium'; // 'firefox', 'webkit'

// enable all common plugins https://github.com/codeceptjs/configure#setcommonplugins
setCommonPlugins();

export const config: CodeceptJS.MainConfig = {
  tests: './tests/*_test.ts',
  output: './output',
  helpers: {
    ChaiWrapper: {
      require: "codeceptjs-chai"
    },
    Playwright: {
      url: base_url,
      show: true,
      browser: currentBrowser,
      waitForTimeout: 10000
    },
    REST: {
      endpoint: base_url,
    },
    JSONResponse: {},
    DbHelper: {
      "require": "codeceptjs-dbhelper"
    }
  },
  include: {
    I: "./common/custom_steps.ts",
  },
  plugins: {
    tryTo: {
      enabled: true
    }
  },
  allure: {
    enabled: true,
    outputDir: './output/allure/allure-results',
  },
  retryFailedStep: {
    enabled: true
  },
  pauseOnFail: {},
  name: 'test',
  fullPromiseBased: false
}
```

**Comment by zhigulin-n** [comment]
described in #3512 
closed
