### ISSUE TITLE
Using playwright helper to run test throw exception at the end of test

### ISSUE THREAD

**Issue by linjin-harvey** [Codeception/CodeceptJS#3624]
#### Throwing exception at the end of the test

```js
(node:52183) UnhandledPromiseRejectionWarning: TypeError: this.browser.disconnect is not a function
    at Playwright._stopBrowser (/Users/harveyl/git/bose-ui-automation/node_modules/codeceptjs/lib/helper/playwright.js:562:26)
    at Playwright._finishTest (/Users/harveyl/git/bose-ui-automation/node_modules/codeceptjs/lib/helper/playwright.js:360:62)
    at /Users/harveyl/git/bose-ui-automation/node_modules/codeceptjs/lib/listener/helpers.js:27:69
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:52183) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:52183) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Below is my playwright help configuration:
```js
let playwright = {
  url: "http://localhost",
  browser: 'chromium',
  chromium: {
    // args: [
    //   `--remote-allow-origins=*`
    // ],
    browserWSEndpoint: "ws://10.230.89.126:8083/wd/hub",
    wsEndpoint: "ws://10.230.89.126:8083/wd/hub"
  }
}
```
Below is the source code of playwright helper, seems the 'await this.browser.disconnect();' is not working as expected
```js
  async _stopBrowser() {
    this.withinLocator = null;
    this._setPage(null);
    this.context = null;
    popupStore.clear();

    if (this.isRemoteBrowser) {
      await this.browser.disconnect();
    } else {
      await this.browser.close();
    }
  }
```

**Comment by ghost** [comment]
according to https://github.com/codeceptjs/CodeceptJS/pull/2629

there is no reference for method `disconnect()` on Playwright's doc. 
You should be good if you are using codecept 3.x or above

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
