### ISSUE TITLE
Does not recognize Scenario Outline values when using gherkin in PT language

### ISSUE THREAD

**Issue by gguto** [Codeception/CodeceptJS#3635]
#### What are you trying to achieve?

I'm trying to use Scenario Outline written in gherkin in the PT language, passing values in the examples.

#### What do you get instead?

The executed scenario is not recognized as a Scenario Outline and the value passed in the string is the value written in the step.

Note: If you run the same .feature but with the EN language, it works normally.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
› <screenshotOnFail> Test failed, try to save a screenshot
output.js:238
› Screenshot has been saved to /Atualizar__1680543458.failed.png, size: 1845x500
output.js:238
  ✖ FAILED in 7541ms
output.js:238
   [2]  Starting recording promises
output.js:238
-- FAILURES:
output.js:238
  1) Suporte para credenciais utilizadas @Login @Credenciais
       Atualizar senha do usuário @Rodar:
     User with nick "<nick>" not found.
      at findCredentialOnCache (helpers/vault.helper.js:151:15)
      at Vaul.grabCredentialOnVault (helpers/vault.helper.js:92:31)
      at Step.run (node_modules/codeceptjs/lib/step.js:122:47)
      at /home/node_modules/codeceptjs/lib/actor.js:135:23
  
  Scenario Steps:
  - I.grabCredentialOnVault("<nick>") at Object.getVaultCredentialDataByNick (./rests/general/login.rest.js:31:24)
  - I.wait(1) at Object.getVaultCredentialDataByNick (./rests/general/login.rest.js:30:17)
  
```

> Provide test source code if related

```
#language: pt
@Login @Credenciais
Funcionalidade: Suporte para credenciais utilizadas nos testes automatizados

  @Rodar
  Esquema do Cenário: Atualizar senha do usuário
    Dado que estou logado via REST com o usuário "<nick>"
    Quando recuperar o número de dias para expirar a senha nos meus dados do auth via REST
    Então caso falte 10 dias ou menos altero as credenciais do usuário logado
    Exemplos:
      | nick                         |
      | User Test                |
```

```js
Given('que estou logado via REST com o usuário {string}', async (user) => {
    const userTest = await loginRest.getVaultCredentialDataByNick(user);
    context.rest.userLogged = userTest;
});
```

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: 18.12.1
* Operating System: Linux Ubuntu 22.04
* webdriverio

**Comment by vhgx** [comment]
I'm having the same issue here. Scenario Outline (PT) crashes in v3.4.1. The Examples I use are not being passed into the steps.

**Comment by jc85lima** [comment]
This issue still happens, I'm using version "3.5.6" and I can't use scenario outline with Portuguese.

**Comment by kobenguyent** [comment]
hi, I could be wrong here but so far the docs doesn't mention the translation works with Gherkin https://codecept.io/translation/#languages

Looks like the keywords you should use them in english

```
Feature: Faker examples

    Scenario Outline: Atualizar senha do usuário
        Given que estou logado via REST com o usuário "<customer>"
```

```
Faker examples --
    [1]  Starting recording promises
    Timeouts: 
  Atualizar senha do usuário {"product":"{{vehicle.vehicle}}","customer":"Dr. {{name.findName}}","price":"{{commerce.price}}","cashier":"cashier 2"}
   Given que estou logado via REST com o usuário "Dr. {{name.findName}}" ""
Dr. {{name.findName}}
  ✔ OK in 11ms

```

https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/interfaces/gherkin.js#L99
