### ISSUE TITLE
Semantic Locator doesn't consider the `within`

### ISSUE THREAD

**Issue by tsuemura** [Codeception/CodeceptJS#3646]
#### What are you trying to achieve?

According to [the document about within](https://codecept.io/basics/#within), every locator should be filtered by the first argument of `within`. However, as I experiment with the simple example, the Semantic Locator does not consider the element specified to `within`.

For instance, in the following example, the ` I.click("Reveal");` should click the element inside the `tr` element with the text `Paul`. But it clicks the first element matched to the text `Reveal` instead. Then, the test will be failed.

```js
Feature('within');

Scenario('can select an element within the element', ({ I }) => {
  I.amOnPage(
    "https://tsuemura.github.io/codeceptjs-within-issue-reproduction/"
  );
  // If you specify locate('tr').withText('Paul')
  // as the first argument of the within,
  // semantic locators should find an element within the element.
  within(locate("tr").withText("Paul"), () => {
    I.click("Reveal");
    I.see("Paul is also a good man");
  });
});
```

You can see the full code here: https://github.com/tsuemura/codeceptjs-within-issue-reproduction

#### What do you get instead?

```bash
$ npx codeceptjs run --verbose
creating output directory: /Users/takuyasuemura/ghq/github.com/tsuemura/codeceptjs-within-issue-reproduction/output
CodeceptJS v3.3.7 #StandWithUkraine
Using test root "/Users/takuyasuemura/ghq/github.com/tsuemura/codeceptjs-within-issue-reproduction"
Helpers: Playwright
Plugins: screenshotOnFail, tryTo, retryTo, eachElement

within --
    [1]  Starting recording promises
    Timeouts: 
 › [Session] Starting singleton browser session
  can select an element within the element
    I am on page "https://tsuemura.github.io/codeceptjs-within-issue-reproduction/"
    Within "{"type":"xpath","output":null,"strict":true,"locator":{"xpath":".//tr[contains(., 'Paul')]"},"value":".//tr[contains(., 'Paul')]"}" 
      I click "Reveal"
      I see "Paul is also a good man"
    [1] <within> Error | Error
    [1] <within> Error | Error
    [1] <within> Error | Error
    [1] <teardown> Stopping recording promises
  › <screenshotOnFail> Test failed, try to save a screenshot
  › Screenshot is saving to /Users/takuyasuemura/ghq/github.com/tsuemura/codeceptjs-within-issue-reproduction/output/can_select_an_element_within_the_element.failed.png
  ✖ FAILED in 622ms

    [2]  Starting recording promises

-- FAILURES:

  1) within
       can select an element within the element:

      expected web application to include "Paul is also a good man"
      + expected - actual

      -Paul     Reveal
      +Paul is also a good man
      
  
  
  Scenario Steps:
  - I.see("Paul is also a good man") at ./within_test.js:12:7
  - I.click("Reveal") at ./within_test.js:11:7
  - I.amOnPage("https://tsuemura.github.io/codeceptjs-within-issue-reproduction/") at Test.<anonymous> (./within_test.js:4:5)
  
  Artifacts:
  - screenshot: /Users/takuyasuemura/ghq/github.com/tsuemura/codeceptjs-within-issue-reproduction/output/can_select_an_element_within_the_element.failed.png


  FAIL  | 0 passed, 1 failed   // 2s
```

> Provide test source code if related

```js
Feature('within');

Scenario('can select an element within the element', ({ I }) => {
  I.amOnPage(
    "https://tsuemura.github.io/codeceptjs-within-issue-reproduction/"
  );
  // If you specify locate('tr').withText('Paul')
  // as the first argument of the within,
  // semantic locators should find an element within the element.
  within(locate("tr").withText("Paul"), () => {
    I.click("Reveal");
    I.see("Paul is also a good man");
  });
});

```

### Details

* CodeceptJS version: 3.3.7
* NodeJS Version: v14.17.6
* Operating System: MacOS Ventura 13.3.1 (22E261)
* Playwright version: 1.30.0
* Configuration file:

```js
const { setHeadlessWhen, setCommonPlugins } = require('@codeceptjs/configure');
// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

// enable all common plugins https://github.com/codeceptjs/configure#setcommonplugins
setCommonPlugins();

/** @type {CodeceptJS.MainConfig} */
exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    Playwright: {
      url: 'http://localhost',
      show: true,
      browser: 'chromium'
    }
  },
  include: {
    I: './steps_file.js'
  },
  name: 'codeceptjs-within-issue-reproduction'
}
```

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
