### ISSUE TITLE
How to extend the appium helper?

### ISSUE THREAD

**Issue by otoniel-isidoro** [Codeception/CodeceptJS#3649]
#### What are you trying to achieve?
I want to extend the Appium helper like:
```typescript
class AppiumExtended extends CodeceptJS.Appium {
```

#### What do you get instead?
```bash
npx codeceptjs run -c config/codecept.conf.appium2.android.emu.staging.ts

Could not load helper AppiumExtended from module '/Users/otonielisidoro/Projects/xxxxx/xxx-app/e2e/helpers/AppiumExtendedHelper.ts':
CodeceptJS is not defined
ReferenceError: CodeceptJS is not defined
    at Object.<anonymous> (/Users/otonielisidoro/Projects/xxxxx/xxx-app/e2e/helpers/AppiumExtendedHelper.ts:6:30)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at createHelpers (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/codeceptjs/lib/container.js:168:27)

Error: 
    at createHelpers (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/codeceptjs/lib/container.js:184:13)
    at Function.create (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/codeceptjs/lib/container.js:44:25)
    at Codecept.init (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/codeceptjs/lib/codecept.js:56:15)
    at module.exports (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/codeceptjs/lib/command/run.js:28:14)
    at Command.<anonymous> (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/codeceptjs/bin/codecept.js:9:11)
    at Command.listener (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:513:28)
    at Command.parseArgs (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/otonielisidoro/Projects/xxxxx/xxx-app/node_modules/codeceptjs/bin/codecept.js:240:9)
``` 

### Details

* CodeceptJS version: 3.4.1
* NodeJS Version: 16.17.1
* Operating System: Mac OSX Ventura 13.3.1
* Appium 2
* Configuration file:

```js
const appiumConfig = {
  platform: 'android',
  desiredCapabilities: {
    'appium:app': '',
    'appium:platformVersion': '12.0',
    'appium:deviceName': 'Android Emulator',
    'appium:automationName': 'Appium',
    'appium:autoAcceptAlerts': 'true',
    'appium:autoGrantPermissions': 'true',
  },
};

const appiumExtendedConfig = {
  require: '../helpers/AppiumExtendedHelper.ts',
  ...appiumConfig,
};

export const commonConfig = {
  tests: '../**/*.test.ts',
  output: '../output',
  include: {
    I: '../fixtures/steps_file.ts',
    welcomeScreen: '../screens/WelcomeScreen.ts',
    signInScreen: '../screens/SignInScreen.ts',
    otpScreen: '../screens/OTPScreen.ts',
    homeScreen: '../screens/HomeScreen.ts',
  },
  name: 'xxx-app',
  require: ['ts-node/register'],
  fullPromiseBased: false,
};

export const codeceptAppiumConfig = {
  ...commonConfig,
  helpers: {
    AppiumExtended: appiumExtendedConfig,
    // Appium: appiumConfig,
  },
};

```

**Comment by StanislavGrishaev** [comment]
Did you try to extend helper like this ? According to the [manual](https://codecept.io/helpers/#development), the syntax should be like this ( not `CodeceptJS.Appium` after `extends` )

```
const Helper = require('@codeceptjs/helper');

class AppiumExtended extends Helper {

  // before/after hooks
  _before() {
    // remove if not used
  }

  _after() {
    // remove if not used
  }

  // add custom methods here
  // If you need to access other helpers
  // use: this.helpers['helperName']

}
module.exports = AppiumExtended;
```

**Comment by otoniel-isidoro** [comment]
Yes, I had to do it that way but I wanted to extend the Appium helper directly so I could just add new methods to it instead of proxying some methods to the original Appium helper methods. Also, in this way extending from Helper I also had to configure both helpers the Appium helper itself and the AppiumExtended helper that I've created.
Example: 
```typescript
class AppiumExtended extends Helper {

 // [...]
 
  async runOnAppium(fn: CallableFunction) {
    recorder.session.start('Appium-only actions');
    fn();
    recorder.add('restore from Appium session', () =>
      recorder.session.restore('Appium-only actions')
    );
    return recorder.promise();
  }

  async runOnDetox(fn: CallableFunction) {
    return fn;
  }

  async waitForElementVisible(locator: any, sec = 5) {
    return this.helpers['Appium'].waitForVisible(this.parseLocator(locator), sec);
  }
```

Config:
```typescript
import { commonConfig } from './codecept.conf.common';

const appiumConfig = {
  platform: 'android',
  desiredCapabilities: {
    'appium:app': '',
    'appium:platformVersion': '12.0',
    'appium:deviceName': 'Android Emulator',
    'appium:automationName': 'Appium',
    'appium:autoAcceptAlerts': 'true',
    'appium:autoGrantPermissions': 'true',
    'appium:idleTimeout': '10',
  },
};

const appiumExtendedConfig = {
  require: '../helpers/AppiumExtendedHelper.ts',
  ...appiumConfig,
};

export const codeceptAppiumConfig = {
  ...commonConfig,
  helpers: {
    AppiumExtended: appiumExtendedConfig,
    Appium: appiumConfig,
  },
};
```

**Comment by kobenguyent** [comment]
I'm not sure how to do it outside the core helpers as looking into codebase, the Appium is currently extending from Webdriver. 

https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/Appium.js

**Comment by otoniel-isidoro** [comment]
The way I've implemented by proxying some methods to the original Appium helper methods is working fine so closing this issue.
