### ISSUE TITLE
`heal` plugin not working in v3.5.2

### ISSUE THREAD

**Issue by jancorvus** [Codeception/CodeceptJS#3766]
#### What are you trying to achieve?

To use the self-healing https://codecept.io/ai/#self-healing-tests with the plugin `heal`
Instead of `I.click('Sign In')` which is working, I edit it to `I.click('Sign InZZZ')` to see how the plugin can heal it

#### What do you get instead?

I got an error not about that the click on the text _'Sign InZZZ'_ has failed, but that the text expected after logging in has not appeared.

If I edit ./node_modules/codeceptjs/lib/plugin/heal.js, commenting out `try/catch` in `tryToHeal` function, I can see the error

```bash
I click "Sign InZZZ"
 » Running OpenAI to heal I.click("Sign InZZZ") step
 » Received 2 suggestions from OpenAI
 » <screenshotOnFail> Test failed, try to save a screenshot
 » Screenshot is saving to xxxxx.png
  × FAILED in 22336ms

-- FAILURES:

  1) Login 
       User logins with unregistered email :
     I is not defined
      at eval (eval at tryToHeal (node_modules\codeceptjs\lib\plugin\heal.js:159:15), <anonymous>:1:1)
      at tryToHeal (node_modules\codeceptjs\lib\plugin\heal.js:159:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Details

* CodeceptJS version: 3.5.2
* NodeJS Version: 18.16.0
* Operating System: Windows
* Playwright: 
* Configuration file:

```js
{
  ...
  plugins: {
    ...
    tryTo: {
      enabled: true,
    },
    retryTo: {
      enabled: true,
    },
    heal: {
      enabled: !!process.env.OPENAI_API_KEY,
      healLimit: 2,
      healSteps: [
        'click',
        'fillField',
        'appendField',
        'selectOption',
        'attachFile',
        'checkOption',
        'uncheckOption',
        'doubleClick',
      ],
    },
  },
  ai: {
    model: 'gpt-3.5-turbo-16k',
    temperature: 0.1,
    html: {
      maxLength: 50000,
      simplify: true,
      minify: true,
      interactiveElements: [
        'a', 'input', 'button', 'select', 'textarea', 'option',
        'm-button', 'm-text-input', 'm-number-input', 'm-text-area',
        'm-form-multiselect', 'm-options-container', 'm-form-checkbox',
        'm-form-date-picker',
        'm-v2-form-field', 'm-v2-radio-button', 'm-v2-checkbox'
      ],
      textElements: ['label', 'h1', 'h2', 'm-v2-form-label'],
      allowedAttrs: [
        'id', 'for', 'class', 'name', 'type', 'value', 'tabindex', 'label', 'role',
        'data-test',
      ],
      allowedRoles: ['button', 'checkbox', 'search', 'textbox', 'tab'],
    },
  },
  ...
}
```

### My personal quick fix

I introduce the 3rd parameter `I` in `async function tryToHeal(failedStep, err, I)` and pass helper to it in 
```js
event.dispatcher.on(event.step.before, () => {
  ...
  await tryToHeal(step, err, helper);
  ...
}
```
and have the test passed
```bash
  OK  | 1 passed   // 36s

===================
Self-Healing Report:
1 step(s) were healed by AI

Suggested changes:

1. To fix User logins with unregistered email 
Replace the failed code with:
- I.click("Sign InZZZ")
+ I.click('button.primary.mynd-theme-external.stretched');
at Actor.loginApplicantSite (.\helpers\I.extend\login.ts:21:10)

======= Tests finished =======
```

**Comment by DavertMik** [comment]
It is quite fun but I know what caused that issue
Indeed `I` should have been defined somewhere, but because `I` was not used by anything except eval, I assume eslint considered this line as useless and dropped it.

It's easy fix. Should be done in 3.5.4
