### ISSUE TITLE
(Playwright) Not waiting until timeout if element is not found on click

### ISSUE THREAD

**Issue by carine-bonnafous** [Codeception/CodeceptJS#3769]
#### What are you trying to achieve?

Click on an element, but wait using auto-waiting Playwright feature if the element is not loaded yet

#### What do you get instead?

Test fails immediately if the element is not found using click method of Playwright helper
If I use `usePlaywrightTo` to do the click with Playwright it works as expected : the test fails after the `timeout` defined in the configuration is reached

> Provide console output if related. Use `--verbose` mode for more details.

```bash
$ npx codeceptjs run --verbose
CodeceptJS v3.5.2 #StandWithUkraine
Using test root "/home/pxl/src/test"
Helpers: Playwright
Plugins:

click --
    [1]  Starting recording promises
    Timeouts:
 › [Session] Starting singleton browser session
  Click on not found element
    I click ".whatever"
    [1] Error | Error: Clickable element ".whatever" was not found by text|CSS|XPath
    [1] Error | Error: Clickable element ".whatever" was not found by text|CSS|XPath
    [1] <teardown> Stopping recording promises
  ✖ FAILED in 35ms

    [2]  Starting recording promises
  Click on not found element using Playwright API
    I use playwright to "click on non existing element", async ({ page }) => {
        await page.click('.whatever');
    }
    [2] Error | TimeoutError: page.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('.whatever')
============================================================
    [2] Error | TimeoutError: page.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('.whatever')
============================================================
    [2] <teardown> Stopping recording promises
  ✖ FAILED in 10016ms

    [3]  Starting recording promises

-- FAILURES:

  1) click
       Click on not found element:
     Clickable element ".whatever" was not found by text|CSS|XPath
      at new ElementNotFound (node_modules/codeceptjs/lib/helper/errors/ElementNotFound.js:14:11)
      at assertElementExists (node_modules/codeceptjs/lib/helper/Playwright.js:2961:11)
      at Playwright.proceedClick (node_modules/codeceptjs/lib/helper/Playwright.js:2732:5)

  Scenario Steps:
  - I.click(".whatever") at Test.<anonymous> (./click_test.ts:4:7)


  2) click
       Click on not found element using Playwright API:
     page.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('.whatever')
============================================================
      at /home/pxl/src/test/click_test.ts:9:20
      at Playwright._useTo (node_modules/@codeceptjs/helper/helper.js:164:12)
      at Playwright.usePlaywrightTo (node_modules/codeceptjs/lib/helper/Playwright.js:606:17)
      at Step.run (node_modules/codeceptjs/lib/step.js:122:47)
      at /home/pxl/src/test/node_modules/codeceptjs/lib/actor.js:135:23

  Scenario Steps:
  - I.usePlaywrightTo("click on non existing element", fn()) at Test.<anonymous> (./click_test.ts:8:7)



  FAIL  | 0 passed, 2 failed   // 10s

```

> Provide test source code if related

```js
Feature('click');

Scenario('Click on not found element',  ({ I }) => {
    I.click('.whatever')
});

Scenario('Click on not found element using Playwright API',  ({ I }) => {
    I.usePlaywrightTo('click on non existing element', async ({ page }) => {
        await page.click('.whatever')
      });
});
```

### Details

* CodeceptJS version: 3.5.2
* NodeJS Version: v18.16.0
* Operating System: Ubuntu 22.04.2 LTS
* Playwright 1.36.1
* Configuration file:

```js
export const config: CodeceptJS.MainConfig = {
  tests: './*_test.ts',
  output: './output',
  helpers: {
    Playwright: {
      browser: 'chromium',
      url: 'https://www.google.com/',
      show: false,
      timeout: 10_000
    }
  },
  include: {
    I: './steps_file'
  },
  name: 'test',
  plugins: {
    screenshotOnFail: {
      enabled: false
    }
 }
}
```

**Comment by pablopaul** [comment]
@carine-bonnafous do you have the same result when you use Playwright standalone, without CodeceptJS as wrapper? 
Can we access the application under test to reproduce and debug?

**Comment by kobenguyent** [comment]
looks like it is discouraged to use **page.click()** -> https://playwright.dev/docs/api/class-page#page-click. So I believe the current behaviour is what CodeceptJS is doing.
