### ISSUE TITLE
scrollTo() is not working with playwright webkit

### ISSUE THREAD

**Issue by VivekLande** [Codeception/CodeceptJS#3790]
#### What are you trying to achieve?
I am trying to scroll to the element using Playwright on webkit browser

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
    I scroll to element Select 1
    [2] Retrying... Attempt #2
    [2] Retrying... Attempt #3
    [2] Retrying... Attempt #4
    [2] Retrying... Attempt #5
    [2] Retrying... Attempt #6
    [2] Error | TimeoutError: elementHandle.scrollIntoViewIfNeeded: Timeout 5000ms exceeded.
=========================== logs ===========================
  waiting for element to be  and stable
============================================================
    [2] Error | TimeoutError: elementHandle.scrollIntoViewIfNeeded: Timeout 5000ms exceeded.
=========================== logs ===========================
  waiting for element to be  and stable
============================================================
    [2] <teardown> Stopping recording promises
 » Screenshot is saving to C:\Projects\Aura-Core\aura-accelerate\tests\e2e\output\screenshots\Validation_Ste_o_the__Select_1__21691135796957.png
Step "I scroll to element Select 1" failed: elementHandle.scrollIntoViewIfNeeded: Timeout 5000ms exceeded.
=========================== logs ===========================
  waiting for element to be  and stable
============================================================ 
 elementHandle.scrollIntoViewIfNeeded: Timeout 5000ms exceeded.
=========================== logs ===========================
  waiting for element to be  and stable
============================================================
    at PlaywrightHelper.scrollTo (C:\Projects\Aura-Core\aura-accelerate\node_modules\codeceptjs\lib\helper\Playwright.js:1063:20)
    at async PlaywrightHelper.scrollToElement (C:\Projects\Aura-Core\aura-accelerate\lib\helpers\playwrightHelper.js:385:9)
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.5.3+
* NodeJS Version: 18+
* Operating System: windows 10
* Playwright: 1.36.2+

**Comment by kobenguyent** [comment]
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.
