### ISSUE TITLE
within()/I.switchTo(): Context of a 2nd iframe is used though I switched to 1st iframe

### ISSUE THREAD

**Issue by mirao** [Codeception/CodeceptJS#3894]
It works as expected in 3.5.3 and doesn't work in 3.5.5, so it seems to be a regression in 3.5.5 (or maybe in 3.5.4)

#### What are you trying to achieve?
The test should fail, because no such text `"The iframe element"` is in the 1st iframe on the page (it's a Google ads iframe). Note the text `"The iframe element"` is in the 2nd iframe instead (in the element "h1").

This is an output from the test run in CodeceptJS 3.5.3 (expected output) :heavy_check_mark: :
```
My --
 › [Session] Starting singleton browser session
  test something
    I am on page "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    I click "#accept-choices"
    I wait 5
    I switch to {xpath: (.//iframe)[position()=1]}
    I see text equals "The iframe element", "h1"
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /home/mirao/workspace/codeceptjs/tests/my/output/test_something.failed.png
  ✖ FAILED in 6583ms


-- FAILURES:

  1) My
       test something:
     Element "h1" was not found by text|CSS|XPath
      at new ElementNotFound (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs@3.5.3_it6hatrurk4vupt6qhkwl6ubhy/node_modules/codeceptjs/lib/helper/errors/ElementNotFound.js:14:11)
      at assertElementExists (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs@3.5.3_it6hatrurk4vupt6qhkwl6ubhy/node_modules/codeceptjs/lib/helper/Playwright.js:3291:11)
      at Playwright.proceedSee (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs@3.5.3_it6hatrurk4vupt6qhkwl6ubhy/node_modules/codeceptjs/lib/helper/Playwright.js:3128:5)
  
  Scenario Steps:
  - I.seeTextEquals("The iframe element", "h1") at Test.<anonymous> (./My_test.ts:10:7)
  - I.switchTo({xpath: (.//iframe)[position()=1]}) at Test.<anonymous> (./My_test.ts:9:7)
  - I.wait(5) at Test.<anonymous> (./My_test.ts:8:7)
  - I.click("#accept-choices") at Test.<anonymous> (./My_test.ts:7:7)
  - I.amOnPage("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe") at Test.<anonymous> (./My_test.ts:4:7)
  
  Artifacts:
  - screenshot: /home/mirao/workspace/codeceptjs/tests/my/output/test_something.failed.png


  FAIL  | 0 passed, 1 failed   // 7s
Run with --verbose flag to see complete NodeJS stacktrace
```

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

The test in 3.5.5 passes :lady_beetle:  :
```bash
My --
 › [Session] Starting singleton browser session
  test something
    I am on page "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    I click "#accept-choices"
    I wait 5
    I switch to {xpath: (.//iframe)[position()=1]}
    I see text equals "The iframe element", "h1"
  ✔ OK in 6426ms
```
I tried it also with the fix https://github.com/codeceptjs/CodeceptJS/pull/3892, but I'm getting the same result.
> Provide test source code if related

```ts
Feature("My");

Scenario("test something", ({ I }) => {
    I.amOnPage(
        "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    );
    I.click("#accept-choices");
    I.wait(5); // Wait for Google ads to be loaded
    I.switchTo(locate("iframe").at(1)); // Switch to the iframe with Google ads
    I.seeTextEquals("The iframe element", "h1");
});
```

### Details

* CodeceptJS version: 3.5.5
* NodeJS Version: 18.15
* Operating System: Ubuntu 22.04
* Playwright 1.37.1
* Configuration file:

```ts
export const config: CodeceptJS.MainConfig = {
    tests: "./*_test.ts",
    output: "./output",
    helpers: {
        Playwright: {
            browser: "chromium",
            url: "http://localhost",
            show: true,
        },
    },
    name: "my",
};
```

**Comment by kobenguyent** [comment]
I guess you haven't switched to another frame, have you? My test works as expected.

![Screenshot 2023-09-26 at 13 16 26](https://github.com/codeceptjs/CodeceptJS/assets/7845001/40ddbabf-579d-4d5e-b60a-a125139b032f)


```
My --
    [1]  Starting recording promises
    Timeouts: 
 › [Session] Starting singleton browser session
  test something
    I am on page "http://127.0.0.1:8000/iframe"
    › [Browser:Error] Failed to load resource: the server responded with a status of 404 (Not Found)
    I switch to {xpath: (.//iframe)[position()=1]}
    I see text equals "Iframe test", "h1"
    [1] Retrying... Attempt #2
    [1] Retrying... Attempt #3
    [1] Retrying... Attempt #4
    [1] Retrying... Attempt #5
    [1] Retrying... Attempt #6
    [1] Error | Error: expected element h1 "Iframe test" to equal "Information"
    [1] Error | Error: expected element h1 "Iframe test" to equal "Information"
    [1] <teardown> Stopping recording promises
```

**Comment by mirao** [comment]
@kobenguyent Try it with multiple iframes (at least two) on a page, please.

In my production visual test I hit this issue: I have two iframes on a page. When the test switches to the 2nd frame and makes a screenshot of an element in the 2nd iframe, a screenshot is done, but it is a screenshot of the element with the same name from the 1st iframe :lady_beetle: .
The issue I reported in #3894 is opposite (but I think it has the same reason as mine "production" issue) - if you switch to the 1st iframe (successfully) on that public page and try to work with elements in it, test actually works with elements in the 2nd iframe.

**Comment by kobenguyent** [comment]
I see @mirao will check!
