### ISSUE TITLE
With Update to 3.5.4 version of codecept Js getting error and execution is not happening

### ISSUE THREAD

**Issue by rohanraviyadav1** [Codeception/CodeceptJS#3965]
### Discussed in https://github.com/codeceptjs/CodeceptJS/discussions/3964

<div type='discussions-op-text'>

<sup>Originally posted by **rohanraviyadav1** October 31, 2023</sup>
Error :
**matcher.locator(...).all is not a function**

This error is not coming till 3.5.3 , What change I need to do to resolve this error. Can someone help

</div>

**Comment by rohanraviyadav1** [comment]
matcher.locator(...).all is not a function
      at findElements (/Users/xyz/projectName/node_modules/codeceptjs/lib/helper/Playwright.js:3252:55)
      at Playwright._locate (/Users/xyz/projectName/node_modules/codeceptjs/lib/helper/Playwright.js:1158:12)
      at async Playwright.findFields (/Users/xyz/projectName/node_modules/codeceptjs/lib/helper/Playwright.js:3400:13)

**Comment by kobenguyent** [comment]
Please try with latest version to see if your issue persists. If so, feel free to reopen this and would be nice to have a sample repo to reproduce your issue.
