### ISSUE TITLE
Re-opening #3987: Ignoring cancel characters with playwright on string locators

### ISSUE THREAD

**Issue by jancorvus** [Codeception/CodeceptJS#4037]
Reopened https://github.com/codeceptjs/CodeceptJS/issues/3987

#### What are you trying to achieve?
To wait for a text containing a single quote `'`

#### What do you get instead?
An error
```
locator.isVisible: Unexpected token "s" while parsing selector ":has-text('Were you able to resolve the resident's issue?') >> nth=0"
      at Playwright.waitForText (node_modules\codeceptjs\lib\helper\Playwright.js:2584:79)
```

> Provide console output if related. Use `--verbose` mode for more details.

```bash
On pageVendorWorkOrder: confirm no materials have been purchased 
      I wait for text "Did you purchase any materials for this work order?", 20
      I click "No", ".m-modal-dialog-container"
    I wait for text "Were you able to resolve the resident's issue?", 1
  × FAILED in 55351ms


-- FAILURES:

  1) Working with work order as Mynd Tech @rtm-team @vendor-portal @severity-critical
       Completing work order when resident was not home:
     locator.isVisible: Unexpected token "s" while parsing selector ":has-text('Were you able to resolve the resident's issue?') >> nth=0"
      at Playwright.waitForText (node_modules\codeceptjs\lib\helper\Playwright.js:2584:79)
```

> Provide test source code if related

```js
// tried in different ways
I.waitForText("Were you able to resolve the resident's issue?", 10);
I.waitForText(`Were you able to resolve the resident's issue?`, 10);
I.waitForText('Were you able to resolve the resident\'s issue?', 10);
```

### Details

* CodeceptJS version: v3.5.9-beta.1
* NodeJS Version: v18.16.0
* Operating System: Windows & MacOS
* Playwright

**Comment by velimd** [comment]
Also experiencing the same issue in v3.5.8
