### ISSUE TITLE
Migrate CodeceptJS to ESM (Top-level await)

### ISSUE THREAD

**Issue by danielhelen** [Codeception/CodeceptJS#4185]
#### What are you trying to achieve?
I need to use top-level `await` to retrieve config from AWS and other APIs but CodeceptJS seems completely incompatible with ES modules. Top-level await is simply not possible in CommonJS. Are there any plans to support ES modules?

#### What do you get instead?

If you set `"type": "module"` in `package.json` you get this error:

```bash
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/REDACTED/config/codecept.conf.js from /Users/REDACTED/node_modules/codeceptjs/lib/config.js not supported.
Instead change the require of codecept.conf.js in /Users/REDACTED/node_modules/codeceptjs/lib/config.js to a dynamic import() which is available in all CommonJS modules.
    at loadConfigFile (/Users/REDACTED/node_modules/codeceptjs/lib/config.js:160:26)
    at Config.load (/Users/REDACTED/node_modules/codeceptjs/lib/config.js:91:14)
    at module.exports.getConfig (/Users/REDACTED/node_modules/codeceptjs/lib/command/utils.js:14:33)
    at module.exports (/Users/REDACTED/node_modules/codeceptjs/lib/command/run.js:18:16)
    at Command.<anonymous> (/Users/REDACTED/node_modules/codeceptjs/bin/codecept.js:9:11)
```

### Details

* CodeceptJS version: 3.5.13-beta.3
* NodeJS Version: v20.10.0
* Operating System: MacOS Ventura

**Comment by DavertMik** [comment]
@danielhelen at this moment this means to rewrite CodeceptJS completely and I don't think we have enough resources to handle this task.

**Comment by DavertMik** [comment]
Actually we can try this codemod, which can make migration faster 

https://github.com/azu/commonjs-to-es-module-codemod

**Comment by DavertMik** [comment]
#4229 We are working on it!

**Comment by kaashan** [comment]
Do we have any target date for https://github.com/codeceptjs/CodeceptJS/pull/4229 ?

**Comment by myrepojuly** [comment]
Hi @kobenguyent @DavertMik ... any ETA for this?

**Comment by mirao** [comment]
I noticed that currently isn't possible to mix `import` and `require` in custom helpers if you try to run tests with Bun instead of NodeJS. See also https://bun.com/blog/bun-v1.0.14#errors-for-unsupported-esm-commonjs-features
Tested with TypeScript helpers.

I know that Bun isn't supported in CodeceptJS (BTW if you don't use own helper or complex stuff then CodeceptJS with Bun works well). I guess that migration of CodeceptJS to ESM could help to solve the compatibility with Bun as well.
