### ISSUE TITLE
quickstart instructions crash

### ISSUE THREAD

**Issue by bionicles** [Codeception/CodeceptJS#4272]
#### What are you trying to achieve?
run the "quick start"
#### What do you get instead?
I get the impression the codecept.js quickstart guide is not being tested with codeceptjs, because it tells you to run demos before running projects, and then running the demos crashes

a wall of red errors
> Provide console output if related. Use `--verbose` mode for more details.
```
        let todos: any = await I.grabTextFrom('.todo-list li')
                 ^
```
```bash
> yarn run codeceptjs:demo
yarn run v1.22.19
$ codeceptjs run --steps -c node_modules/@codeceptjs/examples
creating output directory: www/e2e/node_modules/@codeceptjs/examples/output

Could not include object Step Definition from ./todomvc-tests/step-definitions/create-todos.steps.ts from module 'www/e2e/node_modules/@codeceptjs/examples/todomvc-tests/step-definitions/create-todos.steps.ts'
Could not include object TodosPage from module 'www/e2e/node_modules/@codeceptjs/examples/todomvc-tests/pages/todos.page.ts'
Unexpected token ':'
www/e2e/node_modules/@codeceptjs/examples/todomvc-tests/pages/todos.page.ts:85
        let todos: any = await I.grabTextFrom('.todo-list li')
                 ^

SyntaxError: Unexpected token ':'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1197:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Object.require.extensions.<computed> [as .ts] (www/e2e/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at loadSupportObject (www/e2e/node_modules/codeceptjs/lib/container.js:348:17)
Error: Could not include object TodosPage from module /www/e2e/node_modules/@codeceptjs/examples/todomvc-tests/pages/todos.page.ts'
Unexpected token ':'
www/e2e/node_modules/@codeceptjs/examples/todomvc-tests/pages/todos.page.ts:85
        let todos: any = await I.grabTextFrom('.todo-list li')
                 ^

SyntaxError: Unexpected token ':'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1197:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Object.require.extensions.<computed> [as .ts] (www/e2e/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at loadSupportObject (www/e2e/node_modules/codeceptjs/lib/container.js:348:17)
    at loadSupportObject (www/e2e/node_modules/codeceptjs/lib/container.js:395:11)
    at getSupportObject (www/e2e/node_modules/codeceptjs/lib/container.js:312:12)
    at lazyLoad (www/e2e/node_modules/codeceptjs/lib/container.js:222:18)
    at Object.get (www/e2e/node_modules/codeceptjs/lib/container.js:270:24)
    at Object.<anonymous> (www/e2e/node_modules/@codeceptjs/examples/todomvc-tests/step-definitions/create-todos.steps.ts:1:12)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Object.require.extensions.<computed> [as .ts] (www/e2e/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
```

> Provide test source code if related

```js
your code
```

a humble suggestion, if these demos require the project to be initialized and to use typescript, then moving those instructions above the instruction to run the demo, and just delete this "do you want typescript" option since we have no choice but to use it

![image](https://github.com/codeceptjs/CodeceptJS/assets/24532336/dd6f8b78-1c16-4736-9730-85174371c60a)

### Details

* CodeceptJS version: the one from npx
* NodeJS Version: the latest
* Operating System: ubuntu 22.04 on wsl
* puppeteer || webdriverio || testcafe version (if related) the default
* Configuration file: the default

```js
https://codecept.io/quickstart/
```

it's likely i didn't install some random npm ecosystem junk, but i have typescript installed and the problem persists, and a quickstart guide which leads you right into an error message is extremely bad advertising

**Comment by bionicles** [comment]
would using yarn be less likely to face these issues?
```
Error: npm install --save-dev --loglevel error typescript ts-node @types/node failed

Please install next packages manually:
npm i typescript ts-node @types/node --save-dev
```

```
> npm i typescript ts-node @types/node --save dev
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @codeceptjs/ui@1.1.1
npm ERR! Found: codeceptjs@3.5.15
npm ERR! node_modules/codeceptjs
npm ERR!   peer codeceptjs@">= 2.3.3" from @codeceptjs/configure@1.0.1
npm ERR!   node_modules/@codeceptjs/configure
npm ERR!     @codeceptjs/configure@"1.0.1" from codeceptjs@3.5.15
npm ERR!     dev @codeceptjs/configure@"^1.0.1" from the root project
npm ERR!   dev codeceptjs@"^3.5.15" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer codeceptjs@"3.5.14" from @codeceptjs/ui@1.1.1
npm ERR! node_modules/@codeceptjs/ui
npm ERR!   dev @codeceptjs/ui@"^1.1.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: codeceptjs@3.5.14
npm ERR! node_modules/codeceptjs
npm ERR!   peer codeceptjs@"3.5.14" from @codeceptjs/ui@1.1.1
npm ERR!   node_modules/@codeceptjs/ui
npm ERR!     dev @codeceptjs/ui@"^1.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /home/bion/.npm/_logs/2024-03-26T10_39_25_227Z-eresolve-report.txt
```

**Comment by bionicles** [comment]
i force installed the stuff, still doesn't work
force upgraded / audit fixed, same issue. 
i checked an old project and it does work, probably some new versions introduced breaking changes ? i just want codeceptjs to work
```
Error: Could not include object TodosPage from module '/home/bion/hax/REDACTED/www/e2e/node_modules/@codeceptjs/examples/todomvc-tests/pages/todos.page.ts'
Unexpected token ':'
/home/bion/hax/REDACTED/www/e2e/node_modules/@codeceptjs/examples/todomvc-tests/pages/todos.page.ts:85
        let todos: any = await I.grabTextFrom('.todo-list li')
                 ^
```
different project, working demo just loads nothing for todomvc and fails all the tests, cool. 
```
> npm run codeceptjs:demo:ui

> codecept_tests@1.0.0 codeceptjs:demo:ui
> codecept-ui --app  -c node_modules/@codeceptjs/examples


 ⚠️You have to build Vue application by `npm run build`
 ```
 sorry, maybe i'm spoiled by cargo but why is basic stuff in nodejs such a nightmare ? do i need to cd into node_modules/@codeceptjs/examples and build todomvc ? 
 
 all i want to do is verify this works. i can't believe we have a quickstart guide which leads directly into errors on the 2nd step! i really love codeceptjs or i wouldn't bother making this issue

**Comment by DavertMik** [comment]
@kobenguyent why do we have TypeScript in our examples?

**Comment by kobenguyent** [comment]
issue has been addressed! We introduced another examples in TS -> https://github.com/codeceptjs/examples-ts

```
> codeceptjs-tests@0.1.0 codeceptjs:demo
> codeceptjs run --steps -c node_modules/@codeceptjs/examples

creating output directory: /Users/t/Desktop/projects/node_modules/@codeceptjs/examples/output
CodeceptJS v3.5.15 #StandWithUkraine
Using test root "/Users/t/Desktop/projects/node_modules/@codeceptjs/examples"

Create Todos with BDD --
  Create a single todo item @bdd
   Given I have an empty todo list ""
   When I create a todo 123456 ""
   Then I see the new todo on my list ""
  ✔ OK in 3008ms

@first Create Todos @step:06 @smoke @story:12345 --
  Create a new todo item
    On TodosPage: goto 
      I am on page "https://todomvc.com/examples/react/dist/"
      I refresh page 
      I execute script () => sessionStorage.clear()
      I execute script () => console.error('Boom!')
      I wait for visible ".new-todo"
    I say "Given I have an empty todo list"
   Given I have an empty todo list
    I say "When I create a todo "foo""
   When I create a todo "foo"
    On TodosPage: enter todo "foo"
      I fill field ".new-todo", "foo"
      I press key "Enter"
      I wait 2
    I say "Then I see the new todo on my list"
   Then I see the new todo on my list
    On TodosPage: see number of todos 1
      I see number of visible elements ".todo-list li", 1
    I save screenshot "create-todo-item.png"
  ✔ OK in 2409ms

```

**Comment by DavertMik** [comment]
I think we can close this as @kobenguyent fixed it with updating examples
