### ISSUE TITLE
Could not load helper Nightmare from module './helper/Nightmare'

### ISSUE THREAD

**Issue by m1x0n** [Codeception/CodeceptJS#443]
#### What are you trying to achieve?
Hi @DavertMik , I'm trying to run tests with Nightmare (both nightmare and nightmare-upload have been installed globally):
```bash
codeceptjs run . --steps
```

#### What do you get instead?
Got following:
```bash
Could not load helper Nightmare from module './helper/Nightmare':
Required modules are not installed.

RUN: [sudo] npm install -g nightmare nightmare-upload
{}

Error: 
    at createHelpers (/usr/lib/node_modules/codeceptjs/lib/container.js:29:13)
    at Object.create (/usr/lib/node_modules/codeceptjs/lib/container.js:102:15)
    at Codecept.init (/usr/lib/node_modules/codeceptjs/lib/codecept.js:43:15)
    at Command.module.exports (/usr/lib/node_modules/codeceptjs/lib/command/run.js:23:14)
    at Command.listener (/usr/lib/node_modules/codeceptjs/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/lib/node_modules/codeceptjs/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/lib/node_modules/codeceptjs/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/lib/node_modules/codeceptjs/bin/codecept.js:90:9)
```

My test code is:

```js
Feature('Hellooworld');

Scenario('Login page loaded', (I) => {
  I.amOnPage('/');
  I.seeElement({name: 'password'});
});
```

### Details

* CodeceptJS version: 
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```json
{
  "tests": "./tests/e2e/*_test.js",
  "timeout": 20000,
  "output": "./tests/e2e/output",
  "helpers": {
    "Nightmare": {
      "url": "http://localhost:3000",
      "show": false 
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {},
  "name": "ui"
}
```

Any thoughts about it?
Thanks

**Comment by foodporn** [comment]
I met the same question after global installation.
I solved the problem by changing to local installation and edited the `codecept.json` as followed ：
```
"node_modules": {
    "Nightmare": {
      "url": "",
      "show": false,
      "restart": false
    }},
```
It works for me.

**Comment by adrianblynch** [comment]
I have the same issue.

Following the steps here: http://codenroll.it/acceptance-testing-with-codecept-js/

I have `nightmare` and `nightmare-upload` installed locally.

codecept.json:
```
{
  "tests": "./tests/*.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "url": "http://localhost:3000"
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {},
  "name": "myb-e2e"
}
```
package.json
```
{
  ...
  "scripts": {
    "test": "codeceptjs run --steps"
  },
  ...
  "devDependencies": {
    "codeceptjs": "^0.5.1",
    "nightmare": "^2.10.0",
    "nightmare-upload": "^0.1.1"
  }
}
```

Running `npm test` causes:

```
/project> npm test

> myb-e2e@1.0.0 test /project
> codeceptjs run --steps

Could not load helper Nightmare from module './helper/Nightmare':
Required modules are not installed.

RUN: npm install --save-dev nightmare nightmare-upload
{}

Error:
    at createHelpers (/project/node_modules/codeceptjs/lib/container.js:29:13)
    at Object.create (/project/node_modules/codeceptjs/lib/container.js:102:15)
    at Codecept.init (/project/node_modules/codeceptjs/lib/codecept.js:43:15)
    at Command.module.exports (/project/node_modules/codeceptjs/lib/command/run.js:23:14)
    at Command.listener (/project/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/project/node_modules/commander/index.js:615:12)
    at Command.parse (/project/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/project/node_modules/codeceptjs/bin/codecept.js:90:9)
```

I was about to install things globally but as stated above, that's an issue too.

**Comment by adrianblynch** [comment]
Now as I expand my sample test to:
```
Feature('Retrieve booking');

Scenario('test something', (I) => {
	I.amOnPage('http://localhost:3000');
});
```

It errors with:
```
08:45> npm test

> myb-e2e@1.0.0 test /project
> codeceptjs run --steps --verbose

CodeceptJS v0.5.1
Using test root "/project"

Retrieve booking --
   [1] Starting recording promises
   Emitted | suite.before
 test something
   [2] Starting recording promises
   Emitted | test.before
   Emitted | test.start ([object Object])
   [2] Queued | throw error TypeError: I.amOnPage is not a function
   [2] Queued | fire test.passed
   [2] Queued | finish test
   [2] Error | TypeError: I.amOnPage is not a function
   [2] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [2] <teardown> Queued | () => done(err)
   [2] <teardown> Stopping recording promises
 ✖ FAILED in 3ms

   Emitted | test.after
   [3] Starting recording promises
   Emitted | suite.after

-- FAILURES:

  1) Retrieve booking: test something:
     I.amOnPage is not a function
  ypeError: I.amOnPage is not a function
      at Test.Scenario (tests/retrieve_booking.js:5:4)
      at Context.test.fn (node_modules/codeceptjs/lib/scenario.js:29:24)


  FAIL  | 0 passed, 1 failed   // 13ms
   Emitted | global.result ([object Object])
npm ERR! Test failed.  See above for more details.
```

**Comment by Nekronek0** [comment]
I had the same issue (Could not find helper Nightmare). It turned out I ran `node_modules/codeceptjs` instead of `node_modules/codeceptjs-nightmare`

**Comment by reubenmiller** [comment]
This ticket is being closed due to inactivity. If this is still an active issue, then please reopen it, and we can revisit this.
