### ISSUE TITLE
multi-browser issue

### ISSUE THREAD

**Issue by joelgrimberg** [Codeception/CodeceptJS#481]
trying to configure the great multi-browser feature.
starting the script by: codeceptjs run-multiple basic
the weird thing is that I don't see why my multiple->basic array is breaking my config.

#### What do you get instead?
/Users/joel/code/production/belastingdienst.nl/test/acceptance/codecept.conf.js:32
        {browser: 'chrome', windowSize: 'maximize'},
                                                   ^
SyntaxError: Unexpected token ,
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports.getConfig (/Users/joel/.npm-packages/lib/node_modules/codeceptjs/lib/command/utils.js:26:31)

### Details

* CodeceptJS version: v0.6.0
* NodeJS Version: v7.9.0
* Operating System: MacOS Sierra
* WebDriverIO version: 4.6.2
* Configuration file:

```
exports.config = {
  "helpers": {
    "WebDriverIO": {
      // load variables from the environment and provide defaults
      "url": 'https://www.site.com',
      "browser" : process.profile || "phantomjs",
      "restart" : "false"
    }
  },
  "tests": "./testcases/*_test.js",
  "timeout": 120000,
  "output": "./output",
  "include": {
    "I": "./steps_file.js",
    "checkZoekenPage"   :   "./pages/checkZoekenPage.js",
    "checkMenuPage"     :   "./pages/checkmenuPage.js",
    "checkLogoPage"     :   "./pages/checkLogoPage.js",
    "checkFooterPage"   :   "./pages/checkFooterPage.js",
    "checkCookiePage"   :   "./pages/checkCookiePage.js",
    "checkLoginPage"    :   "./pages/checkLoginPage.js",
    "functions"         :   "./pages/global_functions.js",
    "engLoginPage"      :   "./pages/checkENGPage.js",
    "checkFooterENGPage":   "./pages/checkFooterENGPage",
    "checkFooterDUIPage":   "./pages/checkFooterDUIPage",
    "duiLoginPage"      :   "./pages/checkDUIPage.js",
    "checkKliklijstPage":   "./pages/checkKliklijstPage.js",
    "globals"           :   "./globals.js"
  },
  "multiple": {
    "basic":{
      [
        {browser: 'chrome', windowSize: 'maximize'},
        {browser: 'chrome', windowSize: '1220x1000'}
        {browser: 'chrome', windowSize: '1024x1000'},
        {browser: 'chrome', windowSize: '768x1000'},
        {browser: 'chrome', windowSize: '320x1000'},

        {browser: 'firefox', windowSize: '1220x1000'},
        {browser: 'firefox', windowSize: '1024x1000'},
        {browser: 'firefox', windowSize: '768x1000'},
        {browser: 'firefox', windowSize: '320x1000'},

        {browser: 'safari', windowSize: '1220x1000'},
        {browser: 'safari', windowSize: '1024x1000'},
        {browser: 'safari', windowSize: '768x1000'},
        {browser: 'safari', windowSize: '320x1000'}
    ]
  }
   ,
    "smoke": {
      // run only tests containing "@smoke" in name
      "grep": '@smoke',

      // use firefox and different chrome configurations
      "browsers": [
        //'firefox',
        //{browser: 'chrome', windowSize: 'maximize'},
        // replace any config values from WebDriverIO helper


        {browser: 'safari', windowSize: '1220x1000'},
        {browser: 'safari', windowSize: '1024x1000'},
        {browser: 'safari', windowSize: '768x1000'},
        {browser: 'sfari', windowSize: '320x1000'}

        ]
    }
},

  "bootstrap": false,
  "mocha": {
    "reporterOptions": {
      "mochaFile": "output/result.xml",
      "reportDir": "output",
      "reportFilename": "check",
      "enableCharts": true,
      "autoOpen": true,
      "quiet": true,
      "inlineAssets": true
    }
  },
};


```

**Comment by joelgrimberg** [comment]
added "browser": to the mix: 
```

"basic":{
"browser":
      [
        {browser: 'chrome', windowSize: 'maximize'},
        {browser: 'chrome', windowSize: '1220x1000'}
        {browser: 'chrome', windowSize: '1024x1000'},
        {browser: 'chrome', windowSize: '768x1000'},
        {browser: 'chrome', windowSize: '320x1000'},

        {browser: 'firefox', windowSize: '1220x1000'},
        {browser: 'firefox', windowSize: '1024x1000'},
        {browser: 'firefox', windowSize: '768x1000'},
        {browser: 'firefox', windowSize: '320x1000'},

        {browser: 'safari', windowSize: '1220x1000'},
        {browser: 'safari', windowSize: '1024x1000'},
        {browser: 'safari', windowSize: '768x1000'},
        {browser: 'safari', windowSize: '320x1000'}
    ]
```
