### ISSUE TITLE
Codeceptjs looks for files in parent folder

### ISSUE THREAD

**Issue by SuneRadich** [Codeception/CodeceptJS#484]
#### What are you trying to achieve?
Upgrade a working setup to codeceptjs 0.6.x

#### What do you get instead?
After updating codeceptjs, I am unable to run tests.

It seems that codeceptjs goes up one folder, and looks for files (config, testfiles output folder etc) and therefore looks in the wrong folder.

If I downgrade to 0.5.1 my tests run fine again. Seems to be in the 0.6.x that something either changed, or a bug appeared.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Could not load helper NightmareCustom from module '/Users/srv/Documents/Projects/SPL686.0548/src/nightmarecustom_helper.js':
Cannot find module '/Users/srv/Documents/Projects/SPL686.0548/src/nightmarecustom_helper.js'
{"code":"MODULE_NOT_FOUND"}

Error: 
    at createHelpers (/Users/srv/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/container.js:125:13)
    at Function.create (/Users/srv/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/container.js:28:25)
    at Codecept.init (/Users/srv/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/codecept.js:50:15)
    at Command.module.exports (/Users/srv/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/lib/command/run.js:31:14)
    at Command.listener (/Users/srv/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/srv/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/srv/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/srv/.nvm/versions/node/v6.9.1/lib/node_modules/codeceptjs/bin/codecept.js:106:9)
```
### Details

* CodeceptJS version: 0.6.x (tried with 0.6.0, 0.6.1 and 0.6.2)
* NodeJS Version: 6.9.1
* Operating System: OSX (10.12.3)
* Nightmare version: 2.7.0
* Configuration file:

```js
{
    "name": "UI tests",
    "tests": "./test/**/*_test.js",
    "timeout": 10000,
    "output": "./output",
    "helpers": {
        "Nightmare": {
            "url": "http://localurl.dev/",
            "show": true
        },
        "NightmareCustom": {
            "require": "./nightmarecustom_helper.js"
        }
    },
    "include": {},
    "bootstrap": false,
    "mocha": {
        "reporterOptions": {
            "mochaFile": "output/result.xml"
        }
    }
}

```

**Comment by APshenkin** [comment]
@SuneRadich Is it still reproducible with latest version? If yes, can you please provide your project hierarchy and note us, how you try to run tests

Thanks in advance

**Comment by APshenkin** [comment]
Close due inactiviti
