### ISSUE TITLE
WebDriverError: Session ID is null. Using WebDriver after calling quit()?

### ISSUE THREAD

**Issue by leandroz** [Codeception/CodeceptJS#515]
#### What are you trying to achieve?

Running multiple scenarios in the same feature and in different features.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

Running two features with one scenario each, second scenario empty.

```bash
Emitted | test.after
   [2] Queued | hook Protractor._after()
 > [Session] cleaning cookies and localStorage
   [3] Starting recording promises
   Emitted | suite.after
   [3] Queued | hook Protractor._afterSuite()
Signup --
   [4] Starting recording promises
   Emitted | suite.before
   [4] Queued | hook Protractor._beforeSuite()
 New user creation
 > [Session] Starting singleton browser session
   [5] Starting recording promises
   Emitted | test.before
   [5] Queued | hook Protractor._before()
   Emitted | test.start ([object Object])
   [5] Queued | fire test.passed
   [5] Queued | finish test
   Emitted | test.passed ([object Object])
 ✓ OK in 1ms

   Emitted | test.after
   [5] Queued | hook Protractor._after()
 > [Session] cleaning cookies and localStorage
   [6] Starting recording promises
   Emitted | suite.after
   [6] Queued | hook Protractor._afterSuite()

  OK  | 2 passed   // 8s
   Emitted | global.result ([object Object])
   [6] Error | WebDriverError: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_112'
Driver info: driver.version: EventFiringWebDriver
   [6] Stopping recording promises
/.nvm/versions/node/v6.3.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2517
        throw error;
        ^

WebDriverError: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_112'
Driver info: driver.version: RemoteWebDriver

```

Running two features with one scenario each, second scenario with steps.

```bash
Emitted | test.after
   [2] Queued | hook Protractor._after()
 > [Session] cleaning cookies and localStorage
   [3] Starting recording promises
   Emitted | suite.after
   [3] Queued | hook Protractor._afterSuite()
Signup --
   [4] Starting recording promises
   Emitted | suite.before
   [4] Queued | hook Protractor._beforeSuite()
 New user creation
 > [Session] Starting singleton browser session
   [5] Starting recording promises
   Emitted | test.before
   [5] Queued | hook Protractor._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "/#/home")
   [5] Queued | amOnPage: "/#/home"
   Emitted | step.after (I am on page "/#/home")
   [5] Queued | return step result
   Emitted | step.before (I see "Con Vlic puedes monitorear marcas o personas en contenidos periodísticos de TV y Radio.")
   [5] Queued | see: "Con Vlic puedes monitorear marcas o personas en contenidos periodísticos de TV y Radio."
   Emitted | step.after (I see "Con Vlic puedes monitorear marcas o personas en contenidos periodísticos de TV y Radio.")
   [5] Queued | return step result
   Emitted | step.before (I click "Crear cuenta")
   [5] Queued | click: "Crear cuenta"
   Emitted | step.after (I click "Crear cuenta")
   [5] Queued | return step result
   Emitted | step.before (I see current url equals "/#/create-account")
   [5] Queued | seeCurrentUrlEquals: "/#/create-account"
   Emitted | step.after (I see current url equals "/#/create-account")
   [5] Queued | return step result
   Emitted | step.before (I fill field {"model":"vm.data.username"}, "hello@world.com")
   [5] Queued | fillField: {"model":"vm.data.username"}, "hello@world.com"
   Emitted | step.after (I fill field {"model":"vm.data.username"}, "hello@world.com")
   [5] Queued | return step result
   Emitted | step.before (I fill field {"model":"vm.data.first_name"}, "Hello World")
   [5] Queued | fillField: {"model":"vm.data.first_name"}, "Hello World"
   Emitted | step.after (I fill field {"model":"vm.data.first_name"}, "Hello World")
   [5] Queued | return step result
   Emitted | step.before (I fill field {"model":"vm.data.password"}, "123456")
   [5] Queued | fillField: {"model":"vm.data.password"}, "123456"
   Emitted | step.after (I fill field {"model":"vm.data.password"}, "123456")
   [5] Queued | return step result
   Emitted | step.before (I fill field {"model":"vm.data.confirmPassword"}, "123456")
   [5] Queued | fillField: {"model":"vm.data.confirmPassword"}, "123456"
   Emitted | step.after (I fill field {"model":"vm.data.confirmPassword"}, "123456")
   [5] Queued | return step result
   Emitted | step.before (I click "Crear cuenta")
   [5] Queued | click: "Crear cuenta"
   Emitted | step.after (I click "Crear cuenta")
   [5] Queued | return step result
   [5] Queued | fire test.passed
   [5] Queued | finish test
   Emitted | step.start (I am on page "/#/home")
 • I am on page "/#/home"
   [5] Error | WebDriverError: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_112'
Driver info: driver.version: EventFiringWebDriver
   [5] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [5] <teardown> Queued | hook Protractor._failed()
   [5] <teardown> Queued | () => done(err)
   [5] <teardown> Stopping recording promises
 > Screenshot has been saved to /output/New_user_creation.failed.png
 ✖ FAILED in 1431ms

   Emitted | test.after
   [5] <teardown> Queued | hook Protractor._after()
 > [Session] cleaning cookies and localStorage
   [6] Starting recording promises
   Emitted | suite.after
   [6] Queued | hook Protractor._afterSuite()

-- FAILURES:

  1) Signup: New user creation:
     Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_112'
Driver info: driver.version: EventFiringWebDriver
  
  Scenario Steps:
  
  - I.click("Crear cuenta") at Test.Scenario (test/signup_test.js:12:5)
  - I.fillField({"model":"vm.data.confirmPassword"}, "123456") at Test.Scenario (test/signup_test.js:11:5)
  - I.fillField({"model":"vm.data.password"}, "123456") at Test.Scenario (test/signup_test.js:10:5)
  - I.fillField({"model":"vm.data.first_name"}, "Hello World") at Test.Scenario (test/signup_test.js:9:5)
  - I.fillField({"model":"vm.data.username"}, "hello@world.com") at Test.Scenario (test/signup_test.js:8:5)
  - I.seeCurrentUrlEquals("/#/create-account") at Test.Scenario (test/signup_test.js:7:5)
  - I.click("Crear cuenta") at Test.Scenario (test/signup_test.js:6:5)
  - I.see("Con Vlic puedes monitorear marcas o personas en contenidos periodísticos de TV y Radio.") at Test.Scenario (test/signup_test.js:5:5)
  - I.amOnPage("/#/home") at Test.Scenario (test/signup_test.js:4:5)
  
  WebDriverError: Session ID is null. Using WebDriver after calling quit()?
  Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
  os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_112'
  Driver info: driver.version: EventFiringWebDriver
      at WebDriverError (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
      at Object.checkLegacyResponse (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
      at parseHttpResponse (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: WebDriver.executeScript()
      at schedule (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
      at executeScript (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:887:16)
      at run (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/protractor/built/browser.js:58:33)
      at ProtractorBrowser.to.(anonymous function) [as executeScript] (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/protractor/built/browser.js:66:16)
      at Protractor._after (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/helper/SeleniumWebdriver.js:151:25)
      at recorder.add (/Users/leandroz/.nvm/versions/node/v6.3.1/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/listener/helpers.js:23:69)
      at process._tickCallback (internal/process/next_tick.js:103:7)


  FAIL  | 1 passed, 1 failed   // 10s
   Emitted | global.result ([object Object])
   [6] Error | WebDriverError: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_112'
Driver info: driver.version: EventFiringWebDriver
   [6] Stopping recording promises
   [6] Error | WebDriverError: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_112'
Driver info: driver.version: EventFiringWebDriver
   [6] Stopping recording promises

```

### Details

* CodeceptJS version: 0.6.3-pre
* NodeJS Version: v6.3.1
* Operating System: MacOS
* Protractor || WebDriverIO || Nightmare version (if related)
* Protractor: Version 5.1.1
* Configuration file:

```js
{
  "tests": "./test/*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Protractor": {
      "url": "http://localhost:8100",
      "browser": "chrome",
      "driver": "hosted",
      "rootElement": "body",
    }
  },
  "bootstrap": false,
  "mocha": {}
}
```

**Comment by lisettea** [comment]
I too am running into this issue: a cascading failure of tests when:

- running several subsequent tests - the end/failure of one happens while the next test is starting and the the webdriver.quit() of the first test crashes the second.

- when running parallel tests - the failure of a test in Internet Explorer (and subsequent quitting of the driver) crashes the running of said test in Chrome and vice versa.

CodeceptJS version: 0.6.3-pre
NodeJS Version: v6.3.1
Operating System: Windows
Protractor
Protractor: Version 5.1.2

```
tests: 'tests/*.js',
    timeout: 10000,
    output: './output',
    multiple: {
        'basic': {
            'browsers': ['chrome', 'internet explorer']
        }
    },

    helpers: {
    Protractor: {
        'seleniumAddress': 'http://localhost:4446/wd/hub',
        'url': process.env.URL || '',
        'browser': process.env.BROWSER || ''                  
    }
```

**Comment by APshenkin** [comment]
@leandroz Please try to update codeceptJS to 1.0.0 and try again
