### ISSUE TITLE
codeceptjs init, tries to create test directory in the parent directory

### ISSUE THREAD

**Issue by OussamaElgoumri** [Codeception/CodeceptJS#545]
#### What are you trying to achieve?
`codeceptjs init`

#### What do you get instead?
it tries to create test folder on the parent directory, i did look into the problem and find that the function `getTestRoot()` uses path.extname, but does not check if the path is a directory or a file. in my case i name website in `/var/www` by the real name of the website i'am working on, ex: `/var/www/example.com`

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Installing to /var/www
? Where are your tests located? ./e2e/*_test.js
? What helpers do you want to use? WebDriverIO
? Where should logs, screenshots, and reports to be stored? ./e2e/logs
? Would you like to extend I object with custom steps? Yes
? Do you want to choose localization for tests? English (no localization)
? Where would you like to place custom steps? ./e2e/steps_file.js
readline.js:982
            throw err;
            ^

Error: EACCES: permission denied, mkdir '/var/www/e2e'
    at Object.fs.mkdirSync (fs.js:855:18)
    at Function.sync (/var/www/example.com/node_modules/mkdirp/index.js:71:13)
    at module.exports.inquirer.prompt [as completed] (/var/www/example.com/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/command/init.js:122:12)
    at module.exports.PromptUI.onCompletion (/var/www/example.com/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/var/www/example.com/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/var/www/example.com/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.onCompleted (/var/www/example.com/node_modules/rx-lite/rx.lite.js:5871:19)
    at Subject.tryCatcher (/var/www/example.com/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (/var/www/example.com/node_modules/rx-lite/rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/var/www/example.com/node_modules/rx-lite/rx.lite.js:1489:14)

```
> Provide test source code if related

```php
// paste test
```
### Details

* CodeceptJS version: 
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by APshenkin** [comment]
@OussamaElgoumri 
I'm unable to reproduce this issue? Could you please give us step-by-step reproducible case for it?

Thanks in advance!

**Comment by APshenkin** [comment]
Close due inactivity
