### ISSUE TITLE
Nightmare test fails with custom window size

### ISSUE THREAD

**Issue by d-kurochkin** [Codeception/CodeceptJS#605]
#### What are you trying to achieve?
I'm trying to run tests with custom window size
#### What do you get instead?
I get white screen and test fails.
> Provide console output if related. Use `--verbose` mode for more details.

```bash
$ npm test -- --verbose

> example@1.0.0 test /home/user/example
> codeceptjs run --steps "--verbose"

CodeceptJS v0.6.3
Using test root "/home/user/example"

Example --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook Nightmare._beforeSuite()
 test
   [2] Starting recording promises
   Emitted | test.before
   [2] Queued | hook Nightmare._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "/")
   [2] Queued | amOnPage: "/"
   Emitted | step.after (I am on page "/")
   [2] Queued | return step result
   [2] Queued | fire test.passed
   [2] Queued | finish test
   Emitted | step.start (I am on page "/")
 • I am on page "/"
   [2] Error | Nothing responds to "goto"
   [2] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [2] <teardown> Queued | hook Nightmare._failed()
   [2] <teardown> Queued | () => done(err)
   [2] <teardown> Stopping recording promises
 > Screenshot is saving to /home/user/example/output/test.failed.png
   [2] <teardown> Error | Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
   [2] <teardown> Stopping recording promises
 ✖ FAILED in 30284ms

   Emitted | test.after
   [2] <teardown> Queued | hook Nightmare._after()
   [3] Starting recording promises
   Emitted | suite.after ([object Object])
   [3] Queued | hook Nightmare._afterSuite()

-- FAILURES:

  1) Example: test:
     [Wrapped Error] "Nothing responds to \"goto\""
  
  Scenario Steps:
  
  - I.amOnPage("/") at Test.Scenario (example_test.js:6:5)
  
  Error: [Wrapped Error] "Nothing responds to \"goto\""
      at promise.catch (node_modules/codeceptjs-nightmare/node_modules/codeceptjs/lib/recorder.js:107:15)
      at <anonymous>


  FAIL  | 0 passed, 1 failed   // 30s
   Emitted | global.result ([object Object])
npm ERR! Test failed.  See above for more details.
```
> Provide test source code if related

```js
Feature('Example');

Scenario('test', (I) => {
  I.amOnPage('/');
});
```
### Details

* CodeceptJS version: 0.6.3
* CodeceptJS Nightmare version: 1.1.0
* NodeJS Version: v8.1.3
* Operating System: Fedora release 25 (Twenty Five)
* Nightmare: 2.10.0
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
      "Nightmare": {
      "url": "https://google.com",
      "windowSize": "1000x1000",
      "show": true,
      "restart": false
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {},
  "name": "example"
}
```

**Comment by APshenkin** [comment]
Please test in with 1.0.0 and send the update for us

**Comment by d-kurochkin** [comment]
Hi @APshenkin, it works as expected with new version. Thank you very much.
