### ISSUE TITLE
WebDriverIO seeNumberOfVisibleElements fails on master

### ISSUE THREAD

**Issue by BorisOsipov** [Codeception/CodeceptJS#623]
Hi folks!
I use master as dependency in my tests.
Today I ran into a new issue.
**Simple scenario to reproduce issue:**
```js
Scenario("seeNumberOfVisibleElements test", function*(I) {
  I.amOnPage("https://github.com/");
  I.seeNumberOfVisibleElements("//div[@class='featurette']", 4);
});
```
**Error log:**
```bash
 1) seeNumberOfVisibleElements: seeNumberOfVisibleElements test:
     this.grabNumberOfVisibleElements.then is not a function

  Scenario Steps:

  - I.seeNumberOfVisibleElements("//div[@class='featurette']", 4) at Test.<anonymous> (test_test.js:5:5)
  - I.amOnPage("https://github.com/") at Test.<anonymous> (test_test.js:4:5)

  TypeError: this.grabNumberOfVisibleElements.then is not a function
      at WebDriverIO.seeNumberOfVisibleElements (node_modules/codeceptjs/lib/helper/WebDriverIO.js:985:45)
      at Step.run (node_modules/codeceptjs/lib/step.js:28:47)
      at recorder.add (node_modules/codeceptjs/lib/actor.js:62:27)
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```
> Provide test source code if related

### Details

* CodeceptJS version: master#5fbf29c  
* NodeJS Version: v7.9.0
* Operating System: Linux
* WebDriverIO ^4.8.0
* Configuration file: defailt

**Comment by DavertMik** [comment]
Yes. Thank you for reporing. Looks like this was the resul of a bad merge
