### ISSUE TITLE
"Retries" option doesn't work

### ISSUE THREAD

**Issue by ndemengel** [Codeception/CodeceptJS#644]
#### What are you trying to achieve?

Hi,

I want my test to be rerun upon failure, according to the "retries" option.

#### What do you get instead?

For instance, I expect the following test to print "run" 3 times:
```js
Feature('Retries')

Scenario('simple test', {retries: 2}, (I) => {
    console.log('run');
    throw new Error('boum');
});
```

But it prints "run" only once.

### Details

* CodeceptJS version: 1.0.0
* NodeJS Version: 6.10.3
* Operating System: Ubuntu 16.04.2 LTS
* WebDriverIO: 4.8.0

Note: if I simplify [the test of the feature](https://github.com/Codeception/CodeceptJS/blob/2bed782556448c0b0a737221a104d85d2efb70d0/test/data/sandbox/flacky_test.flacky.js) as follows, it breaks:
```js
var assert = require('assert');
var tries = 0;
var tries2 = 0;

Feature('Flacky');//, {retries: 4});                                                                                                                                                                                               

Scenario('Not so flacky test', { retries: 2}, () => {
  tries++;
  assert.equal(tries, 2);
  console.log('[T1] Retries: '+tries);
});

/*Scenario('Really flacky test', () => {
  tries2++;
  assert.equal(tries2, 4);
  console.log('[T2] Retries: '+tries2);
});*/
```

I thank you in advance for the fix!

**Comment by APshenkin** [comment]
@ndemengel Could you please provide logs in verbose mode?

**Comment by ndemengel** [comment]
Sure, here are the logs for my first example:
```
CodeceptJS v1.0.0
Using test root "/home/nico/Workspaces/hopwork/acceptance-testing"

Retries --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook WebDriverIO._beforeSuite()
 simple test
   Emitted | test.before
   [1] Queued | hook WebDriverIO._before()
   Emitted | test.start ([object Object])
run
   [1] Queued | throw error Error: boum
   [1] Queued | fire test.passed
   [1] Queued | finish test
   [1] Error | Error: boum
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook WebDriverIO._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
 > Screenshot has been saved to /home/nico/Workspaces/hopwork/acceptance-testing/output/simple_test.failed.png
 ✖ FAILED in 948ms

   [2] Starting recording promises
   Emitted | test.after
   [2] Queued | hook WebDriverIO._after()
   Emitted | suite.after ([object Object])
   [2] Queued | hook WebDriverIO._afterSuite()

-- FAILURES:

  1) Retries: simple test:
     boum
  rror: boum
      at Test.Scenario (test/retries-spec.js:5:11)
      at Context.test.fn (node_modules/codeceptjs/lib/scenario.js:51:24)


  FAIL  | 0 passed, 1 failed   // 960ms
   Emitted | global.result ([object Object])
   [2] Queued | hook WebDriverIO._finishTest()
```

**Comment by APshenkin** [comment]
@ndemengel Yep, It's a bug, will fix it in next release

**Comment by ndemengel** [comment]
@APshenkin many thanks!
