### ISSUE TITLE
Cannot load ApiDataFactory

### ISSUE THREAD

**Issue by apomortsev** [Codeception/CodeceptJS#672]
#### What are you trying to achieve?

Use ApiDataFactory helper

#### What do you get instead?

Error:

Could not load helper ApiDataFactory from module './helper/ApiDataFactory':
Required modules are not installed.

RUN: npm install --save-dev unirest rosie
{}

Error:
    at createHelpers (node_modules/codeceptjs/lib/container.js:125:13)
    at Function.create (node_modules/codeceptjs/lib/container.js:28:25)
    at Codecept.init (node_modules/codeceptjs/lib/codecept.js:54:15)
    at Command.module.exports (node_modules/codeceptjs/lib/command/run.js:31:14)
    at Command.listener (node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (node_modules/commander/index.js:615:12)
    at Command.parse (node_modules/commander/index.js:458:21)
    at Object.<anonymous> (node_modules/codeceptjs/bin/codecept.js:106:9)

---

Both unirest and rosie are actually installed:

$ npm list unirest rosie
my-app@0.0.1 /Users/user/my-app
├── rosie@1.6.0
└── unirest@0.5.1

 The error is caused by missing `const requireg = require('requireg')` in ApiDataFactory.js:

```
  static _checkRequirements() {
    try {
      requireg("unirest");
      requireg("rosie");
    } catch(e) {
      return ["unirest", "rosie"]; // <= breakpoint here
    }
  }

> e
ReferenceError: requireg is not defined
message:"requireg is not defined"
stack:"ReferenceError: requireg is not defined\n    at Function._checkRequirements (node_modules/codeceptjs/lib/helper/ApiDataFactory.js:168:7)\n    at createHelpers (node_modules/codeceptjs/lib/container.js:112:40)\n    at Function.create (node_modules/codeceptjs/lib/container.js:28:25)\n    at Codecept.init (node_modules/codeceptjs/lib/codecept.js:54:15)\n    at Command.module.exports (node_modules/codeceptjs/lib/command/run.js:31:14)\n    at Command.listener (node_modules/commander/index.js:301:8)\n    at emitTwo (events.js:106:13)\n    at Command.emit (events.js:191:7)\n    at Command.parseArgs (node_modules/commander/index.js:615:12)\n    at Command.parse (node_modul...
__proto__:Error {name: "ReferenceError", message: ""}
```

### Details

* CodeceptJS version: 1.0.0
* NodeJS Version: 6.9.4
* Operating System: Max OSX Sierra

---

Thank you!

**Comment by apomortsev** [comment]
I can run successfully after adding `require('requireg').globalize()` in my codecept.conf.js, as a workaround.
