### ISSUE TITLE
"before all" hook: codeceptjs.beforeSuite in undefinedms

### ISSUE THREAD

**Issue by filosoff88** [Codeception/CodeceptJS#686]
Hello,

I'm trying to run tests in IE, but this error is all I've got
"before all" hook: codeceptjs.beforeSuite in undefinedms

Chrome and firefox work fine

What should I do to fix that?
IEwebdriver is downloaded and added to Path.

**Comment by APshenkin** [comment]
@filosoff88 Hi!

Can you please provide more details about your issue? versions of codeceptjs, selenium, steps to reproduce?

I tested IE on win 10 with webdriverIO and seleniumWebdriver and it works as expected

**Comment by filosoff88** [comment]
It works fine at my home PC, but doesn't work at virtual machine Win Server 2016.
Codeceptjs 1.0.2 with webdriverIO. 
Selenium build info: version: '3.5.0'

I download IEdriverServer.exe, added it to PATH, added to codecept.json
"multiple": {
 "basic": {"browsers": [
			{"browser": "chrome", "windowSize": "maximize"}, 
			{"browser": "firefox", "windowSize": "maximize"}, 
			{"browser": "internet explorer", "windowSize": "maximize"}
			]},
And execute codeceptjs run-multiple basic --reporter mochawesome

**Comment by APshenkin** [comment]
@filosoff88 Can you please run CodeceptJS in single mode with `--verbose` flag and paste output here? Thanks!

**Comment by filosoff88** [comment]
[1.ie:internet explorer] Registration --
[1.ie:internet explorer]    [1] Starting recording promises
[1.ie:internet explorer]    Emitted | suite.before ([object Object])
[1.ie:internet explorer]    [1] Queued | hook WebDriverIO._beforeSuite()
[1.ie:internet explorer]  > [Session] Starting singleton browser session
[1.ie:internet explorer]  × "before all" hook: codeceptjs.beforeSuite in undefinedms
[1.ie:internet explorer]    Emitted | suite.after ([object Object])
[1.ie:internet explorer]    [1] Queued | hook WebDriverIO._afterSuite()

**Comment by APshenkin** [comment]
@filosoff88 There is no error stack trace?

Could you please also provide selenium logs?

**Comment by filosoff88** [comment]
12:38:35.211 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
12:38:35.211 INFO - Found handler: org.openqa.selenium.remote.server.BeginSession@62748c53
12:38:35.212 INFO - /session: Executing POST on /session (handler: BeginSession)
12:38:35.213 INFO - Capabilities are: Capabilities {rotatable=true, locationContextEnabled=true, loggingPrefs={browser=ALL, driver=ALL, }, browserName=internet explorer, javascriptEnabled=true, handlesAlerts=true, requestOrigins={url=http://webdriver.io, version=4.6.2, name=webdriverio, }, }
12:38:35.214 INFO - Capabilities {rotatable=true, locationContextEnabled=true, loggingPrefs={browser=ALL, driver=ALL, }, browserName=internet explorer, javascriptEnabled=true, handlesAlerts=true, requestOrigins={url=http://webdriver.io, version=4.6.2, name=webdriverio, }, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)
12:38:35.215 INFO - Capabilities {rotatable=true, locationContextEnabled=true, loggingPrefs={browser=ALL, driver=ALL, }, browserName=internet explorer, javascriptEnabled=true, handlesAlerts=true, requestOrigins={url=http://webdriver.io, version=4.6.2, name=webdriverio, }, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Started InternetExplorerDriver server (64-bit)
3.5.0.0
Listening on port 48189
Only local connections are allowed
2017-08-29 12:38:35.748:WARN:osjs.HttpChannel:qtp405662939-17: /wd/hub/session
java.lang.NullPointerException
        at com.google.gson.JsonPrimitive.isPrimitiveOrString(JsonPrimitive.java:278)
        at com.google.gson.JsonPrimitive.setValue(JsonPrimitive.java:101)
        at com.google.gson.JsonPrimitive.<init>(JsonPrimitive.java:65)
        at org.openqa.selenium.remote.server.ExceptionHandler.lambda$execute$0(ExceptionHandler.java:82)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.openqa.selenium.remote.server.ExceptionHandler.execute(ExceptionHandler.java:88)
        at org.openqa.selenium.remote.server.WebDriverServlet.handle(WebDriverServlet.java:247)
        at org.openqa.selenium.remote.server.WebDriverServlet.doPost(WebDriverServlet.java:151)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.WebDriverServlet.service(WebDriverServlet.java:111)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Unknown Source)

**Comment by APshenkin** [comment]
Looks like this is selenium issue. Try to downgrade selenium and ieDriver to 3.4.0
I had the same issue as you with 3.5.0 
![image](https://user-images.githubusercontent.com/14344430/29823722-2cc960ec-8cd8-11e7-80cd-9d3a44be820e.png)

Also Protractor users faces with the same issue, see: https://stackoverflow.com/questions/45681507/protractor-error-webdrivererror-invalid-timeout-type-specified-ms

**Comment by APshenkin** [comment]
Close due inactivity
