### ISSUE TITLE
Cannot read property 'WebDriverIO' of undefined

### ISSUE THREAD

**Issue by ZozoZoeLi** [Codeception/CodeceptJS#702]
#### What are you trying to achieve?

Hi guys, I'm trying to access WebdriverIO so that I can customize my own functions. I read the document that looks like "this.helpers['WebDriverIO']" is the right thing to do. 

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

I get Cannot read property 'WebDriverIO' of undefined.

```bash
Could not include object loginPage from module '/Users/zoel/Documents/workspace/emrc-codeceptJS/src/test/page_objects/login_page.js'
Cannot read property 'WebDriverIO' of undefined

Error: 
    at createSupportObjects (/Users/zoel/.nvm/versions/node/v6.11.1/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/container.js:145:13)
    at Function.create (/Users/zoel/.nvm/versions/node/v6.11.1/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/container.js:30:25)
    at Codecept.init (/Users/zoel/.nvm/versions/node/v6.11.1/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/codecept.js:54:15)
    at Command.module.exports (/Users/zoel/.nvm/versions/node/v6.11.1/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/lib/command/run.js:31:14)
    at Command.listener (/Users/zoel/.nvm/versions/node/v6.11.1/lib/node_modules/codeceptjs-webdriverio/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/zoel/.nvm/versions/node/v6.11.1/lib/node_modules/codeceptjs-webdriverio/node_modules/commander/index.js:635:12)
    at Command.parse (/Users/zoel/.nvm/versions/node/v6.11.1/lib/node_modules/codeceptjs-webdriverio/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (/Users/zoel/.nvm/versions/node/v6.11.1/lib/node_modules/codeceptjs-webdriverio/node_modules/codeceptjs/bin/codecept.js:107:9)
```

> Provide test source code if related

This is my page object where I'm trying to use WebdriverIO to write a function called "waitToSeeInTitle" so I can call it as "page_object.waitToSeeInTitle()" in my test. 

```js
'use strict';
let I;

let wdio = this.helpers['WebDriverIO'].browser;

console.log('test wdio', wdio)
module.exports = {

  _init() {
    I = actor();
  }

  waitToSeeInTitle(text){
    return wdio.waitUntil(() => wdio.getTitle().then((title) => {
      return stringIncludes('web page title').assert(text, title)
    }), 10000);
  }

}

```

### Details

* CodeceptJS version: 1.0.2
* NodeJS Version: 6.11.1
* Operating System: MacOS 10.12.5
*  WebDriverIO version: 4.8.0
* Configuration file:

My config file is written in .js.

```js
var host = 'https://' +
  (process.env.URL||(require('os').hostname()+':8080'));

// console.log('test wdio in config', this.helpers['WebDriverIO'].browser.getTitle());

codeceptJS = {
  tests: "src/test/*_test.js",
  timeout : 10000,
  output: "./output",
  helpers: {
    WebDriverIO : {
      smartWait: 5000,
      browser: "chrome",
      restart: false,
      windowSize: "maximize",
      url: host,
    }
  },
    include: {
      I: "./src/test/actor.js",
      loginPage: './src/test/page_objects/login_page.js',
    },
    bootstrap: false,
    mocha: {},
    name: "emrc-codeceptJS",
}
```
@DavertMik

**Comment by APshenkin** [comment]
@ZozoZoeLi You have to create helpers in helper file, not in PageObject

Check detailed instruction here http://codecept.io/helpers/

**Comment by ZozoZoeLi** [comment]
@APshenkin Same. You may see above that I tried to console 
// console.log('test wdio in config', this.helpers['WebDriverIO'].browser.getTitle());
But still get "getTitle()" is not a function.

**Comment by ZozoZoeLi** [comment]
@APshenkin Thanks for your reply! I will have a look right now.

**Comment by APshenkin** [comment]
Close due inactivity

**Comment by mycarrysun** [comment]
Here is an example for WebDriverIO on how to set this up...it was not very clear in the docs

[https://codecept.io/helpers/#webdriverio-example](https://codecept.io/helpers/#webdriverio-example)
