### ISSUE TITLE
I.appendField ('field', 'value'); helper does not work as documented for Appium

### ISSUE THREAD

**Issue by musanmaz** [Codeception/CodeceptJS#719]
#### What are you trying to achieve?
 I write code like : 
`  I.appendField('#com.example.android.contactmanager:id/contactNameEditText','Someone Name');`

I want to send a name to the test application.

#### What do you get instead?
I get an output like the following.
```
 addition-test: test something:
     Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]
```

> Provide console output if related. Use `--verbose` mode for more details.

`D:\works\codecept\calc-test>codeceptjs run --steps --verbose
CodeceptJS v1.0.2
Using test root "D:\works\codecept\calc-test"

```
addition-test --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook Appium._beforeSuite()
 test something
   Emitted | test.before
   [1] Queued | hook Appium._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I wait 2)
   [1] Queued | wait: 2
   Emitted | step.after (I wait 2)
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I click "#com.example.android.contactmanager:id/addContactButton")
   [1] Queued | click: "#com.example.android.contactmanager:id/addContactButton"
   Emitted | step.after (I click "#com.example.android.contactmanager:id/addContactButton")
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I wait 5)
   [1] Queued | wait: 5
   Emitted | step.after (I wait 5)
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I append field "#com.example.android.contactmanager:id/contactNameEditText", "deneme")
   [1] Queued | appendField: "#com.example.android.contactmanager:id/contactNameEditText", "deneme"
   Emitted | step.after (I append field "#com.example.android.contactmanager:id/contactNameEditText", "deneme")
   [1] Queued | step passed
   [1] Queued | return result
   [1] Queued | fire test.passed
   [1] Queued | finish test
   Emitted | step.start (I wait 2)
 * I wait 2
   Emitted | step.passed (I wait 2)
   Step finished in 2.005 sec
   Emitted | step.start (I click "#com.example.android.contactmanager:id/addContactButton")
 * I click "#com.example.android.contactmanager:id/addContactButton"
   Emitted | step.passed (I click "#com.example.android.contactmanager:id/addContactButton")
   Step finished in 0.664 sec
   Emitted | step.start (I wait 5)
 * I wait 5
   Emitted | step.passed (I wait 5)
   Step finished in 5.002 sec
   Emitted | step.start (I append field "#com.example.android.contactmanager:id/contactNameEditText", "deneme")
 * I append field "#com.example.android.contactmanager:id/contactNameEditText", "deneme"
   [1] Error | Error: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]
   Emitted | step.failed (I append field "#com.example.android.contactmanager:id/contactNameEditText", "deneme")
   Step finished in 0.325 sec
   [1] Error | Error: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook Appium._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
 > Screenshot has been saved to D:\works\codecept\calc-test\output\test_something.failed.png
 × FAILED in 10871ms

   [2] Starting recording promises
   Emitted | test.after
   [2] Queued | hook Appium._after()
   Emitted | suite.after ([object Object])
   [2] Queued | hook Appium._afterSuite()

-- FAILURES:

  1) addition-test: test something:
     Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]

  Scenario Steps:

  - I.appendField("#com.example.android.contactmanager:id/contactNameEditText", "deneme") at Test.Scenario (first_test.js:9:7)
  - I.wait(5) at Test.Scenario (first_test.js:8:7)
  - I.click("#com.example.android.contactmanager:id/addContactButton") at Test.Scenario (first_test.js:7:7)
  - I.wait(2) at Test.Scenario (first_test.js:6:7)

  Error


  FAIL  | 0 passed, 1 failed   // 38s
   Emitted | global.result ([object Object])
   [2] Queued | hook Appium._finishTest()`
```

> Provide test source code if related

```js

Feature('addition-test');

Scenario('test something', (I) => {
    
    I.wait(2);
    I.click('#com.example.android.contactmanager:id/addContactButton');
    I.wait(5);
    I.appendField('#com.example.android.contactmanager:id/contactNameEditText','deneme');  
    
});

```

### Details

* CodeceptJS version: 1.0.2
* NodeJS Version:v7.5.0
* Operating System: Windows 10
* Appium
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
   "helpers": {
      "Appium": {
          "port": "4723",
          "platform": "Android",
          "fullReset": "true",
          "desiredCapabilities": {
              "app": "D:\\works\\codecept\\calc-test\\apk\\contact.apk",
              "deviceName": "test-cihaz",
              "platformVersion": "4.4.2",
              "fullReset": "true"
          }
      }
    },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "calc-test"
}
```

**Comment by DavertMik** [comment]
reproduced. Thanks, going to fix it

**Comment by reubenmiller** [comment]
Closed due to inactivity. If it is still an active issue please reopen it :)
