### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by kevinlambert** [Codeception/CodeceptJS#720]
#### What are you trying to achieve?
I am trying to run the custom runner example code on http://codecept.io/hooks/

#### What do you get instead?
`Cannot read property 'forEach' of undefined`

```bash
/Users/kevin.lambert/Development/xxxx/node_modules/codeceptjs/lib/codecept.js:73
    this.config.hooks.forEach((hook) => runHook(hook));
                     ^

TypeError: Cannot read property 'forEach' of undefined
    at Codecept.bootstrap (/Users/kevin.lambert/Development/xxxx/node_modules/codeceptjs/lib/codecept.js:73:22)
    at Object.<anonymous> (/Users/kevin.lambert/Development/xxxx/src/tests/runner.js:14:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

> Provide test source code if related

```js
let Container = require('codeceptjs').container;
let Codecept = require('codeceptjs').codecept;

let config = { helpers: { WebDriverIO: { browser: 'chrome', url: 'http://localhost' } } };
let opts = { steps: true };

// create runner
let codecept = new Codecept(config, opts);

// create helpers, support files, mocha
Container.create(config, opts);

// initialize listeners
codecept.bootstrap();

// load tests
codecept.loadTests('*_test.js');

// run tests
codecept.run();
```

### Details

* CodeceptJS version: 1.0.2
* NodeJS Version: 6.11.2
* Operating System: OSX 10.12.6
* WebDriverIO: 4.8.0
* Configuration file:

```js
{
    "tests": "./src/tests/acceptance/**/*_test.js",
    "timeout": 10000,
    "output": "./report/tests/acceptance",
    "helpers": {
        "WebDriverIO": {
            "url": "http://localhost",
            "browser": "chrome"
        }
    },
    "include": {
        "I": "./src/tests/acceptance/steps_file.js"
    },
    "bootstrap": false,
    "mocha": {},
    "name": "xxxx"
}
```

**Comment by kevinlambert** [comment]
Got it to work with this code. The example needs to be updated. 

Also it might be helpful to either output friendly error messages for required config fields and fail gracefully 

OR 

if not required then don't error and handle missing config parameters with validation checks.

```
let Container = require('codeceptjs').container;
let Codecept = require('codeceptjs').codecept;

let config = {
    hooks: [],
    helpers: {
        WebDriverIO: {
            browser: 'chrome', url: 'http://localhost'
        }
    },
    output: './report/tests/acceptance'
};

let opts = { steps: true };

// create runner
let codecept = new Codecept(config, opts);
codecept.init('./src/tests/acceptance');

// create helpers, support files, mocha
Container.create(config, opts);

// initialize listeners
codecept.bootstrap();

// load tests
codecept.loadTests('*_test.js');

// run tests
codecept.run();

```
