### ISSUE TITLE
Using webDriverIO helper properly

### ISSUE THREAD

**Issue by alias8** [Codeception/CodeceptJS#738]
#### What do you get instead? An error "Cannot read property 'promise' of undefined".

```bash
webdriverIO test --
 try to locate element
 • I am on page "http://codecept.io/" (13.999 sec)
 • I try locate  (0.001 sec)
 ✖ FAILED in 16342ms


-- FAILURES:

  1) webdriverIO test: try to locate element:
     Cannot read property 'promise' of undefined
  
  Scenario Steps:
  
  - I.tryLocate() at Test.<anonymous> (livetv_test.js:5:7)
  - I.amOnPage("http://codecept.io/") at Test.<anonymous> (livetv_test.js:4:7)
  
  
  
  Run with --verbose flag to see NodeJS stacktrace


  FAIL  | 0 passed, 1 failed   // 16s

```

> Provide test source code if related
some_test.js:
```js
Feature('webdriverIO test');

Scenario("try to locate element", function * (I) {
    I.amOnPage("http://codecept.io/");
    I.tryLocate();
});
```

WebDriverIOHelper.js:
```js
'use strict';

class WebDriverIOHelper extends Helper {
    tryLocate() {
        const element = this.helpers['WebDriverIO'].browser.element;
        return element('h1');
    }
}

module.exports = WebDriverIOHelper;
```

### Details

* CodeceptJS version: v1.0.0
* NodeJS Version: v8.4.0
* Operating System: macOs Sierra v 10.12.6
* SeleniumWebDriver version: '3.4.0'
* Configuration file:

```js
{
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost:3000",
      "windowSize": "maximize",
      "browser": "chrome",
      "restart": true,
      "smartWait": 15000
    },
    "WebDriverIOHelper": {
      "require": "./WebDriverIOHelper.js"
    }
  },
  "include": {
    "I": "./custom_steps.js"
  },
  "mocha": {
    "reporterOptions": {
      "mochaFile": "./output/result.xml"
    }
  },
  "bootstrap": "./bootstrap.js",
  "teardown": null,
  "hooks": [],
  "tests": "./*_test.js",
  "timeout": 5000,
  "multiple": {
    "default": {
      "grep": "signin",
      "browsers": [
        "chrome",
        "safari"
      ]
    }
  },
  "name": "tests"
}
```

**Comment by DavertMik** [comment]
I'd like to see a full stack trace with `--verbose` option to tell more.
But looks like you can't use `element` as it might be not a valid promise which can be handled by our Recorder (see Advanced Usage in docs)

**Comment by alias8** [comment]
Oh yeah sorry, here is the verbose output. I was attempting to use the syntax shown here
http://webdriver.io/api/protocol/element.html. Am I doing something wrong?

``` javascript
yarn run v1.0.2
$ cd codecept && codeceptjs run --verbose
CodeceptJS v1.0.0
Using test root "/Users/codecept"

webdriverIO test --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook WebDriverIO._beforeSuite()
   [1] Queued | hook WebDriverIOHelper._beforeSuite()
 try to locate element
   Emitted | test.before
   [1] Queued | hook WebDriverIO._before()
   [1] Queued | hook WebDriverIOHelper._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "http://codecept.io/")
   [1] Queued | amOnPage: "http://codecept.io/"
   Emitted | step.after (I am on page "http://codecept.io/")
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I try locate )
   [1] Queued | tryLocate: 
   Emitted | step.after (I try locate )
   [1] Queued | step passed
   [1] Queued | return result
   [1] Queued | create new promises queue for generator
   Emitted | step.start (I am on page "http://codecept.io/")
 • I am on page "http://codecept.io/"
   Emitted | step.passed (I am on page "http://codecept.io/")
   Step finished in 8.602 sec
   Emitted | step.start (I try locate )
 • I try locate 
   [1] Error | TypeError: Cannot read property 'promise' of undefined
   Emitted | step.failed (I try locate )
   Step finished in 0.001 sec
   [1] Error | TypeError: Cannot read property 'promise' of undefined
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook WebDriverIO._failed()
   [1] <teardown> Queued | hook WebDriverIOHelper._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
   [1] <teardown> Starting <generator> session
 > Screenshot has been saved to /Users/codecept/output/try_to_locate_element.failed.png
 ✖ FAILED in 13141ms

   [2] Starting recording promises
   Emitted | test.after
   [2] Queued | hook WebDriverIO._after()
   [2] Queued | hook WebDriverIOHelper._after()
   Emitted | suite.after ([object Object])
   [2] Queued | hook WebDriverIO._afterSuite()
   [2] Queued | hook WebDriverIOHelper._afterSuite()

-- FAILURES:

  1) webdriverIO test: try to locate element:
     Cannot read property 'promise' of undefined
  
  Scenario Steps:
  
  - I.tryLocate() at Test.<anonymous> (tests/homePage_tests.js:5:7)
  - I.amOnPage("http://codecept.io/") at Test.<anonymous> (tests/homePage_tests.js:4:7)
  
  TypeError: Cannot read property 'promise' of undefined
      at commandGroup.(anonymous function) (/Users/.config/yarn/global/node_modules/webdriverio/build/lib/webdriverio.js:701:35)
      at WebDriverIOHelper.tryLocate (WebDriverIOHelper.js:42:16)
      at Step.run (/Users/.config/yarn/global/node_modules/codeceptjs/lib/step.js:28:47)
      at recorder.add (/Users/.config/yarn/global/node_modules/codeceptjs/lib/actor.js:62:27)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)


  FAIL  | 0 passed, 1 failed   // 13s
   Emitted | global.result ([object Object])
   [2] Queued | hook WebDriverIO._finishTest()
   [2] Queued | hook WebDriverIOHelper._finishTest()
error Command failed with exit code 1.

```

**Comment by alias8** [comment]
The above posts were a result from just installing
```npm i codeceptjs```

should I have actually installed 
```npm i codeceptjs-webdriverio``` ? 

thanks for any assistance :)

**Comment by alias8** [comment]
I made a repo with some of the errors I've been experiencing, it's easier if I can show people that way. Thanks 
https://github.com/alias8/codeceptjsDemos/tree/webdriverIO-helper

**Comment by reubenmiller** [comment]
I might be able to help. Here is an example that should work. (Note: no needs to use async/wait stuff in the Helper class (well at least not for this function).

Example is written in ES6.

```javascript
let Helper = codecept_helper;

class WebDriverIOHelper extends Helper {
    /**
      * Try's to locate an element using a selector, without throwing an error when no element does not exist.
      * 
      * @param {string|object} selector. Defaults to 'h1'.
      * @returns {null|string} null is return when the element was not found, otherwise 'a WebElement JSON object for the located element'.
      */
    tryLocate(selector = 'h1') {
        const browser = this.helpers['WebDriverIO'].browser;

        return browser.element(selector)
            .then((res) => {
                console.log('Yay, found the element', res);
                return res;
            })
            .catch((err) => {
                // Catch the error because webdriver.io throws if the element could not be found
                // Source: https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/element.js
                console.log('Element does not exist');
                return null;
            });
    }
}

module.exports = WebDriverIOHelper;

```

**Comment by alias8** [comment]
Awesome, thank you so much for your help! I adjusted the function to return the text in that element. I've updated the github repo with the changes.


```javascript
    tryLocate(selector = 'h1') {
        const browser = this.helpers['WebDriverIO'].browser;

        return browser.element(selector).getText()
            .then((res) => {
                return res;
            })
            .catch((err) => {
                // Catch the error because webdriver.io throws if the element could not be found
                // Source: https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/element.js
                return null;
            });
    }
```

and call it by using: 
```javascript
Feature('HomePage Tests');

Scenario('Check home page', function * (I) {
    I.amOnPage('http://codecept.io/');
    if(yield I.tryLocate('h1') === "CodeceptJS") {
        console.log("text found!")
    } else {
        console.log("text not found!")
    }
    I.wait(10);
});
```

**Comment by reubenmiller** [comment]
You’re welcome. I just noticed that you have a small typo in the test scenario `aync`.

Also the advantage of having the helper function return a promise instead of being an async function is that you can call it from the interactive shell and it behaves as expected. 

Don’t forget to close the issue if everything works.
