### ISSUE TITLE
I.dragAndDrop does not work with WebDriverIO helper

### ISSUE THREAD

**Issue by prashantsail** [Codeception/CodeceptJS#822]
#### What are you trying to achieve?
Using WebDriverIO helper and trying to use I.dragAndDrop

#### What do you get instead?
dragAndDrop fails. 

#### Error on console:
```bash
CodeceptJS v1.0.3
Using test root "/home/prashant_sail/cc/ccIssue"

Codecept Evaluation --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook WebDriverIO._beforeSuite()
 Trial
   Emitted | test.before
   [1] Queued | hook WebDriverIO._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "droppable")
   [1] Queued | amOnPage: "droppable"
   Emitted | step.after (I am on page "droppable")
   [1] Queued | step passed
   [1] Queued | return result
   [1] Queued | register within wrapper
   [1] Queued | fire test.passed
   [1] Queued | finish test
   Emitted | step.start (I am on page "droppable")
 • I am on page "droppable"
   Emitted | step.passed (I am on page "droppable")
   Step finished in 6.07 sec
   [1] Starting <within> session
   Within {"frame":"#content > iframe"}:
   [1] <within> Queued | start within block
   Emitted | step.before (I drag and drop "#draggable", "#droppable")
   [1] <within> Queued | dragAndDrop: "#draggable", "#droppable"
   Emitted | step.after (I drag and drop "#draggable", "#droppable")
   [1] <within> Queued | step passed
   [1] <within> Queued | return result
   [1] <within> Queued | finish within block
   [1] <within> Queued | Finalize within session
   Emitted | step.start (Within {"frame":"#content > iframe"}: I drag and drop "#draggable", "#droppable")
   • Within {"frame":"#content > iframe"}: I drag and drop "#draggable", "#droppable"
WARNING: the "moveTo" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
Note: This command is not part of the W3C WebDriver spec and won't be supported in future versions of the driver. It is recommended to use the actions command to emulate pointer events.

(You can disable this warning by setting `"deprecationWarnings": false` in your WebdriverIO config)
   [1] <within> Error | Error: Unable to move cursor to (#draggable)
   Emitted | step.failed (Within {"frame":"#content > iframe"}: I drag and drop "#draggable", "#droppable")
   Step finished in 0.112 sec
   [1] <within> Error | Error: Unable to move cursor to (#draggable)
   [1] <within> Error | Error: Unable to move cursor to (#draggable)
   [1] <within> Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook WebDriverIO._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
 > Screenshot has been saved to /home/prashant_sail/cc/ccIssue/output/Trial.failed.png
 ✖ FAILED in 6409ms

   [2] Starting recording promises
   Emitted | test.after
   [2] Queued | hook WebDriverIO._after()
   Emitted | suite.after ([object Object])
   [2] Queued | hook WebDriverIO._afterSuite()

-- FAILURES:

  1) Codecept Evaluation: Trial:
     Unable to move cursor to (#draggable)
  
  Scenario Steps:
  
  - Within {"frame":"#content > iframe"}: I.dragAndDrop("#draggable", "#droppable") at within (demo_test.js:6:9)
  - I.amOnPage("droppable") at Test.<anonymous> (demo_test.js:4:5)
  
  Error: Unable to move cursor to (#draggable)
      at Object.<anonymous> (/usr/lib/node_modules/codeceptjs/lib/helper/WebDriverIO.js:1485:42)
      at Object.exec (/usr/lib/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (/usr/lib/node_modules/webdriverio/build/lib/webdriverio.js:191:29)
      at /usr/lib/node_modules/webdriverio/build/lib/webdriverio.js:540:32
      at _fulfilled (/usr/lib/node_modules/webdriverio/node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (/usr/lib/node_modules/webdriverio/node_modules/q/q.js:883:30)
      at Promise.promise.promiseDispatch (/usr/lib/node_modules/webdriverio/node_modules/q/q.js:816:13)
      at /usr/lib/node_modules/webdriverio/node_modules/q/q.js:624:44
      at runSingle (/usr/lib/node_modules/webdriverio/node_modules/q/q.js:137:13)
      at flush (/usr/lib/node_modules/webdriverio/node_modules/q/q.js:125:13)


  FAIL  | 0 passed, 1 failed   // 7s
   Emitted | global.result ([object Object])
   [2] Queued | hook WebDriverIO._finishTest()
```

#### My testcase file(demo_test.js) :
```js
Feature('Codecept Evaluation');

Scenario('Trial', function(I) {
  I.amOnPage('droppable');
    within({frame: "#content > iframe"}, () => {
      I.dragAndDrop('#draggable','#droppable');
    });
});
```

### Details
* CodeceptJS version: 1.0.3
* NodeJS Version: 6.12.0
* Operating System: CentOS Linux release 7.4.1708 (Core)
* WebDriverIO 4.9.11
* Configuration file:
```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "https://jqueryui.com/",
      "browser": "chrome"
      }
  },
  "bootstrap": false,
  "mocha": {},
  "name": "ccIssue"
}
```

**Comment by prashantsail** [comment]
The workaround I am using is -

File : lib/helper/WebDriverIO.js 
Function : dragAndDrop()

I have changed the return statement to -
`return client.dragAndDrop(withStrictLocator(srcElement),withStrictLocator(destElement))`

**Comment by storenth** [comment]
> The workaround I am using is -
> 
> File : lib/helper/WebDriverIO.js
> Function : dragAndDrop()
> 
> I have removed all lines of code starting from
> `return this2.moveCursorTo.....`
> 
> and replaced it with -
> `return client.dragAndDrop(withStrictLocator(srcElement),withStrictLocator(destElement))`

Can you explain with more details this workaround?
