### ISSUE TITLE
"before each" hook: codeceptjs.before: Automate testing time expired.

### ISSUE THREAD

**Issue by vladanp** [Codeception/CodeceptJS#851]
#### What are you trying to achieve?

Run cloud testing.

#### What do you get instead?

"before each" hook: codeceptjs.before for "TEST":
Automate testing time expired.

```bash
[1.basic:chrome] CodeceptJS v1.1.1
[1.basic:chrome] Using test root "<path>"

[1.basic:chrome] Feature --
[1.basic:chrome]    [1] Starting recording promises
[1.basic:chrome]    Emitted | suite.before ([object Object])
[1.basic:chrome]    [1] Queued | hook WebDriverIO._beforeSuite()
[1.basic:chrome]  TEST
[1.basic:chrome]    Emitted | test.before
[1.basic:chrome]    [1] Queued | hook WebDriverIO._before()
[1.basic:chrome]    [1] Error | Error: Automate testing time expired.
[1.basic:chrome]    Emitted | test.failed ([object Object])
[1.basic:chrome]    [1] Queued | hook WebDriverIO._failed()
[1.basic:chrome]  ✖ "before each" hook: codeceptjs.before for "TEST" in 558ms
[1.basic:chrome]    [1] Error | Error: Automate testing time expired.
[1.basic:chrome] Error: Automate testing time expired.
[1.basic:chrome]    Emitted | test.after
[1.basic:chrome]    [1] Queued | hook WebDriverIO._after()
[1.basic:chrome]    Emitted | suite.after ([object Object])
[1.basic:chrome]    [1] Queued | hook WebDriverIO._afterSuite()

[1.basic:chrome] -- FAILURES:

  1) Feature
       "before each" hook: codeceptjs.before for "TEST":
     Automate testing time expired.
  rror: Automate testing time expired.
      at new RuntimeError (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
      at Request._callback (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
      at Request.self.callback (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/request/request.js:186:22)
      at Request.<anonymous> (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/request/request.js:1085:12)


[1.basic:chrome]   FAIL  | 0 passed, 1 failed   // 573ms
[1.basic:chrome]    Emitted | global.result ([object Object])
[1.basic:chrome]    [1] Queued | hook WebDriverIO._finishTest()
```

### Details

* CodeceptJS version: ^1.0.3
* NodeJS Version: 8.9.0
* Operating System: macOS Sierra 10.12.6

* Configuration file:

```js
exports.config = {
    "tests": "./tests/*_test.js",
    "timeout": 10000,
    "output": "./tests/output",
    "helpers": {
        "WebDriverIO": {
            "url": "<url>",
            "browser": "chrome",
            "host": "hub-cloud.browserstack.com",
            "windowSize": "1024x768",
            "user": "<user>",
            "key": "<key>"
        }
    },
    "multiple": {
        "basic": {
            "browsers": [
                "chrome",
                // "firefox",
                // "internet explorer"
            ]
        },
    },
    "include": {},
    "bootstrap": false,
    "mocha": {
        "reporterOptions": {
            "reportDir": "www/tests/output/"
        }
    }
};
```

The same codebase was running correctly until it suddenly stopped working. I am using browserstack cloud testing. Changing versions of codeceptjs didn't help.

**Comment by morwalz** [comment]
how did you fix this issue. it was working before then suddenly stopped working.
